// Autogenerated from Pigeon (v27.1.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

enum MessagesPigeonInternal {
  static func isNullish(_ value: Any?) -> Bool {
    guard let innerValue = value else {
      return true
    }

    if case Optional<Any>.some(Optional<Any>.none) = value {
      return true
    }

    return innerValue is NSNull
  }
  static func doubleEquals(_ lhs: Double, _ rhs: Double) -> Bool {
    return (lhs.isNaN && rhs.isNaN) || lhs == rhs
  }

  static func doubleHash(_ value: Double, _ hasher: inout Hasher) {
    if value.isNaN {
      hasher.combine(0x7FF8000000000000)
    } else {
      // Normalize -0.0 to 0.0
      hasher.combine(value == 0 ? 0 : value)
    }
  }

  static func deepEquals(_ lhs: Any?, _ rhs: Any?) -> Bool {
    let cleanLhs = nilOrValue(lhs) as Any?
    let cleanRhs = nilOrValue(rhs) as Any?
    switch (cleanLhs, cleanRhs) {
    case (nil, nil):
      return true

    case (nil, _), (_, nil):
      return false

    case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
      return true

    case is (Void, Void):
      return true

    case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !deepEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsArray, let rhsArray) as ([Double], [Double]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !doubleEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
      guard lhsDictionary.count == rhsDictionary.count else { return false }
      for (lhsKey, lhsValue) in lhsDictionary {
        var found = false
        for (rhsKey, rhsValue) in rhsDictionary {
          if deepEquals(lhsKey, rhsKey) {
            if deepEquals(lhsValue, rhsValue) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if !found { return false }
      }
      return true

    case (let lhs as Double, let rhs as Double):
      return doubleEquals(lhs, rhs)

    case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
      return lhsHashable == rhsHashable

    default:
      return false
    }
  }

  static func deepHash(value: Any?, hasher: inout Hasher) {
    let cleanValue = nilOrValue(value) as Any?
    if let cleanValue = cleanValue {
      if let doubleValue = cleanValue as? Double {
        doubleHash(doubleValue, &hasher)
      } else if let valueList = cleanValue as? [Any?] {
        for item in valueList {
          deepHash(value: item, hasher: &hasher)
        }
      } else if let valueList = cleanValue as? [Double] {
        for item in valueList {
          doubleHash(item, &hasher)
        }
      } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
        var result = 0
        for (key, value) in valueDict {
          var entryKeyHasher = Hasher()
          deepHash(value: key, hasher: &entryKeyHasher)
          var entryValueHasher = Hasher()
          deepHash(value: value, hasher: &entryValueHasher)
          result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
        }
        hasher.combine(result)
      } else if let hashableValue = cleanValue as? AnyHashable {
        hasher.combine(hashableValue)
      } else {
        hasher.combine(String(describing: cleanValue))
      }
    } else {
      hasher.combine(0)
    }
  }

}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


enum BluetoothAdapterState: Int, CaseIterable {
  case unknown = 0
  case unavailable = 1
  case unauthorized = 2
  case turningOn = 3
  case on = 4
  case turningOff = 5
  case off = 6
}

enum BluetoothConnectionState: Int, CaseIterable {
  case disconnected = 0
  case connected = 1
}

enum BmWriteType: Int, CaseIterable {
  case withResponse = 0
  case withoutResponse = 1
}

enum ConnectionPriority: Int, CaseIterable {
  case balanced = 0
  case high = 1
  case lowPower = 2
}

enum BluetoothBondState: Int, CaseIterable {
  case none = 0
  case bonding = 1
  case bonded = 2
}

enum LogLevel: Int, CaseIterable {
  case none = 0
  case error = 1
  case warning = 2
  case info = 3
  case debug = 4
  case verbose = 5
}

/// Single source of truth for error codes, shared by every platform.
///
/// Errors cross the channel as `PlatformException.code` *strings* (pigeon
/// cannot type that field), so the wire form of each code is, by convention,
/// the snake_case of its name here (e.g. [BluebirdErrorCode.deviceDisconnected]
/// crosses as `"device_disconnected"`). Each language has a small `wire`
/// helper implementing that convention; never hand-write a code string.
enum BluebirdErrorCode: Int, CaseIterable {
  case success = 0
  case timeout = 1
  case platform = 2
  case serviceNotFound = 3
  case characteristicNotFound = 4
  case userRejected = 5
  case removeBondFailed = 6
  /// An Android-side GATT stack/link failure — e.g. a `BluetoothGatt` call
  /// returned false/null, an HCI disconnect, or `GATT_FAILURE`. Not a peer
  /// response; see [attError]. The darwin analogue is [darwinError].
  case androidError = 7
  /// A darwin-side (CoreBluetooth) stack/link failure — a non-`CBATTErrorDomain`
  /// `NSError` (e.g. connection lost). Not a peer response; see [attError]. The
  /// android analogue is [androidError].
  case darwinError = 8
  /// A Bluetooth spec-level error: the peer answered a request with an ATT
  /// Error Response. Raised uniformly by every platform, with the raw one-octet
  /// code (an `int`, spanning the core ATT / application / GATT common ranges)
  /// riding along as the error details. Platform/link failures that are *not*
  /// peer responses stay [androidError] / [darwinError].
  case attError = 9
  case deviceDisconnected = 10
  case adapterOff = 11
  case notConnected = 12
  case invalidIdentifier = 13
  case bondFailed = 14
  case userCanceled = 15
  case unsupported = 16
  case operationInProgress = 17
  case permissionDenied = 18
  case invalidArgument = 19
}

/// The universal uuid:instance pair identifying one attribute.
///
/// Generated class from Pigeon that represents data sent in messages.
struct BmAttributeId: Hashable, CustomStringConvertible {
  var uuid: String
  /// Platform-opaque token disambiguating duplicate uuids.
  var instance: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> BmAttributeId? {
    let uuid = pigeonVar_list[0] as! String
    let instance = pigeonVar_list[1] as! Int64

    return BmAttributeId(
      uuid: uuid,
      instance: instance
    )
  }
  func toList() -> [Any?] {
    return [
      uuid,
      instance,
    ]
  }
  static func == (lhs: BmAttributeId, rhs: BmAttributeId) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.uuid, rhs.uuid) && MessagesPigeonInternal.deepEquals(lhs.instance, rhs.instance)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("BmAttributeId")
    MessagesPigeonInternal.deepHash(value: uuid, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: instance, hasher: &hasher)
  }

  public var description: String {
    return "BmAttributeId(uuid: \(String(describing: uuid)), instance: \(String(describing: instance)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct BmServiceRef: Hashable, CustomStringConvertible {
  var service: BmAttributeId
  /// Set when this is a secondary (included) service.
  var parentService: BmAttributeId? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> BmServiceRef? {
    let service = pigeonVar_list[0] as! BmAttributeId
    let parentService: BmAttributeId? = nilOrValue(pigeonVar_list[1])

    return BmServiceRef(
      service: service,
      parentService: parentService
    )
  }
  func toList() -> [Any?] {
    return [
      service,
      parentService,
    ]
  }
  static func == (lhs: BmServiceRef, rhs: BmServiceRef) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.service, rhs.service) && MessagesPigeonInternal.deepEquals(lhs.parentService, rhs.parentService)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("BmServiceRef")
    MessagesPigeonInternal.deepHash(value: service, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: parentService, hasher: &hasher)
  }

  public var description: String {
    return "BmServiceRef(service: \(String(describing: service)), parentService: \(String(describing: parentService)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct BmCharacteristicRef: Hashable, CustomStringConvertible {
  var service: BmServiceRef
  var characteristic: BmAttributeId


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> BmCharacteristicRef? {
    let service = pigeonVar_list[0] as! BmServiceRef
    let characteristic = pigeonVar_list[1] as! BmAttributeId

    return BmCharacteristicRef(
      service: service,
      characteristic: characteristic
    )
  }
  func toList() -> [Any?] {
    return [
      service,
      characteristic,
    ]
  }
  static func == (lhs: BmCharacteristicRef, rhs: BmCharacteristicRef) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.service, rhs.service) && MessagesPigeonInternal.deepEquals(lhs.characteristic, rhs.characteristic)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("BmCharacteristicRef")
    MessagesPigeonInternal.deepHash(value: service, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: characteristic, hasher: &hasher)
  }

  public var description: String {
    return "BmCharacteristicRef(service: \(String(describing: service)), characteristic: \(String(describing: characteristic)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct BmDescriptorRef: Hashable, CustomStringConvertible {
  var characteristic: BmCharacteristicRef
  /// Descriptors are uuid-unique within a characteristic, so [id]'s instance is
  /// always 0; the [BmAttributeId] keeps descriptors uniform with services and
  /// characteristics.
  var id: BmAttributeId


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> BmDescriptorRef? {
    let characteristic = pigeonVar_list[0] as! BmCharacteristicRef
    let id = pigeonVar_list[1] as! BmAttributeId

    return BmDescriptorRef(
      characteristic: characteristic,
      id: id
    )
  }
  func toList() -> [Any?] {
    return [
      characteristic,
      id,
    ]
  }
  static func == (lhs: BmDescriptorRef, rhs: BmDescriptorRef) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.characteristic, rhs.characteristic) && MessagesPigeonInternal.deepEquals(lhs.id, rhs.id)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("BmDescriptorRef")
    MessagesPigeonInternal.deepHash(value: characteristic, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: id, hasher: &hasher)
  }

  public var description: String {
    return "BmDescriptorRef(characteristic: \(String(describing: characteristic)), id: \(String(describing: id)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct BmMsdFilter: Hashable, CustomStringConvertible {
  var manufacturerId: Int64
  var data: FlutterStandardTypedData? = nil
  var mask: FlutterStandardTypedData? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> BmMsdFilter? {
    let manufacturerId = pigeonVar_list[0] as! Int64
    let data: FlutterStandardTypedData? = nilOrValue(pigeonVar_list[1])
    let mask: FlutterStandardTypedData? = nilOrValue(pigeonVar_list[2])

    return BmMsdFilter(
      manufacturerId: manufacturerId,
      data: data,
      mask: mask
    )
  }
  func toList() -> [Any?] {
    return [
      manufacturerId,
      data,
      mask,
    ]
  }
  static func == (lhs: BmMsdFilter, rhs: BmMsdFilter) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.manufacturerId, rhs.manufacturerId) && MessagesPigeonInternal.deepEquals(lhs.data, rhs.data) && MessagesPigeonInternal.deepEquals(lhs.mask, rhs.mask)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("BmMsdFilter")
    MessagesPigeonInternal.deepHash(value: manufacturerId, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: data, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: mask, hasher: &hasher)
  }

  public var description: String {
    return "BmMsdFilter(manufacturerId: \(String(describing: manufacturerId)), data: \(String(describing: data)), mask: \(String(describing: mask)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct BmServiceDataFilter: Hashable, CustomStringConvertible {
  var service: String
  var data: FlutterStandardTypedData
  var mask: FlutterStandardTypedData? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> BmServiceDataFilter? {
    let service = pigeonVar_list[0] as! String
    let data = pigeonVar_list[1] as! FlutterStandardTypedData
    let mask: FlutterStandardTypedData? = nilOrValue(pigeonVar_list[2])

    return BmServiceDataFilter(
      service: service,
      data: data,
      mask: mask
    )
  }
  func toList() -> [Any?] {
    return [
      service,
      data,
      mask,
    ]
  }
  static func == (lhs: BmServiceDataFilter, rhs: BmServiceDataFilter) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.service, rhs.service) && MessagesPigeonInternal.deepEquals(lhs.data, rhs.data) && MessagesPigeonInternal.deepEquals(lhs.mask, rhs.mask)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("BmServiceDataFilter")
    MessagesPigeonInternal.deepHash(value: service, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: data, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: mask, hasher: &hasher)
  }

  public var description: String {
    return "BmServiceDataFilter(service: \(String(describing: service)), data: \(String(describing: data)), mask: \(String(describing: mask)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct BmScanSettings: Hashable, CustomStringConvertible {
  var withServices: [String]
  var withRemoteIds: [String]
  var withNames: [String]
  var withKeywords: [String]
  var withMsd: [BmMsdFilter]
  var withServiceData: [BmServiceDataFilter]
  var continuousUpdates: Bool
  var continuousDivisor: Int64
  var androidLegacy: Bool
  var androidScanMode: Int64
  var androidUsesFineLocation: Bool
  var webOptionalServices: [String]


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> BmScanSettings? {
    let withServices = pigeonVar_list[0] as! [String]
    let withRemoteIds = pigeonVar_list[1] as! [String]
    let withNames = pigeonVar_list[2] as! [String]
    let withKeywords = pigeonVar_list[3] as! [String]
    let withMsd = pigeonVar_list[4] as! [BmMsdFilter]
    let withServiceData = pigeonVar_list[5] as! [BmServiceDataFilter]
    let continuousUpdates = pigeonVar_list[6] as! Bool
    let continuousDivisor = pigeonVar_list[7] as! Int64
    let androidLegacy = pigeonVar_list[8] as! Bool
    let androidScanMode = pigeonVar_list[9] as! Int64
    let androidUsesFineLocation = pigeonVar_list[10] as! Bool
    let webOptionalServices = pigeonVar_list[11] as! [String]

    return BmScanSettings(
      withServices: withServices,
      withRemoteIds: withRemoteIds,
      withNames: withNames,
      withKeywords: withKeywords,
      withMsd: withMsd,
      withServiceData: withServiceData,
      continuousUpdates: continuousUpdates,
      continuousDivisor: continuousDivisor,
      androidLegacy: androidLegacy,
      androidScanMode: androidScanMode,
      androidUsesFineLocation: androidUsesFineLocation,
      webOptionalServices: webOptionalServices
    )
  }
  func toList() -> [Any?] {
    return [
      withServices,
      withRemoteIds,
      withNames,
      withKeywords,
      withMsd,
      withServiceData,
      continuousUpdates,
      continuousDivisor,
      androidLegacy,
      androidScanMode,
      androidUsesFineLocation,
      webOptionalServices,
    ]
  }
  static func == (lhs: BmScanSettings, rhs: BmScanSettings) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.withServices, rhs.withServices) && MessagesPigeonInternal.deepEquals(lhs.withRemoteIds, rhs.withRemoteIds) && MessagesPigeonInternal.deepEquals(lhs.withNames, rhs.withNames) && MessagesPigeonInternal.deepEquals(lhs.withKeywords, rhs.withKeywords) && MessagesPigeonInternal.deepEquals(lhs.withMsd, rhs.withMsd) && MessagesPigeonInternal.deepEquals(lhs.withServiceData, rhs.withServiceData) && MessagesPigeonInternal.deepEquals(lhs.continuousUpdates, rhs.continuousUpdates) && MessagesPigeonInternal.deepEquals(lhs.continuousDivisor, rhs.continuousDivisor) && MessagesPigeonInternal.deepEquals(lhs.androidLegacy, rhs.androidLegacy) && MessagesPigeonInternal.deepEquals(lhs.androidScanMode, rhs.androidScanMode) && MessagesPigeonInternal.deepEquals(lhs.androidUsesFineLocation, rhs.androidUsesFineLocation) && MessagesPigeonInternal.deepEquals(lhs.webOptionalServices, rhs.webOptionalServices)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("BmScanSettings")
    MessagesPigeonInternal.deepHash(value: withServices, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: withRemoteIds, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: withNames, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: withKeywords, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: withMsd, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: withServiceData, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: continuousUpdates, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: continuousDivisor, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: androidLegacy, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: androidScanMode, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: androidUsesFineLocation, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: webOptionalServices, hasher: &hasher)
  }

  public var description: String {
    return "BmScanSettings(withServices: \(String(describing: withServices)), withRemoteIds: \(String(describing: withRemoteIds)), withNames: \(String(describing: withNames)), withKeywords: \(String(describing: withKeywords)), withMsd: \(String(describing: withMsd)), withServiceData: \(String(describing: withServiceData)), continuousUpdates: \(String(describing: continuousUpdates)), continuousDivisor: \(String(describing: continuousDivisor)), androidLegacy: \(String(describing: androidLegacy)), androidScanMode: \(String(describing: androidScanMode)), androidUsesFineLocation: \(String(describing: androidUsesFineLocation)), webOptionalServices: \(String(describing: webOptionalServices)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct BmScanAdvertisement: Hashable, CustomStringConvertible {
  var address: String
  var platformName: String? = nil
  var advName: String? = nil
  var connectable: Bool
  var txPowerLevel: Int64? = nil
  /// Not supported on iOS / macOS.
  var appearance: Int64? = nil
  var manufacturerData: [Int64: FlutterStandardTypedData]
  var serviceData: [String: FlutterStandardTypedData]
  var serviceUuids: [String]
  var rssi: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> BmScanAdvertisement? {
    let address = pigeonVar_list[0] as! String
    let platformName: String? = nilOrValue(pigeonVar_list[1])
    let advName: String? = nilOrValue(pigeonVar_list[2])
    let connectable = pigeonVar_list[3] as! Bool
    let txPowerLevel: Int64? = nilOrValue(pigeonVar_list[4])
    let appearance: Int64? = nilOrValue(pigeonVar_list[5])
    let manufacturerData = pigeonVar_list[6] as! [Int64: FlutterStandardTypedData]
    let serviceData = pigeonVar_list[7] as! [String: FlutterStandardTypedData]
    let serviceUuids = pigeonVar_list[8] as! [String]
    let rssi = pigeonVar_list[9] as! Int64

    return BmScanAdvertisement(
      address: address,
      platformName: platformName,
      advName: advName,
      connectable: connectable,
      txPowerLevel: txPowerLevel,
      appearance: appearance,
      manufacturerData: manufacturerData,
      serviceData: serviceData,
      serviceUuids: serviceUuids,
      rssi: rssi
    )
  }
  func toList() -> [Any?] {
    return [
      address,
      platformName,
      advName,
      connectable,
      txPowerLevel,
      appearance,
      manufacturerData,
      serviceData,
      serviceUuids,
      rssi,
    ]
  }
  static func == (lhs: BmScanAdvertisement, rhs: BmScanAdvertisement) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.address, rhs.address) && MessagesPigeonInternal.deepEquals(lhs.platformName, rhs.platformName) && MessagesPigeonInternal.deepEquals(lhs.advName, rhs.advName) && MessagesPigeonInternal.deepEquals(lhs.connectable, rhs.connectable) && MessagesPigeonInternal.deepEquals(lhs.txPowerLevel, rhs.txPowerLevel) && MessagesPigeonInternal.deepEquals(lhs.appearance, rhs.appearance) && MessagesPigeonInternal.deepEquals(lhs.manufacturerData, rhs.manufacturerData) && MessagesPigeonInternal.deepEquals(lhs.serviceData, rhs.serviceData) && MessagesPigeonInternal.deepEquals(lhs.serviceUuids, rhs.serviceUuids) && MessagesPigeonInternal.deepEquals(lhs.rssi, rhs.rssi)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("BmScanAdvertisement")
    MessagesPigeonInternal.deepHash(value: address, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: platformName, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: advName, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: connectable, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: txPowerLevel, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: appearance, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: manufacturerData, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: serviceData, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: serviceUuids, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: rssi, hasher: &hasher)
  }

  public var description: String {
    return "BmScanAdvertisement(address: \(String(describing: address)), platformName: \(String(describing: platformName)), advName: \(String(describing: advName)), connectable: \(String(describing: connectable)), txPowerLevel: \(String(describing: txPowerLevel)), appearance: \(String(describing: appearance)), manufacturerData: \(String(describing: manufacturerData)), serviceData: \(String(describing: serviceData)), serviceUuids: \(String(describing: serviceUuids)), rssi: \(String(describing: rssi)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct BmBluetoothDevice: Hashable, CustomStringConvertible {
  var address: String
  var platformName: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> BmBluetoothDevice? {
    let address = pigeonVar_list[0] as! String
    let platformName: String? = nilOrValue(pigeonVar_list[1])

    return BmBluetoothDevice(
      address: address,
      platformName: platformName
    )
  }
  func toList() -> [Any?] {
    return [
      address,
      platformName,
    ]
  }
  static func == (lhs: BmBluetoothDevice, rhs: BmBluetoothDevice) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.address, rhs.address) && MessagesPigeonInternal.deepEquals(lhs.platformName, rhs.platformName)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("BmBluetoothDevice")
    MessagesPigeonInternal.deepHash(value: address, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: platformName, hasher: &hasher)
  }

  public var description: String {
    return "BmBluetoothDevice(address: \(String(describing: address)), platformName: \(String(describing: platformName)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct BmBluetoothService: Hashable, CustomStringConvertible {
  var id: BmAttributeId
  var isPrimary: Bool
  var characteristics: [BmBluetoothCharacteristic]
  var includedServices: [BmServiceRef]


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> BmBluetoothService? {
    let id = pigeonVar_list[0] as! BmAttributeId
    let isPrimary = pigeonVar_list[1] as! Bool
    let characteristics = pigeonVar_list[2] as! [BmBluetoothCharacteristic]
    let includedServices = pigeonVar_list[3] as! [BmServiceRef]

    return BmBluetoothService(
      id: id,
      isPrimary: isPrimary,
      characteristics: characteristics,
      includedServices: includedServices
    )
  }
  func toList() -> [Any?] {
    return [
      id,
      isPrimary,
      characteristics,
      includedServices,
    ]
  }
  static func == (lhs: BmBluetoothService, rhs: BmBluetoothService) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.id, rhs.id) && MessagesPigeonInternal.deepEquals(lhs.isPrimary, rhs.isPrimary) && MessagesPigeonInternal.deepEquals(lhs.characteristics, rhs.characteristics) && MessagesPigeonInternal.deepEquals(lhs.includedServices, rhs.includedServices)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("BmBluetoothService")
    MessagesPigeonInternal.deepHash(value: id, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: isPrimary, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: characteristics, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: includedServices, hasher: &hasher)
  }

  public var description: String {
    return "BmBluetoothService(id: \(String(describing: id)), isPrimary: \(String(describing: isPrimary)), characteristics: \(String(describing: characteristics)), includedServices: \(String(describing: includedServices)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct BmBluetoothCharacteristic: Hashable, CustomStringConvertible {
  var id: BmAttributeId
  var descriptors: [BmBluetoothDescriptor]
  var properties: BmCharacteristicProperties


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> BmBluetoothCharacteristic? {
    let id = pigeonVar_list[0] as! BmAttributeId
    let descriptors = pigeonVar_list[1] as! [BmBluetoothDescriptor]
    let properties = pigeonVar_list[2] as! BmCharacteristicProperties

    return BmBluetoothCharacteristic(
      id: id,
      descriptors: descriptors,
      properties: properties
    )
  }
  func toList() -> [Any?] {
    return [
      id,
      descriptors,
      properties,
    ]
  }
  static func == (lhs: BmBluetoothCharacteristic, rhs: BmBluetoothCharacteristic) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.id, rhs.id) && MessagesPigeonInternal.deepEquals(lhs.descriptors, rhs.descriptors) && MessagesPigeonInternal.deepEquals(lhs.properties, rhs.properties)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("BmBluetoothCharacteristic")
    MessagesPigeonInternal.deepHash(value: id, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: descriptors, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: properties, hasher: &hasher)
  }

  public var description: String {
    return "BmBluetoothCharacteristic(id: \(String(describing: id)), descriptors: \(String(describing: descriptors)), properties: \(String(describing: properties)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct BmBluetoothDescriptor: Hashable, CustomStringConvertible {
  var id: BmAttributeId


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> BmBluetoothDescriptor? {
    let id = pigeonVar_list[0] as! BmAttributeId

    return BmBluetoothDescriptor(
      id: id
    )
  }
  func toList() -> [Any?] {
    return [
      id
    ]
  }
  static func == (lhs: BmBluetoothDescriptor, rhs: BmBluetoothDescriptor) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.id, rhs.id)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("BmBluetoothDescriptor")
    MessagesPigeonInternal.deepHash(value: id, hasher: &hasher)
  }

  public var description: String {
    return "BmBluetoothDescriptor(id: \(String(describing: id)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct BmCharacteristicProperties: Hashable, CustomStringConvertible {
  var broadcast: Bool
  var read: Bool
  var writeWithoutResponse: Bool
  var write: Bool
  var notify: Bool
  var indicate: Bool
  var authenticatedSignedWrites: Bool
  var extendedProperties: Bool
  var notifyEncryptionRequired: Bool
  var indicateEncryptionRequired: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> BmCharacteristicProperties? {
    let broadcast = pigeonVar_list[0] as! Bool
    let read = pigeonVar_list[1] as! Bool
    let writeWithoutResponse = pigeonVar_list[2] as! Bool
    let write = pigeonVar_list[3] as! Bool
    let notify = pigeonVar_list[4] as! Bool
    let indicate = pigeonVar_list[5] as! Bool
    let authenticatedSignedWrites = pigeonVar_list[6] as! Bool
    let extendedProperties = pigeonVar_list[7] as! Bool
    let notifyEncryptionRequired = pigeonVar_list[8] as! Bool
    let indicateEncryptionRequired = pigeonVar_list[9] as! Bool

    return BmCharacteristicProperties(
      broadcast: broadcast,
      read: read,
      writeWithoutResponse: writeWithoutResponse,
      write: write,
      notify: notify,
      indicate: indicate,
      authenticatedSignedWrites: authenticatedSignedWrites,
      extendedProperties: extendedProperties,
      notifyEncryptionRequired: notifyEncryptionRequired,
      indicateEncryptionRequired: indicateEncryptionRequired
    )
  }
  func toList() -> [Any?] {
    return [
      broadcast,
      read,
      writeWithoutResponse,
      write,
      notify,
      indicate,
      authenticatedSignedWrites,
      extendedProperties,
      notifyEncryptionRequired,
      indicateEncryptionRequired,
    ]
  }
  static func == (lhs: BmCharacteristicProperties, rhs: BmCharacteristicProperties) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.broadcast, rhs.broadcast) && MessagesPigeonInternal.deepEquals(lhs.read, rhs.read) && MessagesPigeonInternal.deepEquals(lhs.writeWithoutResponse, rhs.writeWithoutResponse) && MessagesPigeonInternal.deepEquals(lhs.write, rhs.write) && MessagesPigeonInternal.deepEquals(lhs.notify, rhs.notify) && MessagesPigeonInternal.deepEquals(lhs.indicate, rhs.indicate) && MessagesPigeonInternal.deepEquals(lhs.authenticatedSignedWrites, rhs.authenticatedSignedWrites) && MessagesPigeonInternal.deepEquals(lhs.extendedProperties, rhs.extendedProperties) && MessagesPigeonInternal.deepEquals(lhs.notifyEncryptionRequired, rhs.notifyEncryptionRequired) && MessagesPigeonInternal.deepEquals(lhs.indicateEncryptionRequired, rhs.indicateEncryptionRequired)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("BmCharacteristicProperties")
    MessagesPigeonInternal.deepHash(value: broadcast, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: read, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: writeWithoutResponse, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: write, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: notify, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: indicate, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: authenticatedSignedWrites, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: extendedProperties, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: notifyEncryptionRequired, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: indicateEncryptionRequired, hasher: &hasher)
  }

  public var description: String {
    return "BmCharacteristicProperties(broadcast: \(String(describing: broadcast)), read: \(String(describing: read)), writeWithoutResponse: \(String(describing: writeWithoutResponse)), write: \(String(describing: write)), notify: \(String(describing: notify)), indicate: \(String(describing: indicate)), authenticatedSignedWrites: \(String(describing: authenticatedSignedWrites)), extendedProperties: \(String(describing: extendedProperties)), notifyEncryptionRequired: \(String(describing: notifyEncryptionRequired)), indicateEncryptionRequired: \(String(describing: indicateEncryptionRequired)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct BmPhySupport: Hashable, CustomStringConvertible {
  /// High speed (PHY 2M)
  var le2M: Bool
  /// Long range (PHY codec)
  var leCoded: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> BmPhySupport? {
    let le2M = pigeonVar_list[0] as! Bool
    let leCoded = pigeonVar_list[1] as! Bool

    return BmPhySupport(
      le2M: le2M,
      leCoded: leCoded
    )
  }
  func toList() -> [Any?] {
    return [
      le2M,
      leCoded,
    ]
  }
  static func == (lhs: BmPhySupport, rhs: BmPhySupport) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.le2M, rhs.le2M) && MessagesPigeonInternal.deepEquals(lhs.leCoded, rhs.leCoded)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("BmPhySupport")
    MessagesPigeonInternal.deepHash(value: le2M, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: leCoded, hasher: &hasher)
  }

  public var description: String {
    return "BmPhySupport(le2M: \(String(describing: le2M)), leCoded: \(String(describing: leCoded)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
/// This protocol should not be extended by any user class outside of the generated file.
protocol BmEvent {

}

/// Generated class from Pigeon that represents data sent in messages.
struct BmAdapterStateEvent: BmEvent {
  var adapterState: BluetoothAdapterState


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> BmAdapterStateEvent? {
    let adapterState = pigeonVar_list[0] as! BluetoothAdapterState

    return BmAdapterStateEvent(
      adapterState: adapterState
    )
  }
  func toList() -> [Any?] {
    return [
      adapterState
    ]
  }
  static func == (lhs: BmAdapterStateEvent, rhs: BmAdapterStateEvent) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.adapterState, rhs.adapterState)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("BmAdapterStateEvent")
    MessagesPigeonInternal.deepHash(value: adapterState, hasher: &hasher)
  }

  public var description: String {
    return "BmAdapterStateEvent(adapterState: \(String(describing: adapterState)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct BmScanAdvertisementEvent: BmEvent {
  var advertisement: BmScanAdvertisement


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> BmScanAdvertisementEvent? {
    let advertisement = pigeonVar_list[0] as! BmScanAdvertisement

    return BmScanAdvertisementEvent(
      advertisement: advertisement
    )
  }
  func toList() -> [Any?] {
    return [
      advertisement
    ]
  }
  static func == (lhs: BmScanAdvertisementEvent, rhs: BmScanAdvertisementEvent) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.advertisement, rhs.advertisement)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("BmScanAdvertisementEvent")
    MessagesPigeonInternal.deepHash(value: advertisement, hasher: &hasher)
  }

  public var description: String {
    return "BmScanAdvertisementEvent(advertisement: \(String(describing: advertisement)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct BmScanFailedEvent: BmEvent {
  var errorCode: Int64
  var errorString: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> BmScanFailedEvent? {
    let errorCode = pigeonVar_list[0] as! Int64
    let errorString = pigeonVar_list[1] as! String

    return BmScanFailedEvent(
      errorCode: errorCode,
      errorString: errorString
    )
  }
  func toList() -> [Any?] {
    return [
      errorCode,
      errorString,
    ]
  }
  static func == (lhs: BmScanFailedEvent, rhs: BmScanFailedEvent) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.errorCode, rhs.errorCode) && MessagesPigeonInternal.deepEquals(lhs.errorString, rhs.errorString)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("BmScanFailedEvent")
    MessagesPigeonInternal.deepHash(value: errorCode, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: errorString, hasher: &hasher)
  }

  public var description: String {
    return "BmScanFailedEvent(errorCode: \(String(describing: errorCode)), errorString: \(String(describing: errorString)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct BmConnectionStateEvent: BmEvent {
  var address: String
  var connectionState: BluetoothConnectionState
  var disconnectReasonCode: Int64? = nil
  var disconnectReasonString: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> BmConnectionStateEvent? {
    let address = pigeonVar_list[0] as! String
    let connectionState = pigeonVar_list[1] as! BluetoothConnectionState
    let disconnectReasonCode: Int64? = nilOrValue(pigeonVar_list[2])
    let disconnectReasonString: String? = nilOrValue(pigeonVar_list[3])

    return BmConnectionStateEvent(
      address: address,
      connectionState: connectionState,
      disconnectReasonCode: disconnectReasonCode,
      disconnectReasonString: disconnectReasonString
    )
  }
  func toList() -> [Any?] {
    return [
      address,
      connectionState,
      disconnectReasonCode,
      disconnectReasonString,
    ]
  }
  static func == (lhs: BmConnectionStateEvent, rhs: BmConnectionStateEvent) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.address, rhs.address) && MessagesPigeonInternal.deepEquals(lhs.connectionState, rhs.connectionState) && MessagesPigeonInternal.deepEquals(lhs.disconnectReasonCode, rhs.disconnectReasonCode) && MessagesPigeonInternal.deepEquals(lhs.disconnectReasonString, rhs.disconnectReasonString)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("BmConnectionStateEvent")
    MessagesPigeonInternal.deepHash(value: address, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: connectionState, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: disconnectReasonCode, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: disconnectReasonString, hasher: &hasher)
  }

  public var description: String {
    return "BmConnectionStateEvent(address: \(String(describing: address)), connectionState: \(String(describing: connectionState)), disconnectReasonCode: \(String(describing: disconnectReasonCode)), disconnectReasonString: \(String(describing: disconnectReasonString)))"
  }
}

/// A characteristic value received via notify/indicate. Read responses are
/// returned from [BluebirdHostApi.readCharacteristic] instead.
///
/// Generated class from Pigeon that represents data sent in messages.
struct BmCharacteristicNotificationEvent: BmEvent {
  var address: String
  var characteristic: BmCharacteristicRef
  var value: FlutterStandardTypedData


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> BmCharacteristicNotificationEvent? {
    let address = pigeonVar_list[0] as! String
    let characteristic = pigeonVar_list[1] as! BmCharacteristicRef
    let value = pigeonVar_list[2] as! FlutterStandardTypedData

    return BmCharacteristicNotificationEvent(
      address: address,
      characteristic: characteristic,
      value: value
    )
  }
  func toList() -> [Any?] {
    return [
      address,
      characteristic,
      value,
    ]
  }
  static func == (lhs: BmCharacteristicNotificationEvent, rhs: BmCharacteristicNotificationEvent) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.address, rhs.address) && MessagesPigeonInternal.deepEquals(lhs.characteristic, rhs.characteristic) && MessagesPigeonInternal.deepEquals(lhs.value, rhs.value)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("BmCharacteristicNotificationEvent")
    MessagesPigeonInternal.deepHash(value: address, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: characteristic, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: value, hasher: &hasher)
  }

  public var description: String {
    return "BmCharacteristicNotificationEvent(address: \(String(describing: address)), characteristic: \(String(describing: characteristic)), value: \(String(describing: value)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct BmBondStateEvent: BmEvent {
  var address: String
  var bondState: BluetoothBondState
  var prevState: BluetoothBondState? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> BmBondStateEvent? {
    let address = pigeonVar_list[0] as! String
    let bondState = pigeonVar_list[1] as! BluetoothBondState
    let prevState: BluetoothBondState? = nilOrValue(pigeonVar_list[2])

    return BmBondStateEvent(
      address: address,
      bondState: bondState,
      prevState: prevState
    )
  }
  func toList() -> [Any?] {
    return [
      address,
      bondState,
      prevState,
    ]
  }
  static func == (lhs: BmBondStateEvent, rhs: BmBondStateEvent) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.address, rhs.address) && MessagesPigeonInternal.deepEquals(lhs.bondState, rhs.bondState) && MessagesPigeonInternal.deepEquals(lhs.prevState, rhs.prevState)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("BmBondStateEvent")
    MessagesPigeonInternal.deepHash(value: address, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: bondState, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: prevState, hasher: &hasher)
  }

  public var description: String {
    return "BmBondStateEvent(address: \(String(describing: address)), bondState: \(String(describing: bondState)), prevState: \(String(describing: prevState)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct BmNameChangedEvent: BmEvent {
  var address: String
  var name: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> BmNameChangedEvent? {
    let address = pigeonVar_list[0] as! String
    let name = pigeonVar_list[1] as! String

    return BmNameChangedEvent(
      address: address,
      name: name
    )
  }
  func toList() -> [Any?] {
    return [
      address,
      name,
    ]
  }
  static func == (lhs: BmNameChangedEvent, rhs: BmNameChangedEvent) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.address, rhs.address) && MessagesPigeonInternal.deepEquals(lhs.name, rhs.name)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("BmNameChangedEvent")
    MessagesPigeonInternal.deepHash(value: address, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: name, hasher: &hasher)
  }

  public var description: String {
    return "BmNameChangedEvent(address: \(String(describing: address)), name: \(String(describing: name)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct BmServicesResetEvent: BmEvent {
  var address: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> BmServicesResetEvent? {
    let address = pigeonVar_list[0] as! String

    return BmServicesResetEvent(
      address: address
    )
  }
  func toList() -> [Any?] {
    return [
      address
    ]
  }
  static func == (lhs: BmServicesResetEvent, rhs: BmServicesResetEvent) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.address, rhs.address)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("BmServicesResetEvent")
    MessagesPigeonInternal.deepHash(value: address, hasher: &hasher)
  }

  public var description: String {
    return "BmServicesResetEvent(address: \(String(describing: address)))"
  }
}

/// Emitted on any MTU change: solicited (requestMtu) or peer-initiated on
/// Android; on darwin, emitted after connect and whenever the negotiated
/// value changes (CoreBluetooth has no MTU callback, so the plugin polls
/// while devices are connected).
///
/// Generated class from Pigeon that represents data sent in messages.
struct BmMtuChangedEvent: BmEvent {
  var address: String
  var mtu: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> BmMtuChangedEvent? {
    let address = pigeonVar_list[0] as! String
    let mtu = pigeonVar_list[1] as! Int64

    return BmMtuChangedEvent(
      address: address,
      mtu: mtu
    )
  }
  func toList() -> [Any?] {
    return [
      address,
      mtu,
    ]
  }
  static func == (lhs: BmMtuChangedEvent, rhs: BmMtuChangedEvent) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.address, rhs.address) && MessagesPigeonInternal.deepEquals(lhs.mtu, rhs.mtu)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("BmMtuChangedEvent")
    MessagesPigeonInternal.deepHash(value: address, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: mtu, hasher: &hasher)
  }

  public var description: String {
    return "BmMtuChangedEvent(address: \(String(describing: address)), mtu: \(String(describing: mtu)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct BmDetachedFromEngineEvent: BmEvent {
  /// Carries no information — pigeon requires data classes to have a field.
  var unused: Bool? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> BmDetachedFromEngineEvent? {
    let unused: Bool? = nilOrValue(pigeonVar_list[0])

    return BmDetachedFromEngineEvent(
      unused: unused
    )
  }
  func toList() -> [Any?] {
    return [
      unused
    ]
  }
  static func == (lhs: BmDetachedFromEngineEvent, rhs: BmDetachedFromEngineEvent) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.unused, rhs.unused)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("BmDetachedFromEngineEvent")
    MessagesPigeonInternal.deepHash(value: unused, hasher: &hasher)
  }

  public var description: String {
    return "BmDetachedFromEngineEvent(unused: \(String(describing: unused)))"
  }
}

private class MessagesPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return BluetoothAdapterState(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return BluetoothConnectionState(rawValue: enumResultAsInt)
      }
      return nil
    case 131:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return BmWriteType(rawValue: enumResultAsInt)
      }
      return nil
    case 132:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return ConnectionPriority(rawValue: enumResultAsInt)
      }
      return nil
    case 133:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return BluetoothBondState(rawValue: enumResultAsInt)
      }
      return nil
    case 134:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return LogLevel(rawValue: enumResultAsInt)
      }
      return nil
    case 135:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return BluebirdErrorCode(rawValue: enumResultAsInt)
      }
      return nil
    case 136:
      return BmAttributeId.fromList(self.readValue() as! [Any?])
    case 137:
      return BmServiceRef.fromList(self.readValue() as! [Any?])
    case 138:
      return BmCharacteristicRef.fromList(self.readValue() as! [Any?])
    case 139:
      return BmDescriptorRef.fromList(self.readValue() as! [Any?])
    case 140:
      return BmMsdFilter.fromList(self.readValue() as! [Any?])
    case 141:
      return BmServiceDataFilter.fromList(self.readValue() as! [Any?])
    case 142:
      return BmScanSettings.fromList(self.readValue() as! [Any?])
    case 143:
      return BmScanAdvertisement.fromList(self.readValue() as! [Any?])
    case 144:
      return BmBluetoothDevice.fromList(self.readValue() as! [Any?])
    case 145:
      return BmBluetoothService.fromList(self.readValue() as! [Any?])
    case 146:
      return BmBluetoothCharacteristic.fromList(self.readValue() as! [Any?])
    case 147:
      return BmBluetoothDescriptor.fromList(self.readValue() as! [Any?])
    case 148:
      return BmCharacteristicProperties.fromList(self.readValue() as! [Any?])
    case 149:
      return BmPhySupport.fromList(self.readValue() as! [Any?])
    case 150:
      return BmAdapterStateEvent.fromList(self.readValue() as! [Any?])
    case 151:
      return BmScanAdvertisementEvent.fromList(self.readValue() as! [Any?])
    case 152:
      return BmScanFailedEvent.fromList(self.readValue() as! [Any?])
    case 153:
      return BmConnectionStateEvent.fromList(self.readValue() as! [Any?])
    case 154:
      return BmCharacteristicNotificationEvent.fromList(self.readValue() as! [Any?])
    case 155:
      return BmBondStateEvent.fromList(self.readValue() as! [Any?])
    case 156:
      return BmNameChangedEvent.fromList(self.readValue() as! [Any?])
    case 157:
      return BmServicesResetEvent.fromList(self.readValue() as! [Any?])
    case 158:
      return BmMtuChangedEvent.fromList(self.readValue() as! [Any?])
    case 159:
      return BmDetachedFromEngineEvent.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class MessagesPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? BluetoothAdapterState {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? BluetoothConnectionState {
      super.writeByte(130)
      super.writeValue(value.rawValue)
    } else if let value = value as? BmWriteType {
      super.writeByte(131)
      super.writeValue(value.rawValue)
    } else if let value = value as? ConnectionPriority {
      super.writeByte(132)
      super.writeValue(value.rawValue)
    } else if let value = value as? BluetoothBondState {
      super.writeByte(133)
      super.writeValue(value.rawValue)
    } else if let value = value as? LogLevel {
      super.writeByte(134)
      super.writeValue(value.rawValue)
    } else if let value = value as? BluebirdErrorCode {
      super.writeByte(135)
      super.writeValue(value.rawValue)
    } else if let value = value as? BmAttributeId {
      super.writeByte(136)
      super.writeValue(value.toList())
    } else if let value = value as? BmServiceRef {
      super.writeByte(137)
      super.writeValue(value.toList())
    } else if let value = value as? BmCharacteristicRef {
      super.writeByte(138)
      super.writeValue(value.toList())
    } else if let value = value as? BmDescriptorRef {
      super.writeByte(139)
      super.writeValue(value.toList())
    } else if let value = value as? BmMsdFilter {
      super.writeByte(140)
      super.writeValue(value.toList())
    } else if let value = value as? BmServiceDataFilter {
      super.writeByte(141)
      super.writeValue(value.toList())
    } else if let value = value as? BmScanSettings {
      super.writeByte(142)
      super.writeValue(value.toList())
    } else if let value = value as? BmScanAdvertisement {
      super.writeByte(143)
      super.writeValue(value.toList())
    } else if let value = value as? BmBluetoothDevice {
      super.writeByte(144)
      super.writeValue(value.toList())
    } else if let value = value as? BmBluetoothService {
      super.writeByte(145)
      super.writeValue(value.toList())
    } else if let value = value as? BmBluetoothCharacteristic {
      super.writeByte(146)
      super.writeValue(value.toList())
    } else if let value = value as? BmBluetoothDescriptor {
      super.writeByte(147)
      super.writeValue(value.toList())
    } else if let value = value as? BmCharacteristicProperties {
      super.writeByte(148)
      super.writeValue(value.toList())
    } else if let value = value as? BmPhySupport {
      super.writeByte(149)
      super.writeValue(value.toList())
    } else if let value = value as? BmAdapterStateEvent {
      super.writeByte(150)
      super.writeValue(value.toList())
    } else if let value = value as? BmScanAdvertisementEvent {
      super.writeByte(151)
      super.writeValue(value.toList())
    } else if let value = value as? BmScanFailedEvent {
      super.writeByte(152)
      super.writeValue(value.toList())
    } else if let value = value as? BmConnectionStateEvent {
      super.writeByte(153)
      super.writeValue(value.toList())
    } else if let value = value as? BmCharacteristicNotificationEvent {
      super.writeByte(154)
      super.writeValue(value.toList())
    } else if let value = value as? BmBondStateEvent {
      super.writeByte(155)
      super.writeValue(value.toList())
    } else if let value = value as? BmNameChangedEvent {
      super.writeByte(156)
      super.writeValue(value.toList())
    } else if let value = value as? BmServicesResetEvent {
      super.writeByte(157)
      super.writeValue(value.toList())
    } else if let value = value as? BmMtuChangedEvent {
      super.writeByte(158)
      super.writeValue(value.toList())
    } else if let value = value as? BmDetachedFromEngineEvent {
      super.writeByte(159)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class MessagesPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return MessagesPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return MessagesPigeonCodecWriter(data: data)
  }
}

class MessagesPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = MessagesPigeonCodec(readerWriter: MessagesPigeonCodecReaderWriter())
}

var messagesPigeonMethodCodec = FlutterStandardMethodCodec(readerWriter: MessagesPigeonCodecReaderWriter());



private class PigeonStreamHandler<ReturnType>: NSObject, FlutterStreamHandler {
  private let wrapper: PigeonEventChannelWrapper<ReturnType>
  private var pigeonSink: PigeonEventSink<ReturnType>? = nil

  init(wrapper: PigeonEventChannelWrapper<ReturnType>) {
    self.wrapper = wrapper
  }

  func onListen(withArguments arguments: Any?, eventSink events: @escaping FlutterEventSink)
    -> FlutterError?
  {
    pigeonSink = PigeonEventSink<ReturnType>(events)
    wrapper.onListen(withArguments: arguments, sink: pigeonSink!)
    return nil
  }

  func onCancel(withArguments arguments: Any?) -> FlutterError? {
    pigeonSink = nil
    wrapper.onCancel(withArguments: arguments)
    return nil
  }
}

class PigeonEventChannelWrapper<ReturnType> {
  func onListen(withArguments arguments: Any?, sink: PigeonEventSink<ReturnType>) {}
  func onCancel(withArguments arguments: Any?) {}
}

class PigeonEventSink<ReturnType> {
  private let sink: FlutterEventSink

  init(_ sink: @escaping FlutterEventSink) {
    self.sink = sink
  }

  func success(_ value: ReturnType) {
    sink(value)
  }

  func error(code: String, message: String?, details: Any?) {
    sink(FlutterError(code: code, message: message, details: details))
  }

  func endOfStream() {
    sink(FlutterEndOfEventStream)
  }

}

class NativeEventsStreamHandler: PigeonEventChannelWrapper<BmEvent> {
  static func register(with messenger: FlutterBinaryMessenger,
                      instanceName: String = "",
                      streamHandler: NativeEventsStreamHandler) {
    var channelName = "dev.flutter.pigeon.bluebird.BluebirdEventChannelApi.nativeEvents"
    if !instanceName.isEmpty {
      channelName += ".\(instanceName)"
    }
    let internalStreamHandler = PigeonStreamHandler<BmEvent>(wrapper: streamHandler)
    let channel = FlutterEventChannel(name: channelName, binaryMessenger: messenger, codec: messagesPigeonMethodCodec)
    channel.setStreamHandler(internalStreamHandler)
  }
}
      
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol BluebirdHostApi {
  /// Hot-restart handshake: disconnects and closes everything, returns the
  /// number of devices still closing.
  func flutterRestart() throws -> Int64
  func connectedCount() throws -> Int64
  func setLogLevel(level: LogLevel) throws
  func setOptions(showPowerAlert: Bool, restoreState: Bool) throws
  func isSupported() throws -> Bool
  /// @async: may need to request runtime permissions before answering.
  func getAdapterName(completion: @escaping (Result<String, Error>) -> Void)
  func getAdapterState() throws -> BluetoothAdapterState
  /// Android: shows the enable-bluetooth dialog; completes with user consent.
  func turnOn(completion: @escaping (Result<Bool, Error>) -> Void)
  func turnOff(completion: @escaping (Result<Bool, Error>) -> Void)
  func startScan(settings: BmScanSettings, completion: @escaping (Result<Void, Error>) -> Void)
  func stopScan() throws
  func getSystemDevices(withServices: [String], completion: @escaping (Result<[BmBluetoothDevice], Error>) -> Void)
  func getBondedDevices(completion: @escaping (Result<[BmBluetoothDevice], Error>) -> Void)
  func connect(address: String, completion: @escaping (Result<Void, Error>) -> Void)
  func disconnect(address: String, completion: @escaping (Result<Void, Error>) -> Void)
  func discoverServices(address: String, completion: @escaping (Result<[BmBluetoothService], Error>) -> Void)
  func readCharacteristic(address: String, characteristic: BmCharacteristicRef, completion: @escaping (Result<FlutterStandardTypedData, Error>) -> Void)
  func writeCharacteristic(address: String, characteristic: BmCharacteristicRef, writeType: BmWriteType, allowLongWrite: Bool, value: FlutterStandardTypedData, completion: @escaping (Result<Void, Error>) -> Void)
  func readDescriptor(address: String, descriptor: BmDescriptorRef, completion: @escaping (Result<FlutterStandardTypedData, Error>) -> Void)
  func writeDescriptor(address: String, descriptor: BmDescriptorRef, value: FlutterStandardTypedData, completion: @escaping (Result<Void, Error>) -> Void)
  /// Completes after the CCCD write confirms (or immediately if no CCCD).
  func setNotifyValue(address: String, characteristic: BmCharacteristicRef, enable: Bool, completion: @escaping (Result<Bool, Error>) -> Void)
  func requestMtu(address: String, mtu: Int64, completion: @escaping (Result<Int64, Error>) -> Void)
  func readRssi(address: String, completion: @escaping (Result<Int64, Error>) -> Void)
  func requestConnectionPriority(address: String, connectionPriority: ConnectionPriority) throws
  func getPhySupport() throws -> BmPhySupport
  func setPreferredPhy(address: String, txPhy: Int64, rxPhy: Int64, phyOptions: Int64, completion: @escaping (Result<Void, Error>) -> Void)
  func getBondState(address: String) throws -> BluetoothBondState
  func createBond(address: String, pin: FlutterStandardTypedData?, completion: @escaping (Result<Bool, Error>) -> Void)
  func removeBond(address: String, completion: @escaping (Result<Bool, Error>) -> Void)
  func clearGattCache(address: String, completion: @escaping (Result<Void, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class BluebirdHostApiSetup {
  static var codec: FlutterStandardMessageCodec { MessagesPigeonCodec.shared }
  /// Sets up an instance of `BluebirdHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: BluebirdHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Hot-restart handshake: disconnects and closes everything, returns the
    /// number of devices still closing.
    let flutterRestartChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.bluebird.BluebirdHostApi.flutterRestart\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      flutterRestartChannel.setMessageHandler { _, reply in
        do {
          let result = try api.flutterRestart()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      flutterRestartChannel.setMessageHandler(nil)
    }
    let connectedCountChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.bluebird.BluebirdHostApi.connectedCount\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      connectedCountChannel.setMessageHandler { _, reply in
        do {
          let result = try api.connectedCount()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      connectedCountChannel.setMessageHandler(nil)
    }
    let setLogLevelChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.bluebird.BluebirdHostApi.setLogLevel\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setLogLevelChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let levelArg = args[0] as! LogLevel
        do {
          try api.setLogLevel(level: levelArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setLogLevelChannel.setMessageHandler(nil)
    }
    let setOptionsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.bluebird.BluebirdHostApi.setOptions\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setOptionsChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let showPowerAlertArg = args[0] as! Bool
        let restoreStateArg = args[1] as! Bool
        do {
          try api.setOptions(showPowerAlert: showPowerAlertArg, restoreState: restoreStateArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setOptionsChannel.setMessageHandler(nil)
    }
    let isSupportedChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.bluebird.BluebirdHostApi.isSupported\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      isSupportedChannel.setMessageHandler { _, reply in
        do {
          let result = try api.isSupported()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      isSupportedChannel.setMessageHandler(nil)
    }
    /// @async: may need to request runtime permissions before answering.
    let getAdapterNameChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.bluebird.BluebirdHostApi.getAdapterName\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getAdapterNameChannel.setMessageHandler { _, reply in
        api.getAdapterName { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getAdapterNameChannel.setMessageHandler(nil)
    }
    let getAdapterStateChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.bluebird.BluebirdHostApi.getAdapterState\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getAdapterStateChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getAdapterState()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getAdapterStateChannel.setMessageHandler(nil)
    }
    /// Android: shows the enable-bluetooth dialog; completes with user consent.
    let turnOnChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.bluebird.BluebirdHostApi.turnOn\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      turnOnChannel.setMessageHandler { _, reply in
        api.turnOn { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      turnOnChannel.setMessageHandler(nil)
    }
    let turnOffChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.bluebird.BluebirdHostApi.turnOff\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      turnOffChannel.setMessageHandler { _, reply in
        api.turnOff { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      turnOffChannel.setMessageHandler(nil)
    }
    let startScanChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.bluebird.BluebirdHostApi.startScan\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startScanChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let settingsArg = args[0] as! BmScanSettings
        api.startScan(settings: settingsArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      startScanChannel.setMessageHandler(nil)
    }
    let stopScanChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.bluebird.BluebirdHostApi.stopScan\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      stopScanChannel.setMessageHandler { _, reply in
        do {
          try api.stopScan()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      stopScanChannel.setMessageHandler(nil)
    }
    let getSystemDevicesChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.bluebird.BluebirdHostApi.getSystemDevices\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getSystemDevicesChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let withServicesArg = args[0] as! [String]
        api.getSystemDevices(withServices: withServicesArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getSystemDevicesChannel.setMessageHandler(nil)
    }
    let getBondedDevicesChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.bluebird.BluebirdHostApi.getBondedDevices\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getBondedDevicesChannel.setMessageHandler { _, reply in
        api.getBondedDevices { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getBondedDevicesChannel.setMessageHandler(nil)
    }
    let connectChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.bluebird.BluebirdHostApi.connect\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      connectChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let addressArg = args[0] as! String
        api.connect(address: addressArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      connectChannel.setMessageHandler(nil)
    }
    let disconnectChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.bluebird.BluebirdHostApi.disconnect\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      disconnectChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let addressArg = args[0] as! String
        api.disconnect(address: addressArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      disconnectChannel.setMessageHandler(nil)
    }
    let discoverServicesChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.bluebird.BluebirdHostApi.discoverServices\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      discoverServicesChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let addressArg = args[0] as! String
        api.discoverServices(address: addressArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      discoverServicesChannel.setMessageHandler(nil)
    }
    let readCharacteristicChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.bluebird.BluebirdHostApi.readCharacteristic\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      readCharacteristicChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let addressArg = args[0] as! String
        let characteristicArg = args[1] as! BmCharacteristicRef
        api.readCharacteristic(address: addressArg, characteristic: characteristicArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      readCharacteristicChannel.setMessageHandler(nil)
    }
    let writeCharacteristicChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.bluebird.BluebirdHostApi.writeCharacteristic\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      writeCharacteristicChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let addressArg = args[0] as! String
        let characteristicArg = args[1] as! BmCharacteristicRef
        let writeTypeArg = args[2] as! BmWriteType
        let allowLongWriteArg = args[3] as! Bool
        let valueArg = args[4] as! FlutterStandardTypedData
        api.writeCharacteristic(address: addressArg, characteristic: characteristicArg, writeType: writeTypeArg, allowLongWrite: allowLongWriteArg, value: valueArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      writeCharacteristicChannel.setMessageHandler(nil)
    }
    let readDescriptorChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.bluebird.BluebirdHostApi.readDescriptor\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      readDescriptorChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let addressArg = args[0] as! String
        let descriptorArg = args[1] as! BmDescriptorRef
        api.readDescriptor(address: addressArg, descriptor: descriptorArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      readDescriptorChannel.setMessageHandler(nil)
    }
    let writeDescriptorChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.bluebird.BluebirdHostApi.writeDescriptor\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      writeDescriptorChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let addressArg = args[0] as! String
        let descriptorArg = args[1] as! BmDescriptorRef
        let valueArg = args[2] as! FlutterStandardTypedData
        api.writeDescriptor(address: addressArg, descriptor: descriptorArg, value: valueArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      writeDescriptorChannel.setMessageHandler(nil)
    }
    /// Completes after the CCCD write confirms (or immediately if no CCCD).
    let setNotifyValueChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.bluebird.BluebirdHostApi.setNotifyValue\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setNotifyValueChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let addressArg = args[0] as! String
        let characteristicArg = args[1] as! BmCharacteristicRef
        let enableArg = args[2] as! Bool
        api.setNotifyValue(address: addressArg, characteristic: characteristicArg, enable: enableArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      setNotifyValueChannel.setMessageHandler(nil)
    }
    let requestMtuChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.bluebird.BluebirdHostApi.requestMtu\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      requestMtuChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let addressArg = args[0] as! String
        let mtuArg = args[1] as! Int64
        api.requestMtu(address: addressArg, mtu: mtuArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      requestMtuChannel.setMessageHandler(nil)
    }
    let readRssiChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.bluebird.BluebirdHostApi.readRssi\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      readRssiChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let addressArg = args[0] as! String
        api.readRssi(address: addressArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      readRssiChannel.setMessageHandler(nil)
    }
    let requestConnectionPriorityChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.bluebird.BluebirdHostApi.requestConnectionPriority\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      requestConnectionPriorityChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let addressArg = args[0] as! String
        let connectionPriorityArg = args[1] as! ConnectionPriority
        do {
          try api.requestConnectionPriority(address: addressArg, connectionPriority: connectionPriorityArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      requestConnectionPriorityChannel.setMessageHandler(nil)
    }
    let getPhySupportChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.bluebird.BluebirdHostApi.getPhySupport\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getPhySupportChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getPhySupport()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getPhySupportChannel.setMessageHandler(nil)
    }
    let setPreferredPhyChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.bluebird.BluebirdHostApi.setPreferredPhy\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setPreferredPhyChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let addressArg = args[0] as! String
        let txPhyArg = args[1] as! Int64
        let rxPhyArg = args[2] as! Int64
        let phyOptionsArg = args[3] as! Int64
        api.setPreferredPhy(address: addressArg, txPhy: txPhyArg, rxPhy: rxPhyArg, phyOptions: phyOptionsArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      setPreferredPhyChannel.setMessageHandler(nil)
    }
    let getBondStateChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.bluebird.BluebirdHostApi.getBondState\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getBondStateChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let addressArg = args[0] as! String
        do {
          let result = try api.getBondState(address: addressArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getBondStateChannel.setMessageHandler(nil)
    }
    let createBondChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.bluebird.BluebirdHostApi.createBond\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      createBondChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let addressArg = args[0] as! String
        let pinArg: FlutterStandardTypedData? = nilOrValue(args[1])
        api.createBond(address: addressArg, pin: pinArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      createBondChannel.setMessageHandler(nil)
    }
    let removeBondChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.bluebird.BluebirdHostApi.removeBond\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      removeBondChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let addressArg = args[0] as! String
        api.removeBond(address: addressArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      removeBondChannel.setMessageHandler(nil)
    }
    let clearGattCacheChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.bluebird.BluebirdHostApi.clearGattCache\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      clearGattCacheChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let addressArg = args[0] as! String
        api.clearGattCache(address: addressArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      clearGattCacheChannel.setMessageHandler(nil)
    }
  }
}
