// Autogenerated from Pigeon (v27.1.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(List<Object?>? replyList, String channelName, {required bool isNullValid}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(code: replyList[0]! as String, message: replyList[1] as String?, details: replyList[2]);
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length && a.indexed.every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}

enum BluetoothAdapterState { unknown, unavailable, unauthorized, turningOn, on, turningOff, off }

enum BluetoothConnectionState { disconnected, connected, connecting, disconnecting }

enum BmWriteType { withResponse, withoutResponse }

enum ConnectionPriority { balanced, high, lowPower }

enum BluetoothBondState { none, bonding, bonded }

enum LogLevel { none, error, warning, info, debug, verbose }

/// Single source of truth for error codes, shared by every platform.
///
/// Errors cross the channel as `PlatformException.code` *strings* (pigeon
/// cannot type that field), so the wire form of each code is, by convention,
/// the snake_case of its name here (e.g. [BluebirdErrorCode.deviceDisconnected]
/// crosses as `"device_disconnected"`). Each language has a small `wire`
/// helper implementing that convention; never hand-write a code string.
enum BluebirdErrorCode {
  success,
  timeout,
  platform,
  serviceNotFound,
  characteristicNotFound,
  userRejected,
  removeBondFailed,

  /// An Android-side GATT stack/link failure — e.g. a `BluetoothGatt` call
  /// returned false/null, an HCI disconnect, or `GATT_FAILURE`. Not a peer
  /// response; see [attError]. The darwin analogue is [darwinError].
  androidError,

  /// A darwin-side (CoreBluetooth) stack/link failure — a non-`CBATTErrorDomain`
  /// `NSError` (e.g. connection lost). Not a peer response; see [attError]. The
  /// android analogue is [androidError].
  darwinError,

  /// A Bluetooth spec-level error: the peer answered a request with an ATT
  /// Error Response. Raised uniformly by every platform, with the raw one-octet
  /// code (an `int`, spanning the core ATT / application / GATT common ranges)
  /// riding along as the error details. Platform/link failures that are *not*
  /// peer responses stay [androidError] / [darwinError].
  attError,
  deviceDisconnected,
  adapterOff,
  notConnected,
  invalidIdentifier,
  bondFailed,
  userCanceled,
  unsupported,
  operationInProgress,
  permissionDenied,
  invalidArgument,
}

/// The universal uuid:instance pair identifying one attribute.
class BmAttributeId {
  BmAttributeId({required this.uuid, required this.instance});

  String uuid;

  /// Platform-opaque token disambiguating duplicate uuids.
  int instance;

  List<Object?> _toList() {
    return <Object?>[uuid, instance];
  }

  Object encode() {
    return _toList();
  }

  static BmAttributeId decode(Object result) {
    result as List<Object?>;
    return BmAttributeId(uuid: result[0]! as String, instance: result[1]! as int);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! BmAttributeId || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(uuid, other.uuid) && _deepEquals(instance, other.instance);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'BmAttributeId(uuid: $uuid, instance: $instance)';
  }
}

class BmServiceRef {
  BmServiceRef({required this.service, this.parentService});

  BmAttributeId service;

  /// Set when this is a secondary (included) service.
  BmAttributeId? parentService;

  List<Object?> _toList() {
    return <Object?>[service, parentService];
  }

  Object encode() {
    return _toList();
  }

  static BmServiceRef decode(Object result) {
    result as List<Object?>;
    return BmServiceRef(service: result[0]! as BmAttributeId, parentService: result[1] as BmAttributeId?);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! BmServiceRef || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(service, other.service) && _deepEquals(parentService, other.parentService);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'BmServiceRef(service: $service, parentService: $parentService)';
  }
}

class BmCharacteristicRef {
  BmCharacteristicRef({required this.service, required this.characteristic});

  BmServiceRef service;

  BmAttributeId characteristic;

  List<Object?> _toList() {
    return <Object?>[service, characteristic];
  }

  Object encode() {
    return _toList();
  }

  static BmCharacteristicRef decode(Object result) {
    result as List<Object?>;
    return BmCharacteristicRef(service: result[0]! as BmServiceRef, characteristic: result[1]! as BmAttributeId);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! BmCharacteristicRef || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(service, other.service) && _deepEquals(characteristic, other.characteristic);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'BmCharacteristicRef(service: $service, characteristic: $characteristic)';
  }
}

class BmDescriptorRef {
  BmDescriptorRef({required this.characteristic, required this.id});

  BmCharacteristicRef characteristic;

  /// Descriptors are uuid-unique within a characteristic, so [id]'s instance is
  /// always 0; the [BmAttributeId] keeps descriptors uniform with services and
  /// characteristics.
  BmAttributeId id;

  List<Object?> _toList() {
    return <Object?>[characteristic, id];
  }

  Object encode() {
    return _toList();
  }

  static BmDescriptorRef decode(Object result) {
    result as List<Object?>;
    return BmDescriptorRef(characteristic: result[0]! as BmCharacteristicRef, id: result[1]! as BmAttributeId);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! BmDescriptorRef || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(characteristic, other.characteristic) && _deepEquals(id, other.id);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'BmDescriptorRef(characteristic: $characteristic, id: $id)';
  }
}

class BmMsdFilter {
  BmMsdFilter({required this.manufacturerId, this.data, this.mask});

  int manufacturerId;

  Uint8List? data;

  Uint8List? mask;

  List<Object?> _toList() {
    return <Object?>[manufacturerId, data, mask];
  }

  Object encode() {
    return _toList();
  }

  static BmMsdFilter decode(Object result) {
    result as List<Object?>;
    return BmMsdFilter(manufacturerId: result[0]! as int, data: result[1] as Uint8List?, mask: result[2] as Uint8List?);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! BmMsdFilter || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(manufacturerId, other.manufacturerId) &&
        _deepEquals(data, other.data) &&
        _deepEquals(mask, other.mask);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'BmMsdFilter(manufacturerId: $manufacturerId, data: $data, mask: $mask)';
  }
}

class BmServiceDataFilter {
  BmServiceDataFilter({required this.service, required this.data, this.mask});

  String service;

  Uint8List data;

  Uint8List? mask;

  List<Object?> _toList() {
    return <Object?>[service, data, mask];
  }

  Object encode() {
    return _toList();
  }

  static BmServiceDataFilter decode(Object result) {
    result as List<Object?>;
    return BmServiceDataFilter(
      service: result[0]! as String,
      data: result[1]! as Uint8List,
      mask: result[2] as Uint8List?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! BmServiceDataFilter || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(service, other.service) && _deepEquals(data, other.data) && _deepEquals(mask, other.mask);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'BmServiceDataFilter(service: $service, data: $data, mask: $mask)';
  }
}

class BmScanSettings {
  BmScanSettings({
    required this.withServices,
    required this.withRemoteIds,
    required this.withNames,
    required this.withKeywords,
    required this.withMsd,
    required this.withServiceData,
    required this.continuousUpdates,
    required this.continuousDivisor,
    required this.androidLegacy,
    required this.androidScanMode,
    required this.androidUsesFineLocation,
    required this.webOptionalServices,
  });

  List<String> withServices;

  List<String> withRemoteIds;

  List<String> withNames;

  List<String> withKeywords;

  List<BmMsdFilter> withMsd;

  List<BmServiceDataFilter> withServiceData;

  bool continuousUpdates;

  int continuousDivisor;

  bool androidLegacy;

  int androidScanMode;

  bool androidUsesFineLocation;

  List<String> webOptionalServices;

  List<Object?> _toList() {
    return <Object?>[
      withServices,
      withRemoteIds,
      withNames,
      withKeywords,
      withMsd,
      withServiceData,
      continuousUpdates,
      continuousDivisor,
      androidLegacy,
      androidScanMode,
      androidUsesFineLocation,
      webOptionalServices,
    ];
  }

  Object encode() {
    return _toList();
  }

  static BmScanSettings decode(Object result) {
    result as List<Object?>;
    return BmScanSettings(
      withServices: (result[0]! as List<Object?>).cast<String>(),
      withRemoteIds: (result[1]! as List<Object?>).cast<String>(),
      withNames: (result[2]! as List<Object?>).cast<String>(),
      withKeywords: (result[3]! as List<Object?>).cast<String>(),
      withMsd: (result[4]! as List<Object?>).cast<BmMsdFilter>(),
      withServiceData: (result[5]! as List<Object?>).cast<BmServiceDataFilter>(),
      continuousUpdates: result[6]! as bool,
      continuousDivisor: result[7]! as int,
      androidLegacy: result[8]! as bool,
      androidScanMode: result[9]! as int,
      androidUsesFineLocation: result[10]! as bool,
      webOptionalServices: (result[11]! as List<Object?>).cast<String>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! BmScanSettings || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(withServices, other.withServices) &&
        _deepEquals(withRemoteIds, other.withRemoteIds) &&
        _deepEquals(withNames, other.withNames) &&
        _deepEquals(withKeywords, other.withKeywords) &&
        _deepEquals(withMsd, other.withMsd) &&
        _deepEquals(withServiceData, other.withServiceData) &&
        _deepEquals(continuousUpdates, other.continuousUpdates) &&
        _deepEquals(continuousDivisor, other.continuousDivisor) &&
        _deepEquals(androidLegacy, other.androidLegacy) &&
        _deepEquals(androidScanMode, other.androidScanMode) &&
        _deepEquals(androidUsesFineLocation, other.androidUsesFineLocation) &&
        _deepEquals(webOptionalServices, other.webOptionalServices);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'BmScanSettings(withServices: $withServices, withRemoteIds: $withRemoteIds, withNames: $withNames, withKeywords: $withKeywords, withMsd: $withMsd, withServiceData: $withServiceData, continuousUpdates: $continuousUpdates, continuousDivisor: $continuousDivisor, androidLegacy: $androidLegacy, androidScanMode: $androidScanMode, androidUsesFineLocation: $androidUsesFineLocation, webOptionalServices: $webOptionalServices)';
  }
}

class BmScanAdvertisement {
  BmScanAdvertisement({
    required this.address,
    this.platformName,
    this.advName,
    required this.connectable,
    this.txPowerLevel,
    this.appearance,
    required this.manufacturerData,
    required this.serviceData,
    required this.serviceUuids,
    required this.rssi,
  });

  String address;

  String? platformName;

  String? advName;

  bool connectable;

  int? txPowerLevel;

  /// Not supported on iOS / macOS.
  int? appearance;

  Map<int, Uint8List> manufacturerData;

  Map<String, Uint8List> serviceData;

  List<String> serviceUuids;

  int rssi;

  List<Object?> _toList() {
    return <Object?>[
      address,
      platformName,
      advName,
      connectable,
      txPowerLevel,
      appearance,
      manufacturerData,
      serviceData,
      serviceUuids,
      rssi,
    ];
  }

  Object encode() {
    return _toList();
  }

  static BmScanAdvertisement decode(Object result) {
    result as List<Object?>;
    return BmScanAdvertisement(
      address: result[0]! as String,
      platformName: result[1] as String?,
      advName: result[2] as String?,
      connectable: result[3]! as bool,
      txPowerLevel: result[4] as int?,
      appearance: result[5] as int?,
      manufacturerData: (result[6]! as Map<Object?, Object?>).cast<int, Uint8List>(),
      serviceData: (result[7]! as Map<Object?, Object?>).cast<String, Uint8List>(),
      serviceUuids: (result[8]! as List<Object?>).cast<String>(),
      rssi: result[9]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! BmScanAdvertisement || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(address, other.address) &&
        _deepEquals(platformName, other.platformName) &&
        _deepEquals(advName, other.advName) &&
        _deepEquals(connectable, other.connectable) &&
        _deepEquals(txPowerLevel, other.txPowerLevel) &&
        _deepEquals(appearance, other.appearance) &&
        _deepEquals(manufacturerData, other.manufacturerData) &&
        _deepEquals(serviceData, other.serviceData) &&
        _deepEquals(serviceUuids, other.serviceUuids) &&
        _deepEquals(rssi, other.rssi);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'BmScanAdvertisement(address: $address, platformName: $platformName, advName: $advName, connectable: $connectable, txPowerLevel: $txPowerLevel, appearance: $appearance, manufacturerData: $manufacturerData, serviceData: $serviceData, serviceUuids: $serviceUuids, rssi: $rssi)';
  }
}

class BmBluetoothDevice {
  BmBluetoothDevice({required this.address, this.platformName});

  String address;

  String? platformName;

  List<Object?> _toList() {
    return <Object?>[address, platformName];
  }

  Object encode() {
    return _toList();
  }

  static BmBluetoothDevice decode(Object result) {
    result as List<Object?>;
    return BmBluetoothDevice(address: result[0]! as String, platformName: result[1] as String?);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! BmBluetoothDevice || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(address, other.address) && _deepEquals(platformName, other.platformName);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'BmBluetoothDevice(address: $address, platformName: $platformName)';
  }
}

class BmBluetoothService {
  BmBluetoothService({
    required this.id,
    required this.isPrimary,
    required this.characteristics,
    required this.includedServices,
  });

  BmAttributeId id;

  bool isPrimary;

  List<BmBluetoothCharacteristic> characteristics;

  List<BmServiceRef> includedServices;

  List<Object?> _toList() {
    return <Object?>[id, isPrimary, characteristics, includedServices];
  }

  Object encode() {
    return _toList();
  }

  static BmBluetoothService decode(Object result) {
    result as List<Object?>;
    return BmBluetoothService(
      id: result[0]! as BmAttributeId,
      isPrimary: result[1]! as bool,
      characteristics: (result[2]! as List<Object?>).cast<BmBluetoothCharacteristic>(),
      includedServices: (result[3]! as List<Object?>).cast<BmServiceRef>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! BmBluetoothService || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(id, other.id) &&
        _deepEquals(isPrimary, other.isPrimary) &&
        _deepEquals(characteristics, other.characteristics) &&
        _deepEquals(includedServices, other.includedServices);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'BmBluetoothService(id: $id, isPrimary: $isPrimary, characteristics: $characteristics, includedServices: $includedServices)';
  }
}

class BmBluetoothCharacteristic {
  BmBluetoothCharacteristic({required this.id, required this.descriptors, required this.properties});

  BmAttributeId id;

  List<BmBluetoothDescriptor> descriptors;

  BmCharacteristicProperties properties;

  List<Object?> _toList() {
    return <Object?>[id, descriptors, properties];
  }

  Object encode() {
    return _toList();
  }

  static BmBluetoothCharacteristic decode(Object result) {
    result as List<Object?>;
    return BmBluetoothCharacteristic(
      id: result[0]! as BmAttributeId,
      descriptors: (result[1]! as List<Object?>).cast<BmBluetoothDescriptor>(),
      properties: result[2]! as BmCharacteristicProperties,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! BmBluetoothCharacteristic || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(id, other.id) &&
        _deepEquals(descriptors, other.descriptors) &&
        _deepEquals(properties, other.properties);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'BmBluetoothCharacteristic(id: $id, descriptors: $descriptors, properties: $properties)';
  }
}

class BmBluetoothDescriptor {
  BmBluetoothDescriptor({required this.id});

  BmAttributeId id;

  List<Object?> _toList() {
    return <Object?>[id];
  }

  Object encode() {
    return _toList();
  }

  static BmBluetoothDescriptor decode(Object result) {
    result as List<Object?>;
    return BmBluetoothDescriptor(id: result[0]! as BmAttributeId);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! BmBluetoothDescriptor || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(id, other.id);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'BmBluetoothDescriptor(id: $id)';
  }
}

class BmCharacteristicProperties {
  BmCharacteristicProperties({
    required this.broadcast,
    required this.read,
    required this.writeWithoutResponse,
    required this.write,
    required this.notify,
    required this.indicate,
    required this.authenticatedSignedWrites,
    required this.extendedProperties,
    required this.notifyEncryptionRequired,
    required this.indicateEncryptionRequired,
  });

  bool broadcast;

  bool read;

  bool writeWithoutResponse;

  bool write;

  bool notify;

  bool indicate;

  bool authenticatedSignedWrites;

  bool extendedProperties;

  bool notifyEncryptionRequired;

  bool indicateEncryptionRequired;

  List<Object?> _toList() {
    return <Object?>[
      broadcast,
      read,
      writeWithoutResponse,
      write,
      notify,
      indicate,
      authenticatedSignedWrites,
      extendedProperties,
      notifyEncryptionRequired,
      indicateEncryptionRequired,
    ];
  }

  Object encode() {
    return _toList();
  }

  static BmCharacteristicProperties decode(Object result) {
    result as List<Object?>;
    return BmCharacteristicProperties(
      broadcast: result[0]! as bool,
      read: result[1]! as bool,
      writeWithoutResponse: result[2]! as bool,
      write: result[3]! as bool,
      notify: result[4]! as bool,
      indicate: result[5]! as bool,
      authenticatedSignedWrites: result[6]! as bool,
      extendedProperties: result[7]! as bool,
      notifyEncryptionRequired: result[8]! as bool,
      indicateEncryptionRequired: result[9]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! BmCharacteristicProperties || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(broadcast, other.broadcast) &&
        _deepEquals(read, other.read) &&
        _deepEquals(writeWithoutResponse, other.writeWithoutResponse) &&
        _deepEquals(write, other.write) &&
        _deepEquals(notify, other.notify) &&
        _deepEquals(indicate, other.indicate) &&
        _deepEquals(authenticatedSignedWrites, other.authenticatedSignedWrites) &&
        _deepEquals(extendedProperties, other.extendedProperties) &&
        _deepEquals(notifyEncryptionRequired, other.notifyEncryptionRequired) &&
        _deepEquals(indicateEncryptionRequired, other.indicateEncryptionRequired);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'BmCharacteristicProperties(broadcast: $broadcast, read: $read, writeWithoutResponse: $writeWithoutResponse, write: $write, notify: $notify, indicate: $indicate, authenticatedSignedWrites: $authenticatedSignedWrites, extendedProperties: $extendedProperties, notifyEncryptionRequired: $notifyEncryptionRequired, indicateEncryptionRequired: $indicateEncryptionRequired)';
  }
}

class BmPhySupport {
  BmPhySupport({required this.le2M, required this.leCoded});

  /// High speed (PHY 2M)
  bool le2M;

  /// Long range (PHY codec)
  bool leCoded;

  List<Object?> _toList() {
    return <Object?>[le2M, leCoded];
  }

  Object encode() {
    return _toList();
  }

  static BmPhySupport decode(Object result) {
    result as List<Object?>;
    return BmPhySupport(le2M: result[0]! as bool, leCoded: result[1]! as bool);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! BmPhySupport || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(le2M, other.le2M) && _deepEquals(leCoded, other.leCoded);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'BmPhySupport(le2M: $le2M, leCoded: $leCoded)';
  }
}

sealed class BmEvent {}

class BmAdapterStateEvent extends BmEvent {
  BmAdapterStateEvent({required this.adapterState});

  BluetoothAdapterState adapterState;

  List<Object?> _toList() {
    return <Object?>[adapterState];
  }

  Object encode() {
    return _toList();
  }

  static BmAdapterStateEvent decode(Object result) {
    result as List<Object?>;
    return BmAdapterStateEvent(adapterState: result[0]! as BluetoothAdapterState);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! BmAdapterStateEvent || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(adapterState, other.adapterState);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'BmAdapterStateEvent(adapterState: $adapterState)';
  }
}

class BmScanAdvertisementEvent extends BmEvent {
  BmScanAdvertisementEvent({required this.advertisement});

  BmScanAdvertisement advertisement;

  List<Object?> _toList() {
    return <Object?>[advertisement];
  }

  Object encode() {
    return _toList();
  }

  static BmScanAdvertisementEvent decode(Object result) {
    result as List<Object?>;
    return BmScanAdvertisementEvent(advertisement: result[0]! as BmScanAdvertisement);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! BmScanAdvertisementEvent || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(advertisement, other.advertisement);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'BmScanAdvertisementEvent(advertisement: $advertisement)';
  }
}

class BmScanFailedEvent extends BmEvent {
  BmScanFailedEvent({required this.errorCode, required this.errorString});

  int errorCode;

  String errorString;

  List<Object?> _toList() {
    return <Object?>[errorCode, errorString];
  }

  Object encode() {
    return _toList();
  }

  static BmScanFailedEvent decode(Object result) {
    result as List<Object?>;
    return BmScanFailedEvent(errorCode: result[0]! as int, errorString: result[1]! as String);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! BmScanFailedEvent || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(errorCode, other.errorCode) && _deepEquals(errorString, other.errorString);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'BmScanFailedEvent(errorCode: $errorCode, errorString: $errorString)';
  }
}

class BmConnectionStateEvent extends BmEvent {
  BmConnectionStateEvent({
    required this.address,
    required this.connectionState,
    this.disconnectReasonCode,
    this.disconnectReasonString,
  });

  String address;

  BluetoothConnectionState connectionState;

  int? disconnectReasonCode;

  String? disconnectReasonString;

  List<Object?> _toList() {
    return <Object?>[address, connectionState, disconnectReasonCode, disconnectReasonString];
  }

  Object encode() {
    return _toList();
  }

  static BmConnectionStateEvent decode(Object result) {
    result as List<Object?>;
    return BmConnectionStateEvent(
      address: result[0]! as String,
      connectionState: result[1]! as BluetoothConnectionState,
      disconnectReasonCode: result[2] as int?,
      disconnectReasonString: result[3] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! BmConnectionStateEvent || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(address, other.address) &&
        _deepEquals(connectionState, other.connectionState) &&
        _deepEquals(disconnectReasonCode, other.disconnectReasonCode) &&
        _deepEquals(disconnectReasonString, other.disconnectReasonString);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'BmConnectionStateEvent(address: $address, connectionState: $connectionState, disconnectReasonCode: $disconnectReasonCode, disconnectReasonString: $disconnectReasonString)';
  }
}

/// A characteristic value received via notify/indicate. Read responses are
/// returned from [BluebirdHostApi.readCharacteristic] instead.
class BmCharacteristicNotificationEvent extends BmEvent {
  BmCharacteristicNotificationEvent({required this.address, required this.characteristic, required this.value});

  String address;

  BmCharacteristicRef characteristic;

  Uint8List value;

  List<Object?> _toList() {
    return <Object?>[address, characteristic, value];
  }

  Object encode() {
    return _toList();
  }

  static BmCharacteristicNotificationEvent decode(Object result) {
    result as List<Object?>;
    return BmCharacteristicNotificationEvent(
      address: result[0]! as String,
      characteristic: result[1]! as BmCharacteristicRef,
      value: result[2]! as Uint8List,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! BmCharacteristicNotificationEvent || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(address, other.address) &&
        _deepEquals(characteristic, other.characteristic) &&
        _deepEquals(value, other.value);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'BmCharacteristicNotificationEvent(address: $address, characteristic: $characteristic, value: $value)';
  }
}

class BmBondStateEvent extends BmEvent {
  BmBondStateEvent({required this.address, required this.bondState, this.prevState});

  String address;

  BluetoothBondState bondState;

  BluetoothBondState? prevState;

  List<Object?> _toList() {
    return <Object?>[address, bondState, prevState];
  }

  Object encode() {
    return _toList();
  }

  static BmBondStateEvent decode(Object result) {
    result as List<Object?>;
    return BmBondStateEvent(
      address: result[0]! as String,
      bondState: result[1]! as BluetoothBondState,
      prevState: result[2] as BluetoothBondState?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! BmBondStateEvent || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(address, other.address) &&
        _deepEquals(bondState, other.bondState) &&
        _deepEquals(prevState, other.prevState);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'BmBondStateEvent(address: $address, bondState: $bondState, prevState: $prevState)';
  }
}

class BmNameChangedEvent extends BmEvent {
  BmNameChangedEvent({required this.address, required this.name});

  String address;

  String name;

  List<Object?> _toList() {
    return <Object?>[address, name];
  }

  Object encode() {
    return _toList();
  }

  static BmNameChangedEvent decode(Object result) {
    result as List<Object?>;
    return BmNameChangedEvent(address: result[0]! as String, name: result[1]! as String);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! BmNameChangedEvent || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(address, other.address) && _deepEquals(name, other.name);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'BmNameChangedEvent(address: $address, name: $name)';
  }
}

class BmServicesResetEvent extends BmEvent {
  BmServicesResetEvent({required this.address});

  String address;

  List<Object?> _toList() {
    return <Object?>[address];
  }

  Object encode() {
    return _toList();
  }

  static BmServicesResetEvent decode(Object result) {
    result as List<Object?>;
    return BmServicesResetEvent(address: result[0]! as String);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! BmServicesResetEvent || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(address, other.address);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'BmServicesResetEvent(address: $address)';
  }
}

/// Emitted on any MTU change: solicited (requestMtu) or peer-initiated on
/// Android; on darwin, emitted after connect and whenever the negotiated
/// value changes (CoreBluetooth has no MTU callback, so the plugin polls
/// while devices are connected).
class BmMtuChangedEvent extends BmEvent {
  BmMtuChangedEvent({required this.address, required this.mtu});

  String address;

  int mtu;

  List<Object?> _toList() {
    return <Object?>[address, mtu];
  }

  Object encode() {
    return _toList();
  }

  static BmMtuChangedEvent decode(Object result) {
    result as List<Object?>;
    return BmMtuChangedEvent(address: result[0]! as String, mtu: result[1]! as int);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! BmMtuChangedEvent || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(address, other.address) && _deepEquals(mtu, other.mtu);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'BmMtuChangedEvent(address: $address, mtu: $mtu)';
  }
}

class BmDetachedFromEngineEvent extends BmEvent {
  BmDetachedFromEngineEvent({this.unused});

  /// Carries no information — pigeon requires data classes to have a field.
  bool? unused;

  List<Object?> _toList() {
    return <Object?>[unused];
  }

  Object encode() {
    return _toList();
  }

  static BmDetachedFromEngineEvent decode(Object result) {
    result as List<Object?>;
    return BmDetachedFromEngineEvent(unused: result[0] as bool?);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! BmDetachedFromEngineEvent || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(unused, other.unused);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'BmDetachedFromEngineEvent(unused: $unused)';
  }
}

/// An L2CAP connection-oriented channel closed *unsolicited* — the peer closed
/// it, the device disconnected, or a read/write failed. A successful open is
/// reported by [BluebirdHostApi.openL2capChannel]'s return value, and a
/// [closeL2capChannel] the app requested itself is confirmed by that call
/// completing, so neither emits this event. Channel *data* never crosses here:
/// it flows on the dedicated `bluebird/l2cap` binary channel (see
/// [BluebirdHostApi.openL2capChannel]).
class BmL2capChannelClosedEvent extends BmEvent {
  BmL2capChannelClosedEvent({required this.channelId, required this.address, this.errorCode, this.errorString});

  int channelId;

  String address;

  /// Wire error code (snake_case of a [BluebirdErrorCode]) when the close was
  /// caused by a failure; null for a clean peer/EOF close.
  String? errorCode;

  String? errorString;

  List<Object?> _toList() {
    return <Object?>[channelId, address, errorCode, errorString];
  }

  Object encode() {
    return _toList();
  }

  static BmL2capChannelClosedEvent decode(Object result) {
    result as List<Object?>;
    return BmL2capChannelClosedEvent(
      channelId: result[0]! as int,
      address: result[1]! as String,
      errorCode: result[2] as String?,
      errorString: result[3] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! BmL2capChannelClosedEvent || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(channelId, other.channelId) &&
        _deepEquals(address, other.address) &&
        _deepEquals(errorCode, other.errorCode) &&
        _deepEquals(errorString, other.errorString);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'BmL2capChannelClosedEvent(channelId: $channelId, address: $address, errorCode: $errorCode, errorString: $errorString)';
  }
}

class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    } else if (value is BluetoothAdapterState) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    } else if (value is BluetoothConnectionState) {
      buffer.putUint8(130);
      writeValue(buffer, value.index);
    } else if (value is BmWriteType) {
      buffer.putUint8(131);
      writeValue(buffer, value.index);
    } else if (value is ConnectionPriority) {
      buffer.putUint8(132);
      writeValue(buffer, value.index);
    } else if (value is BluetoothBondState) {
      buffer.putUint8(133);
      writeValue(buffer, value.index);
    } else if (value is LogLevel) {
      buffer.putUint8(134);
      writeValue(buffer, value.index);
    } else if (value is BluebirdErrorCode) {
      buffer.putUint8(135);
      writeValue(buffer, value.index);
    } else if (value is BmAttributeId) {
      buffer.putUint8(136);
      writeValue(buffer, value.encode());
    } else if (value is BmServiceRef) {
      buffer.putUint8(137);
      writeValue(buffer, value.encode());
    } else if (value is BmCharacteristicRef) {
      buffer.putUint8(138);
      writeValue(buffer, value.encode());
    } else if (value is BmDescriptorRef) {
      buffer.putUint8(139);
      writeValue(buffer, value.encode());
    } else if (value is BmMsdFilter) {
      buffer.putUint8(140);
      writeValue(buffer, value.encode());
    } else if (value is BmServiceDataFilter) {
      buffer.putUint8(141);
      writeValue(buffer, value.encode());
    } else if (value is BmScanSettings) {
      buffer.putUint8(142);
      writeValue(buffer, value.encode());
    } else if (value is BmScanAdvertisement) {
      buffer.putUint8(143);
      writeValue(buffer, value.encode());
    } else if (value is BmBluetoothDevice) {
      buffer.putUint8(144);
      writeValue(buffer, value.encode());
    } else if (value is BmBluetoothService) {
      buffer.putUint8(145);
      writeValue(buffer, value.encode());
    } else if (value is BmBluetoothCharacteristic) {
      buffer.putUint8(146);
      writeValue(buffer, value.encode());
    } else if (value is BmBluetoothDescriptor) {
      buffer.putUint8(147);
      writeValue(buffer, value.encode());
    } else if (value is BmCharacteristicProperties) {
      buffer.putUint8(148);
      writeValue(buffer, value.encode());
    } else if (value is BmPhySupport) {
      buffer.putUint8(149);
      writeValue(buffer, value.encode());
    } else if (value is BmAdapterStateEvent) {
      buffer.putUint8(150);
      writeValue(buffer, value.encode());
    } else if (value is BmScanAdvertisementEvent) {
      buffer.putUint8(151);
      writeValue(buffer, value.encode());
    } else if (value is BmScanFailedEvent) {
      buffer.putUint8(152);
      writeValue(buffer, value.encode());
    } else if (value is BmConnectionStateEvent) {
      buffer.putUint8(153);
      writeValue(buffer, value.encode());
    } else if (value is BmCharacteristicNotificationEvent) {
      buffer.putUint8(154);
      writeValue(buffer, value.encode());
    } else if (value is BmBondStateEvent) {
      buffer.putUint8(155);
      writeValue(buffer, value.encode());
    } else if (value is BmNameChangedEvent) {
      buffer.putUint8(156);
      writeValue(buffer, value.encode());
    } else if (value is BmServicesResetEvent) {
      buffer.putUint8(157);
      writeValue(buffer, value.encode());
    } else if (value is BmMtuChangedEvent) {
      buffer.putUint8(158);
      writeValue(buffer, value.encode());
    } else if (value is BmDetachedFromEngineEvent) {
      buffer.putUint8(159);
      writeValue(buffer, value.encode());
    } else if (value is BmL2capChannelClosedEvent) {
      buffer.putUint8(160);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        final value = readValue(buffer) as int?;
        return value == null ? null : BluetoothAdapterState.values[value];
      case 130:
        final value = readValue(buffer) as int?;
        return value == null ? null : BluetoothConnectionState.values[value];
      case 131:
        final value = readValue(buffer) as int?;
        return value == null ? null : BmWriteType.values[value];
      case 132:
        final value = readValue(buffer) as int?;
        return value == null ? null : ConnectionPriority.values[value];
      case 133:
        final value = readValue(buffer) as int?;
        return value == null ? null : BluetoothBondState.values[value];
      case 134:
        final value = readValue(buffer) as int?;
        return value == null ? null : LogLevel.values[value];
      case 135:
        final value = readValue(buffer) as int?;
        return value == null ? null : BluebirdErrorCode.values[value];
      case 136:
        return BmAttributeId.decode(readValue(buffer)!);
      case 137:
        return BmServiceRef.decode(readValue(buffer)!);
      case 138:
        return BmCharacteristicRef.decode(readValue(buffer)!);
      case 139:
        return BmDescriptorRef.decode(readValue(buffer)!);
      case 140:
        return BmMsdFilter.decode(readValue(buffer)!);
      case 141:
        return BmServiceDataFilter.decode(readValue(buffer)!);
      case 142:
        return BmScanSettings.decode(readValue(buffer)!);
      case 143:
        return BmScanAdvertisement.decode(readValue(buffer)!);
      case 144:
        return BmBluetoothDevice.decode(readValue(buffer)!);
      case 145:
        return BmBluetoothService.decode(readValue(buffer)!);
      case 146:
        return BmBluetoothCharacteristic.decode(readValue(buffer)!);
      case 147:
        return BmBluetoothDescriptor.decode(readValue(buffer)!);
      case 148:
        return BmCharacteristicProperties.decode(readValue(buffer)!);
      case 149:
        return BmPhySupport.decode(readValue(buffer)!);
      case 150:
        return BmAdapterStateEvent.decode(readValue(buffer)!);
      case 151:
        return BmScanAdvertisementEvent.decode(readValue(buffer)!);
      case 152:
        return BmScanFailedEvent.decode(readValue(buffer)!);
      case 153:
        return BmConnectionStateEvent.decode(readValue(buffer)!);
      case 154:
        return BmCharacteristicNotificationEvent.decode(readValue(buffer)!);
      case 155:
        return BmBondStateEvent.decode(readValue(buffer)!);
      case 156:
        return BmNameChangedEvent.decode(readValue(buffer)!);
      case 157:
        return BmServicesResetEvent.decode(readValue(buffer)!);
      case 158:
        return BmMtuChangedEvent.decode(readValue(buffer)!);
      case 159:
        return BmDetachedFromEngineEvent.decode(readValue(buffer)!);
      case 160:
        return BmL2capChannelClosedEvent.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

const StandardMethodCodec pigeonMethodCodec = StandardMethodCodec(_PigeonCodec());

/// Returns a broadcast [Stream] of events from the `nativeEvents` event channel.
///
/// Each call to this method creates a new [EventChannel], so it should
/// not be called multiple times for the same `instanceName`. To deliver
/// events to multiple listeners, call this method once and listen to the
/// returned broadcast stream multiple times instead.
Stream<BmEvent> nativeEvents({String instanceName = ''}) {
  if (instanceName.isNotEmpty) {
    instanceName = '.$instanceName';
  }
  final EventChannel nativeEventsChannel = EventChannel(
    'dev.flutter.pigeon.bluebird.BluebirdEventChannelApi.nativeEvents$instanceName',
    pigeonMethodCodec,
  );
  return nativeEventsChannel.receiveBroadcastStream().map((dynamic event) {
    return event as BmEvent;
  });
}

class BluebirdHostApi {
  /// Constructor for [BluebirdHostApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  BluebirdHostApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
    : pigeonVar_binaryMessenger = binaryMessenger,
      pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// Hot-restart handshake: disconnects and closes everything, returns the
  /// number of devices still closing.
  Future<int> flutterRestart() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.bluebird.BluebirdHostApi.flutterRestart$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as int;
  }

  Future<int> connectedCount() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.bluebird.BluebirdHostApi.connectedCount$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as int;
  }

  Future<void> setLogLevel(LogLevel level) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.bluebird.BluebirdHostApi.setLogLevel$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[level]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(pigeonVar_replyList, pigeonVar_channelName, isNullValid: true);
  }

  Future<void> setOptions(bool showPowerAlert, bool restoreState) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.bluebird.BluebirdHostApi.setOptions$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[showPowerAlert, restoreState]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(pigeonVar_replyList, pigeonVar_channelName, isNullValid: true);
  }

  Future<bool> isSupported() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.bluebird.BluebirdHostApi.isSupported$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as bool;
  }

  /// @async: may need to request runtime permissions before answering.
  Future<String> getAdapterName() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.bluebird.BluebirdHostApi.getAdapterName$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as String;
  }

  Future<BluetoothAdapterState> getAdapterState() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.bluebird.BluebirdHostApi.getAdapterState$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as BluetoothAdapterState;
  }

  /// Android: shows the enable-bluetooth dialog; completes with user consent.
  Future<bool> turnOn() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.bluebird.BluebirdHostApi.turnOn$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as bool;
  }

  Future<bool> turnOff() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.bluebird.BluebirdHostApi.turnOff$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as bool;
  }

  Future<void> startScan(BmScanSettings settings) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.bluebird.BluebirdHostApi.startScan$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[settings]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(pigeonVar_replyList, pigeonVar_channelName, isNullValid: true);
  }

  Future<void> stopScan() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.bluebird.BluebirdHostApi.stopScan$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(pigeonVar_replyList, pigeonVar_channelName, isNullValid: true);
  }

  Future<List<BmBluetoothDevice>> getSystemDevices(List<String> withServices) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.bluebird.BluebirdHostApi.getSystemDevices$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[withServices]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return (pigeonVar_replyValue! as List<Object?>).cast<BmBluetoothDevice>();
  }

  Future<List<BmBluetoothDevice>> getBondedDevices() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.bluebird.BluebirdHostApi.getBondedDevices$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return (pigeonVar_replyValue! as List<Object?>).cast<BmBluetoothDevice>();
  }

  Future<void> connect(String address) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.bluebird.BluebirdHostApi.connect$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[address]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(pigeonVar_replyList, pigeonVar_channelName, isNullValid: true);
  }

  Future<void> disconnect(String address) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.bluebird.BluebirdHostApi.disconnect$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[address]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(pigeonVar_replyList, pigeonVar_channelName, isNullValid: true);
  }

  Future<List<BmBluetoothService>> discoverServices(String address) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.bluebird.BluebirdHostApi.discoverServices$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[address]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return (pigeonVar_replyValue! as List<Object?>).cast<BmBluetoothService>();
  }

  Future<Uint8List> readCharacteristic(String address, BmCharacteristicRef characteristic) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.bluebird.BluebirdHostApi.readCharacteristic$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[address, characteristic]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as Uint8List;
  }

  Future<void> writeCharacteristic(
    String address,
    BmCharacteristicRef characteristic,
    BmWriteType writeType,
    bool allowLongWrite,
    Uint8List value,
  ) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.bluebird.BluebirdHostApi.writeCharacteristic$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[
      address,
      characteristic,
      writeType,
      allowLongWrite,
      value,
    ]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(pigeonVar_replyList, pigeonVar_channelName, isNullValid: true);
  }

  Future<Uint8List> readDescriptor(String address, BmDescriptorRef descriptor) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.bluebird.BluebirdHostApi.readDescriptor$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[address, descriptor]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as Uint8List;
  }

  Future<void> writeDescriptor(String address, BmDescriptorRef descriptor, Uint8List value) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.bluebird.BluebirdHostApi.writeDescriptor$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[address, descriptor, value]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(pigeonVar_replyList, pigeonVar_channelName, isNullValid: true);
  }

  /// Completes after the CCCD write confirms (or immediately if no CCCD).
  Future<bool> setNotifyValue(String address, BmCharacteristicRef characteristic, bool enable) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.bluebird.BluebirdHostApi.setNotifyValue$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[address, characteristic, enable]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as bool;
  }

  Future<int> requestMtu(String address, int mtu) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.bluebird.BluebirdHostApi.requestMtu$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[address, mtu]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as int;
  }

  Future<int> readRssi(String address) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.bluebird.BluebirdHostApi.readRssi$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[address]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as int;
  }

  Future<void> requestConnectionPriority(String address, ConnectionPriority connectionPriority) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.bluebird.BluebirdHostApi.requestConnectionPriority$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[address, connectionPriority]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(pigeonVar_replyList, pigeonVar_channelName, isNullValid: true);
  }

  Future<BmPhySupport> getPhySupport() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.bluebird.BluebirdHostApi.getPhySupport$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as BmPhySupport;
  }

  Future<void> setPreferredPhy(String address, int txPhy, int rxPhy, int phyOptions) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.bluebird.BluebirdHostApi.setPreferredPhy$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[address, txPhy, rxPhy, phyOptions]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(pigeonVar_replyList, pigeonVar_channelName, isNullValid: true);
  }

  Future<BluetoothBondState> getBondState(String address) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.bluebird.BluebirdHostApi.getBondState$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[address]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as BluetoothBondState;
  }

  Future<bool> createBond(String address, Uint8List? pin) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.bluebird.BluebirdHostApi.createBond$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[address, pin]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as bool;
  }

  Future<bool> removeBond(String address) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.bluebird.BluebirdHostApi.removeBond$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[address]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as bool;
  }

  Future<void> clearGattCache(String address) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.bluebird.BluebirdHostApi.clearGattCache$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[address]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(pigeonVar_replyList, pigeonVar_channelName, isNullValid: true);
  }

  Future<int> openL2capChannel(String address, int psm, bool secure) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.bluebird.BluebirdHostApi.openL2capChannel$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[address, psm, secure]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as int;
  }

  Future<void> closeL2capChannel(int channelId) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.bluebird.BluebirdHostApi.closeL2capChannel$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[channelId]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(pigeonVar_replyList, pigeonVar_channelName, isNullValid: true);
  }
}
