name: flutter_blue_plus
description: Flutter plugin for connecting and communicating with Bluetooth Low Energy devices, on Android, iOS, and MacOS.
version: 1.34.4
homepage: https://github.com/boskokg/flutter_blue_plus

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=3.27.0"
resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  # use specific versions.
  #  - users otherwise forget to update all
  #  - simpler bug reporting
  #  - unified changelog
  #  - users can still manually override
  flutter_blue_plus_platform_interface: 7.0.0
  flutter_blue_plus_android: 7.0.4
  flutter_blue_plus_darwin: 7.0.3
#  flutter_blue_plus_linux: 7.0.3
#  flutter_blue_plus_web: 7.0.2

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        default_package: flutter_blue_plus_android
      ios:
        default_package: flutter_blue_plus_darwin
      macos:
        default_package: flutter_blue_plus_darwin
      # parked:
      # linux:
      #   default_package: flutter_blue_plus_linux
      # web:
      #   default_package: flutter_blue_plus_web