// Autogenerated from Pigeon (v27.1.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.lib.bluebird

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object MessagesPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

enum class BmAdapterStateEnum(val raw: Int) {
  UNKNOWN(0),
  UNAVAILABLE(1),
  UNAUTHORIZED(2),
  TURNING_ON(3),
  ON(4),
  TURNING_OFF(5),
  OFF(6);

  companion object {
    fun ofRaw(raw: Int): BmAdapterStateEnum? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class BmConnectionStateEnum(val raw: Int) {
  DISCONNECTED(0),
  CONNECTED(1);

  companion object {
    fun ofRaw(raw: Int): BmConnectionStateEnum? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class BmWriteType(val raw: Int) {
  WITH_RESPONSE(0),
  WITHOUT_RESPONSE(1);

  companion object {
    fun ofRaw(raw: Int): BmWriteType? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class BmConnectionPriorityEnum(val raw: Int) {
  BALANCED(0),
  HIGH(1),
  LOW_POWER(2);

  companion object {
    fun ofRaw(raw: Int): BmConnectionPriorityEnum? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class BmBondStateEnum(val raw: Int) {
  NONE(0),
  BONDING(1),
  BONDED(2);

  companion object {
    fun ofRaw(raw: Int): BmBondStateEnum? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class LogLevel(val raw: Int) {
  NONE(0),
  ERROR(1),
  WARNING(2),
  INFO(3),
  DEBUG(4),
  VERBOSE(5);

  companion object {
    fun ofRaw(raw: Int): LogLevel? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/**
 * Single source of truth for error codes, shared by every platform.
 *
 * Errors cross the channel as `PlatformException.code` *strings* (pigeon
 * cannot type that field), so the wire form of each code is, by convention,
 * the snake_case of its name here (e.g. [BluebirdErrorCode.deviceDisconnected]
 * crosses as `"device_disconnected"`). Each language has a small `wire`
 * helper implementing that convention; never hand-write a code string.
 */
enum class BluebirdErrorCode(val raw: Int) {
  SUCCESS(0),
  TIMEOUT(1),
  PLATFORM(2),
  SERVICE_NOT_FOUND(3),
  CHARACTERISTIC_NOT_FOUND(4),
  USER_REJECTED(5),
  REMOVE_BOND_FAILED(6),
  GATT_ERROR(7),
  CB_ERROR(8),
  DEVICE_DISCONNECTED(9),
  ADAPTER_OFF(10),
  NOT_CONNECTED(11),
  INVALID_IDENTIFIER(12),
  BOND_FAILED(13),
  USER_CANCELED(14),
  UNSUPPORTED(15),
  OPERATION_IN_PROGRESS(16),
  PERMISSION_DENIED(17),
  INVALID_ARGUMENT(18);

  companion object {
    fun ofRaw(raw: Int): BluebirdErrorCode? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/**
 * The universal uuid:instance pair identifying one attribute.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class BmAttributeId (
  val uuid: String,
  /** Platform-opaque token disambiguating duplicate uuids. */
  val instance: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): BmAttributeId {
      val uuid = pigeonVar_list[0] as String
      val instance = pigeonVar_list[1] as Long
      return BmAttributeId(uuid, instance)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      uuid,
      instance,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as BmAttributeId
    return MessagesPigeonUtils.deepEquals(this.uuid, other.uuid) && MessagesPigeonUtils.deepEquals(this.instance, other.instance)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.uuid)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.instance)
    return result
  }
  override fun toString(): String {
    return "BmAttributeId(uuid=$uuid, instance=$instance)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class BmServiceRef (
  val service: BmAttributeId,
  /** Set when this is a secondary (included) service. */
  val parentService: BmAttributeId? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): BmServiceRef {
      val service = pigeonVar_list[0] as BmAttributeId
      val parentService = pigeonVar_list[1] as BmAttributeId?
      return BmServiceRef(service, parentService)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      service,
      parentService,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as BmServiceRef
    return MessagesPigeonUtils.deepEquals(this.service, other.service) && MessagesPigeonUtils.deepEquals(this.parentService, other.parentService)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.service)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.parentService)
    return result
  }
  override fun toString(): String {
    return "BmServiceRef(service=$service, parentService=$parentService)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class BmCharacteristicRef (
  val service: BmServiceRef,
  val characteristic: BmAttributeId
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): BmCharacteristicRef {
      val service = pigeonVar_list[0] as BmServiceRef
      val characteristic = pigeonVar_list[1] as BmAttributeId
      return BmCharacteristicRef(service, characteristic)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      service,
      characteristic,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as BmCharacteristicRef
    return MessagesPigeonUtils.deepEquals(this.service, other.service) && MessagesPigeonUtils.deepEquals(this.characteristic, other.characteristic)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.service)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.characteristic)
    return result
  }
  override fun toString(): String {
    return "BmCharacteristicRef(service=$service, characteristic=$characteristic)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class BmDescriptorRef (
  val characteristic: BmCharacteristicRef,
  /** Descriptor uuids are unique within a characteristic; no instance needed. */
  val uuid: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): BmDescriptorRef {
      val characteristic = pigeonVar_list[0] as BmCharacteristicRef
      val uuid = pigeonVar_list[1] as String
      return BmDescriptorRef(characteristic, uuid)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      characteristic,
      uuid,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as BmDescriptorRef
    return MessagesPigeonUtils.deepEquals(this.characteristic, other.characteristic) && MessagesPigeonUtils.deepEquals(this.uuid, other.uuid)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.characteristic)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.uuid)
    return result
  }
  override fun toString(): String {
    return "BmDescriptorRef(characteristic=$characteristic, uuid=$uuid)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class BmMsdFilter (
  val manufacturerId: Long,
  val data: ByteArray? = null,
  val mask: ByteArray? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): BmMsdFilter {
      val manufacturerId = pigeonVar_list[0] as Long
      val data = pigeonVar_list[1] as ByteArray?
      val mask = pigeonVar_list[2] as ByteArray?
      return BmMsdFilter(manufacturerId, data, mask)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      manufacturerId,
      data,
      mask,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as BmMsdFilter
    return MessagesPigeonUtils.deepEquals(this.manufacturerId, other.manufacturerId) && MessagesPigeonUtils.deepEquals(this.data, other.data) && MessagesPigeonUtils.deepEquals(this.mask, other.mask)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.manufacturerId)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.data)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.mask)
    return result
  }
  override fun toString(): String {
    return "BmMsdFilter(manufacturerId=$manufacturerId, data=${data?.contentToString()}, mask=${mask?.contentToString()})"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class BmServiceDataFilter (
  val service: String,
  val data: ByteArray,
  val mask: ByteArray? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): BmServiceDataFilter {
      val service = pigeonVar_list[0] as String
      val data = pigeonVar_list[1] as ByteArray
      val mask = pigeonVar_list[2] as ByteArray?
      return BmServiceDataFilter(service, data, mask)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      service,
      data,
      mask,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as BmServiceDataFilter
    return MessagesPigeonUtils.deepEquals(this.service, other.service) && MessagesPigeonUtils.deepEquals(this.data, other.data) && MessagesPigeonUtils.deepEquals(this.mask, other.mask)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.service)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.data)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.mask)
    return result
  }
  override fun toString(): String {
    return "BmServiceDataFilter(service=$service, data=${data.contentToString()}, mask=${mask?.contentToString()})"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class BmScanSettings (
  val withServices: List<String>,
  val withRemoteIds: List<String>,
  val withNames: List<String>,
  val withKeywords: List<String>,
  val withMsd: List<BmMsdFilter>,
  val withServiceData: List<BmServiceDataFilter>,
  val continuousUpdates: Boolean,
  val continuousDivisor: Long,
  val androidLegacy: Boolean,
  val androidScanMode: Long,
  val androidUsesFineLocation: Boolean,
  val webOptionalServices: List<String>
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): BmScanSettings {
      val withServices = pigeonVar_list[0] as List<String>
      val withRemoteIds = pigeonVar_list[1] as List<String>
      val withNames = pigeonVar_list[2] as List<String>
      val withKeywords = pigeonVar_list[3] as List<String>
      val withMsd = pigeonVar_list[4] as List<BmMsdFilter>
      val withServiceData = pigeonVar_list[5] as List<BmServiceDataFilter>
      val continuousUpdates = pigeonVar_list[6] as Boolean
      val continuousDivisor = pigeonVar_list[7] as Long
      val androidLegacy = pigeonVar_list[8] as Boolean
      val androidScanMode = pigeonVar_list[9] as Long
      val androidUsesFineLocation = pigeonVar_list[10] as Boolean
      val webOptionalServices = pigeonVar_list[11] as List<String>
      return BmScanSettings(withServices, withRemoteIds, withNames, withKeywords, withMsd, withServiceData, continuousUpdates, continuousDivisor, androidLegacy, androidScanMode, androidUsesFineLocation, webOptionalServices)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      withServices,
      withRemoteIds,
      withNames,
      withKeywords,
      withMsd,
      withServiceData,
      continuousUpdates,
      continuousDivisor,
      androidLegacy,
      androidScanMode,
      androidUsesFineLocation,
      webOptionalServices,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as BmScanSettings
    return MessagesPigeonUtils.deepEquals(this.withServices, other.withServices) && MessagesPigeonUtils.deepEquals(this.withRemoteIds, other.withRemoteIds) && MessagesPigeonUtils.deepEquals(this.withNames, other.withNames) && MessagesPigeonUtils.deepEquals(this.withKeywords, other.withKeywords) && MessagesPigeonUtils.deepEquals(this.withMsd, other.withMsd) && MessagesPigeonUtils.deepEquals(this.withServiceData, other.withServiceData) && MessagesPigeonUtils.deepEquals(this.continuousUpdates, other.continuousUpdates) && MessagesPigeonUtils.deepEquals(this.continuousDivisor, other.continuousDivisor) && MessagesPigeonUtils.deepEquals(this.androidLegacy, other.androidLegacy) && MessagesPigeonUtils.deepEquals(this.androidScanMode, other.androidScanMode) && MessagesPigeonUtils.deepEquals(this.androidUsesFineLocation, other.androidUsesFineLocation) && MessagesPigeonUtils.deepEquals(this.webOptionalServices, other.webOptionalServices)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.withServices)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.withRemoteIds)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.withNames)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.withKeywords)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.withMsd)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.withServiceData)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.continuousUpdates)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.continuousDivisor)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.androidLegacy)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.androidScanMode)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.androidUsesFineLocation)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.webOptionalServices)
    return result
  }
  override fun toString(): String {
    return "BmScanSettings(withServices=$withServices, withRemoteIds=$withRemoteIds, withNames=$withNames, withKeywords=$withKeywords, withMsd=$withMsd, withServiceData=$withServiceData, continuousUpdates=$continuousUpdates, continuousDivisor=$continuousDivisor, androidLegacy=$androidLegacy, androidScanMode=$androidScanMode, androidUsesFineLocation=$androidUsesFineLocation, webOptionalServices=$webOptionalServices)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class BmScanAdvertisement (
  val address: String,
  val platformName: String? = null,
  val advName: String? = null,
  val connectable: Boolean,
  val txPowerLevel: Long? = null,
  /** Not supported on iOS / macOS. */
  val appearance: Long? = null,
  val manufacturerData: Map<Long, ByteArray>,
  val serviceData: Map<String, ByteArray>,
  val serviceUuids: List<String>,
  val rssi: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): BmScanAdvertisement {
      val address = pigeonVar_list[0] as String
      val platformName = pigeonVar_list[1] as String?
      val advName = pigeonVar_list[2] as String?
      val connectable = pigeonVar_list[3] as Boolean
      val txPowerLevel = pigeonVar_list[4] as Long?
      val appearance = pigeonVar_list[5] as Long?
      val manufacturerData = pigeonVar_list[6] as Map<Long, ByteArray>
      val serviceData = pigeonVar_list[7] as Map<String, ByteArray>
      val serviceUuids = pigeonVar_list[8] as List<String>
      val rssi = pigeonVar_list[9] as Long
      return BmScanAdvertisement(address, platformName, advName, connectable, txPowerLevel, appearance, manufacturerData, serviceData, serviceUuids, rssi)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      address,
      platformName,
      advName,
      connectable,
      txPowerLevel,
      appearance,
      manufacturerData,
      serviceData,
      serviceUuids,
      rssi,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as BmScanAdvertisement
    return MessagesPigeonUtils.deepEquals(this.address, other.address) && MessagesPigeonUtils.deepEquals(this.platformName, other.platformName) && MessagesPigeonUtils.deepEquals(this.advName, other.advName) && MessagesPigeonUtils.deepEquals(this.connectable, other.connectable) && MessagesPigeonUtils.deepEquals(this.txPowerLevel, other.txPowerLevel) && MessagesPigeonUtils.deepEquals(this.appearance, other.appearance) && MessagesPigeonUtils.deepEquals(this.manufacturerData, other.manufacturerData) && MessagesPigeonUtils.deepEquals(this.serviceData, other.serviceData) && MessagesPigeonUtils.deepEquals(this.serviceUuids, other.serviceUuids) && MessagesPigeonUtils.deepEquals(this.rssi, other.rssi)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.address)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.platformName)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.advName)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.connectable)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.txPowerLevel)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.appearance)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.manufacturerData)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.serviceData)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.serviceUuids)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.rssi)
    return result
  }
  override fun toString(): String {
    return "BmScanAdvertisement(address=$address, platformName=$platformName, advName=$advName, connectable=$connectable, txPowerLevel=$txPowerLevel, appearance=$appearance, manufacturerData=$manufacturerData, serviceData=$serviceData, serviceUuids=$serviceUuids, rssi=$rssi)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class BmBluetoothDevice (
  val address: String,
  val platformName: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): BmBluetoothDevice {
      val address = pigeonVar_list[0] as String
      val platformName = pigeonVar_list[1] as String?
      return BmBluetoothDevice(address, platformName)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      address,
      platformName,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as BmBluetoothDevice
    return MessagesPigeonUtils.deepEquals(this.address, other.address) && MessagesPigeonUtils.deepEquals(this.platformName, other.platformName)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.address)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.platformName)
    return result
  }
  override fun toString(): String {
    return "BmBluetoothDevice(address=$address, platformName=$platformName)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class BmBluetoothService (
  val id: BmAttributeId,
  val isPrimary: Boolean,
  val characteristics: List<BmBluetoothCharacteristic>,
  val includedServices: List<BmServiceRef>
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): BmBluetoothService {
      val id = pigeonVar_list[0] as BmAttributeId
      val isPrimary = pigeonVar_list[1] as Boolean
      val characteristics = pigeonVar_list[2] as List<BmBluetoothCharacteristic>
      val includedServices = pigeonVar_list[3] as List<BmServiceRef>
      return BmBluetoothService(id, isPrimary, characteristics, includedServices)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      id,
      isPrimary,
      characteristics,
      includedServices,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as BmBluetoothService
    return MessagesPigeonUtils.deepEquals(this.id, other.id) && MessagesPigeonUtils.deepEquals(this.isPrimary, other.isPrimary) && MessagesPigeonUtils.deepEquals(this.characteristics, other.characteristics) && MessagesPigeonUtils.deepEquals(this.includedServices, other.includedServices)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.id)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.isPrimary)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.characteristics)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.includedServices)
    return result
  }
  override fun toString(): String {
    return "BmBluetoothService(id=$id, isPrimary=$isPrimary, characteristics=$characteristics, includedServices=$includedServices)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class BmBluetoothCharacteristic (
  val id: BmAttributeId,
  val descriptors: List<BmBluetoothDescriptor>,
  val properties: BmCharacteristicProperties
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): BmBluetoothCharacteristic {
      val id = pigeonVar_list[0] as BmAttributeId
      val descriptors = pigeonVar_list[1] as List<BmBluetoothDescriptor>
      val properties = pigeonVar_list[2] as BmCharacteristicProperties
      return BmBluetoothCharacteristic(id, descriptors, properties)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      id,
      descriptors,
      properties,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as BmBluetoothCharacteristic
    return MessagesPigeonUtils.deepEquals(this.id, other.id) && MessagesPigeonUtils.deepEquals(this.descriptors, other.descriptors) && MessagesPigeonUtils.deepEquals(this.properties, other.properties)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.id)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.descriptors)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.properties)
    return result
  }
  override fun toString(): String {
    return "BmBluetoothCharacteristic(id=$id, descriptors=$descriptors, properties=$properties)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class BmBluetoothDescriptor (
  val uuid: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): BmBluetoothDescriptor {
      val uuid = pigeonVar_list[0] as String
      return BmBluetoothDescriptor(uuid)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      uuid,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as BmBluetoothDescriptor
    return MessagesPigeonUtils.deepEquals(this.uuid, other.uuid)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.uuid)
    return result
  }
  override fun toString(): String {
    return "BmBluetoothDescriptor(uuid=$uuid)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class BmCharacteristicProperties (
  val broadcast: Boolean,
  val read: Boolean,
  val writeWithoutResponse: Boolean,
  val write: Boolean,
  val notify: Boolean,
  val indicate: Boolean,
  val authenticatedSignedWrites: Boolean,
  val extendedProperties: Boolean,
  val notifyEncryptionRequired: Boolean,
  val indicateEncryptionRequired: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): BmCharacteristicProperties {
      val broadcast = pigeonVar_list[0] as Boolean
      val read = pigeonVar_list[1] as Boolean
      val writeWithoutResponse = pigeonVar_list[2] as Boolean
      val write = pigeonVar_list[3] as Boolean
      val notify = pigeonVar_list[4] as Boolean
      val indicate = pigeonVar_list[5] as Boolean
      val authenticatedSignedWrites = pigeonVar_list[6] as Boolean
      val extendedProperties = pigeonVar_list[7] as Boolean
      val notifyEncryptionRequired = pigeonVar_list[8] as Boolean
      val indicateEncryptionRequired = pigeonVar_list[9] as Boolean
      return BmCharacteristicProperties(broadcast, read, writeWithoutResponse, write, notify, indicate, authenticatedSignedWrites, extendedProperties, notifyEncryptionRequired, indicateEncryptionRequired)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      broadcast,
      read,
      writeWithoutResponse,
      write,
      notify,
      indicate,
      authenticatedSignedWrites,
      extendedProperties,
      notifyEncryptionRequired,
      indicateEncryptionRequired,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as BmCharacteristicProperties
    return MessagesPigeonUtils.deepEquals(this.broadcast, other.broadcast) && MessagesPigeonUtils.deepEquals(this.read, other.read) && MessagesPigeonUtils.deepEquals(this.writeWithoutResponse, other.writeWithoutResponse) && MessagesPigeonUtils.deepEquals(this.write, other.write) && MessagesPigeonUtils.deepEquals(this.notify, other.notify) && MessagesPigeonUtils.deepEquals(this.indicate, other.indicate) && MessagesPigeonUtils.deepEquals(this.authenticatedSignedWrites, other.authenticatedSignedWrites) && MessagesPigeonUtils.deepEquals(this.extendedProperties, other.extendedProperties) && MessagesPigeonUtils.deepEquals(this.notifyEncryptionRequired, other.notifyEncryptionRequired) && MessagesPigeonUtils.deepEquals(this.indicateEncryptionRequired, other.indicateEncryptionRequired)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.broadcast)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.read)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.writeWithoutResponse)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.write)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.notify)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.indicate)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.authenticatedSignedWrites)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.extendedProperties)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.notifyEncryptionRequired)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.indicateEncryptionRequired)
    return result
  }
  override fun toString(): String {
    return "BmCharacteristicProperties(broadcast=$broadcast, read=$read, writeWithoutResponse=$writeWithoutResponse, write=$write, notify=$notify, indicate=$indicate, authenticatedSignedWrites=$authenticatedSignedWrites, extendedProperties=$extendedProperties, notifyEncryptionRequired=$notifyEncryptionRequired, indicateEncryptionRequired=$indicateEncryptionRequired)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class BmPhySupport (
  /** High speed (PHY 2M) */
  val le2M: Boolean,
  /** Long range (PHY codec) */
  val leCoded: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): BmPhySupport {
      val le2M = pigeonVar_list[0] as Boolean
      val leCoded = pigeonVar_list[1] as Boolean
      return BmPhySupport(le2M, leCoded)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      le2M,
      leCoded,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as BmPhySupport
    return MessagesPigeonUtils.deepEquals(this.le2M, other.le2M) && MessagesPigeonUtils.deepEquals(this.leCoded, other.leCoded)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.le2M)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.leCoded)
    return result
  }
  override fun toString(): String {
    return "BmPhySupport(le2M=$le2M, leCoded=$leCoded)"
  }
}

/**
 * Generated class from Pigeon that represents data sent in messages.
 * This class should not be extended by any user class outside of the generated file.
 */
sealed class BmEvent 
/** Generated class from Pigeon that represents data sent in messages. */
data class BmAdapterStateEvent (
  val adapterState: BmAdapterStateEnum
) : BmEvent()
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): BmAdapterStateEvent {
      val adapterState = pigeonVar_list[0] as BmAdapterStateEnum
      return BmAdapterStateEvent(adapterState)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      adapterState,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as BmAdapterStateEvent
    return MessagesPigeonUtils.deepEquals(this.adapterState, other.adapterState)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.adapterState)
    return result
  }
  override fun toString(): String {
    return "BmAdapterStateEvent(adapterState=$adapterState)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class BmScanAdvertisementsEvent (
  val advertisements: List<BmScanAdvertisement>
) : BmEvent()
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): BmScanAdvertisementsEvent {
      val advertisements = pigeonVar_list[0] as List<BmScanAdvertisement>
      return BmScanAdvertisementsEvent(advertisements)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      advertisements,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as BmScanAdvertisementsEvent
    return MessagesPigeonUtils.deepEquals(this.advertisements, other.advertisements)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.advertisements)
    return result
  }
  override fun toString(): String {
    return "BmScanAdvertisementsEvent(advertisements=$advertisements)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class BmScanFailedEvent (
  val errorCode: Long,
  val errorString: String
) : BmEvent()
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): BmScanFailedEvent {
      val errorCode = pigeonVar_list[0] as Long
      val errorString = pigeonVar_list[1] as String
      return BmScanFailedEvent(errorCode, errorString)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      errorCode,
      errorString,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as BmScanFailedEvent
    return MessagesPigeonUtils.deepEquals(this.errorCode, other.errorCode) && MessagesPigeonUtils.deepEquals(this.errorString, other.errorString)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.errorCode)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.errorString)
    return result
  }
  override fun toString(): String {
    return "BmScanFailedEvent(errorCode=$errorCode, errorString=$errorString)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class BmConnectionStateEvent (
  val address: String,
  val connectionState: BmConnectionStateEnum,
  val disconnectReasonCode: Long? = null,
  val disconnectReasonString: String? = null
) : BmEvent()
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): BmConnectionStateEvent {
      val address = pigeonVar_list[0] as String
      val connectionState = pigeonVar_list[1] as BmConnectionStateEnum
      val disconnectReasonCode = pigeonVar_list[2] as Long?
      val disconnectReasonString = pigeonVar_list[3] as String?
      return BmConnectionStateEvent(address, connectionState, disconnectReasonCode, disconnectReasonString)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      address,
      connectionState,
      disconnectReasonCode,
      disconnectReasonString,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as BmConnectionStateEvent
    return MessagesPigeonUtils.deepEquals(this.address, other.address) && MessagesPigeonUtils.deepEquals(this.connectionState, other.connectionState) && MessagesPigeonUtils.deepEquals(this.disconnectReasonCode, other.disconnectReasonCode) && MessagesPigeonUtils.deepEquals(this.disconnectReasonString, other.disconnectReasonString)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.address)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.connectionState)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.disconnectReasonCode)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.disconnectReasonString)
    return result
  }
  override fun toString(): String {
    return "BmConnectionStateEvent(address=$address, connectionState=$connectionState, disconnectReasonCode=$disconnectReasonCode, disconnectReasonString=$disconnectReasonString)"
  }
}

/**
 * A characteristic value received via notify/indicate. Read responses are
 * returned from [BluebirdHostApi.readCharacteristic] instead.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class BmCharacteristicNotificationEvent (
  val address: String,
  val characteristic: BmCharacteristicRef,
  val value: ByteArray
) : BmEvent()
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): BmCharacteristicNotificationEvent {
      val address = pigeonVar_list[0] as String
      val characteristic = pigeonVar_list[1] as BmCharacteristicRef
      val value = pigeonVar_list[2] as ByteArray
      return BmCharacteristicNotificationEvent(address, characteristic, value)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      address,
      characteristic,
      value,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as BmCharacteristicNotificationEvent
    return MessagesPigeonUtils.deepEquals(this.address, other.address) && MessagesPigeonUtils.deepEquals(this.characteristic, other.characteristic) && MessagesPigeonUtils.deepEquals(this.value, other.value)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.address)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.characteristic)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.value)
    return result
  }
  override fun toString(): String {
    return "BmCharacteristicNotificationEvent(address=$address, characteristic=$characteristic, value=${value.contentToString()})"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class BmBondStateEvent (
  val address: String,
  val bondState: BmBondStateEnum,
  val prevState: BmBondStateEnum? = null
) : BmEvent()
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): BmBondStateEvent {
      val address = pigeonVar_list[0] as String
      val bondState = pigeonVar_list[1] as BmBondStateEnum
      val prevState = pigeonVar_list[2] as BmBondStateEnum?
      return BmBondStateEvent(address, bondState, prevState)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      address,
      bondState,
      prevState,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as BmBondStateEvent
    return MessagesPigeonUtils.deepEquals(this.address, other.address) && MessagesPigeonUtils.deepEquals(this.bondState, other.bondState) && MessagesPigeonUtils.deepEquals(this.prevState, other.prevState)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.address)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.bondState)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.prevState)
    return result
  }
  override fun toString(): String {
    return "BmBondStateEvent(address=$address, bondState=$bondState, prevState=$prevState)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class BmNameChangedEvent (
  val address: String,
  val name: String
) : BmEvent()
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): BmNameChangedEvent {
      val address = pigeonVar_list[0] as String
      val name = pigeonVar_list[1] as String
      return BmNameChangedEvent(address, name)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      address,
      name,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as BmNameChangedEvent
    return MessagesPigeonUtils.deepEquals(this.address, other.address) && MessagesPigeonUtils.deepEquals(this.name, other.name)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.address)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.name)
    return result
  }
  override fun toString(): String {
    return "BmNameChangedEvent(address=$address, name=$name)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class BmServicesResetEvent (
  val address: String
) : BmEvent()
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): BmServicesResetEvent {
      val address = pigeonVar_list[0] as String
      return BmServicesResetEvent(address)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      address,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as BmServicesResetEvent
    return MessagesPigeonUtils.deepEquals(this.address, other.address)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.address)
    return result
  }
  override fun toString(): String {
    return "BmServicesResetEvent(address=$address)"
  }
}

/**
 * Emitted on any MTU change: solicited (requestMtu) or peer-initiated on
 * Android; on darwin, emitted after connect and whenever the negotiated
 * value changes (CoreBluetooth has no MTU callback, so the plugin polls
 * while devices are connected).
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class BmMtuChangedEvent (
  val address: String,
  val mtu: Long
) : BmEvent()
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): BmMtuChangedEvent {
      val address = pigeonVar_list[0] as String
      val mtu = pigeonVar_list[1] as Long
      return BmMtuChangedEvent(address, mtu)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      address,
      mtu,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as BmMtuChangedEvent
    return MessagesPigeonUtils.deepEquals(this.address, other.address) && MessagesPigeonUtils.deepEquals(this.mtu, other.mtu)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.address)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.mtu)
    return result
  }
  override fun toString(): String {
    return "BmMtuChangedEvent(address=$address, mtu=$mtu)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class BmDetachedFromEngineEvent (
  /** Carries no information — pigeon requires data classes to have a field. */
  val unused: Boolean? = null
) : BmEvent()
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): BmDetachedFromEngineEvent {
      val unused = pigeonVar_list[0] as Boolean?
      return BmDetachedFromEngineEvent(unused)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      unused,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as BmDetachedFromEngineEvent
    return MessagesPigeonUtils.deepEquals(this.unused, other.unused)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.unused)
    return result
  }
  override fun toString(): String {
    return "BmDetachedFromEngineEvent(unused=$unused)"
  }
}
private open class MessagesPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          BmAdapterStateEnum.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          BmConnectionStateEnum.ofRaw(it.toInt())
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          BmWriteType.ofRaw(it.toInt())
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          BmConnectionPriorityEnum.ofRaw(it.toInt())
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          BmBondStateEnum.ofRaw(it.toInt())
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          LogLevel.ofRaw(it.toInt())
        }
      }
      135.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          BluebirdErrorCode.ofRaw(it.toInt())
        }
      }
      136.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          BmAttributeId.fromList(it)
        }
      }
      137.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          BmServiceRef.fromList(it)
        }
      }
      138.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          BmCharacteristicRef.fromList(it)
        }
      }
      139.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          BmDescriptorRef.fromList(it)
        }
      }
      140.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          BmMsdFilter.fromList(it)
        }
      }
      141.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          BmServiceDataFilter.fromList(it)
        }
      }
      142.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          BmScanSettings.fromList(it)
        }
      }
      143.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          BmScanAdvertisement.fromList(it)
        }
      }
      144.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          BmBluetoothDevice.fromList(it)
        }
      }
      145.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          BmBluetoothService.fromList(it)
        }
      }
      146.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          BmBluetoothCharacteristic.fromList(it)
        }
      }
      147.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          BmBluetoothDescriptor.fromList(it)
        }
      }
      148.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          BmCharacteristicProperties.fromList(it)
        }
      }
      149.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          BmPhySupport.fromList(it)
        }
      }
      150.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          BmAdapterStateEvent.fromList(it)
        }
      }
      151.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          BmScanAdvertisementsEvent.fromList(it)
        }
      }
      152.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          BmScanFailedEvent.fromList(it)
        }
      }
      153.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          BmConnectionStateEvent.fromList(it)
        }
      }
      154.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          BmCharacteristicNotificationEvent.fromList(it)
        }
      }
      155.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          BmBondStateEvent.fromList(it)
        }
      }
      156.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          BmNameChangedEvent.fromList(it)
        }
      }
      157.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          BmServicesResetEvent.fromList(it)
        }
      }
      158.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          BmMtuChangedEvent.fromList(it)
        }
      }
      159.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          BmDetachedFromEngineEvent.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is BmAdapterStateEnum -> {
        stream.write(129)
        writeValue(stream, value.raw.toLong())
      }
      is BmConnectionStateEnum -> {
        stream.write(130)
        writeValue(stream, value.raw.toLong())
      }
      is BmWriteType -> {
        stream.write(131)
        writeValue(stream, value.raw.toLong())
      }
      is BmConnectionPriorityEnum -> {
        stream.write(132)
        writeValue(stream, value.raw.toLong())
      }
      is BmBondStateEnum -> {
        stream.write(133)
        writeValue(stream, value.raw.toLong())
      }
      is LogLevel -> {
        stream.write(134)
        writeValue(stream, value.raw.toLong())
      }
      is BluebirdErrorCode -> {
        stream.write(135)
        writeValue(stream, value.raw.toLong())
      }
      is BmAttributeId -> {
        stream.write(136)
        writeValue(stream, value.toList())
      }
      is BmServiceRef -> {
        stream.write(137)
        writeValue(stream, value.toList())
      }
      is BmCharacteristicRef -> {
        stream.write(138)
        writeValue(stream, value.toList())
      }
      is BmDescriptorRef -> {
        stream.write(139)
        writeValue(stream, value.toList())
      }
      is BmMsdFilter -> {
        stream.write(140)
        writeValue(stream, value.toList())
      }
      is BmServiceDataFilter -> {
        stream.write(141)
        writeValue(stream, value.toList())
      }
      is BmScanSettings -> {
        stream.write(142)
        writeValue(stream, value.toList())
      }
      is BmScanAdvertisement -> {
        stream.write(143)
        writeValue(stream, value.toList())
      }
      is BmBluetoothDevice -> {
        stream.write(144)
        writeValue(stream, value.toList())
      }
      is BmBluetoothService -> {
        stream.write(145)
        writeValue(stream, value.toList())
      }
      is BmBluetoothCharacteristic -> {
        stream.write(146)
        writeValue(stream, value.toList())
      }
      is BmBluetoothDescriptor -> {
        stream.write(147)
        writeValue(stream, value.toList())
      }
      is BmCharacteristicProperties -> {
        stream.write(148)
        writeValue(stream, value.toList())
      }
      is BmPhySupport -> {
        stream.write(149)
        writeValue(stream, value.toList())
      }
      is BmAdapterStateEvent -> {
        stream.write(150)
        writeValue(stream, value.toList())
      }
      is BmScanAdvertisementsEvent -> {
        stream.write(151)
        writeValue(stream, value.toList())
      }
      is BmScanFailedEvent -> {
        stream.write(152)
        writeValue(stream, value.toList())
      }
      is BmConnectionStateEvent -> {
        stream.write(153)
        writeValue(stream, value.toList())
      }
      is BmCharacteristicNotificationEvent -> {
        stream.write(154)
        writeValue(stream, value.toList())
      }
      is BmBondStateEvent -> {
        stream.write(155)
        writeValue(stream, value.toList())
      }
      is BmNameChangedEvent -> {
        stream.write(156)
        writeValue(stream, value.toList())
      }
      is BmServicesResetEvent -> {
        stream.write(157)
        writeValue(stream, value.toList())
      }
      is BmMtuChangedEvent -> {
        stream.write(158)
        writeValue(stream, value.toList())
      }
      is BmDetachedFromEngineEvent -> {
        stream.write(159)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

val MessagesPigeonMethodCodec = StandardMethodCodec(MessagesPigeonCodec())



private class MessagesPigeonStreamHandler<T>(
    val wrapper: MessagesPigeonEventChannelWrapper<T>
) : EventChannel.StreamHandler {
  var pigeonSink: PigeonEventSink<T>? = null

  override fun onListen(p0: Any?, sink: EventChannel.EventSink) {
    pigeonSink = PigeonEventSink<T>(sink)
    wrapper.onListen(p0, pigeonSink!!)
  }

  override fun onCancel(p0: Any?) {
    pigeonSink = null
    wrapper.onCancel(p0)
  }
}

interface MessagesPigeonEventChannelWrapper<T> {
  open fun onListen(p0: Any?, sink: PigeonEventSink<T>) {}

  open fun onCancel(p0: Any?) {}
}

class PigeonEventSink<T>(private val sink: EventChannel.EventSink) {
  fun success(value: T) {
    sink.success(value)
  }

  fun error(errorCode: String, errorMessage: String?, errorDetails: Any?) {
    sink.error(errorCode, errorMessage, errorDetails)
  }

  fun endOfStream() {
    sink.endOfStream()
  }
}
      
abstract class NativeEventsStreamHandler : MessagesPigeonEventChannelWrapper<BmEvent> {
  companion object {
    fun register(messenger: BinaryMessenger, streamHandler: NativeEventsStreamHandler, instanceName: String = "") {
      var channelName: String = "dev.flutter.pigeon.bluebird.BluebirdEventChannelApi.nativeEvents"
      if (instanceName.isNotEmpty()) {
        channelName += ".$instanceName"
      }
      val internalStreamHandler = MessagesPigeonStreamHandler<BmEvent>(streamHandler)
      EventChannel(messenger, channelName, MessagesPigeonMethodCodec).setStreamHandler(internalStreamHandler)
    }
  }
// Implement methods from MessagesPigeonEventChannelWrapper
override fun onListen(p0: Any?, sink: PigeonEventSink<BmEvent>) {}

override fun onCancel(p0: Any?) {}
}
      
/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface BluebirdHostApi {
  /**
   * Hot-restart handshake: disconnects and closes everything, returns the
   * number of devices still closing.
   */
  fun flutterRestart(): Long
  fun connectedCount(): Long
  fun setLogLevel(level: LogLevel)
  fun setOptions(showPowerAlert: Boolean, restoreState: Boolean)
  fun isSupported(): Boolean
  /** @async: may need to request runtime permissions before answering. */
  fun getAdapterName(callback: (Result<String>) -> Unit)
  fun getAdapterState(): BmAdapterStateEnum
  /** Android: shows the enable-bluetooth dialog; completes with user consent. */
  fun turnOn(callback: (Result<Boolean>) -> Unit)
  fun turnOff(callback: (Result<Boolean>) -> Unit)
  fun startScan(settings: BmScanSettings, callback: (Result<Unit>) -> Unit)
  fun stopScan()
  fun getSystemDevices(withServices: List<String>, callback: (Result<List<BmBluetoothDevice>>) -> Unit)
  fun getBondedDevices(callback: (Result<List<BmBluetoothDevice>>) -> Unit)
  fun connect(address: String, callback: (Result<Unit>) -> Unit)
  fun disconnect(address: String, callback: (Result<Unit>) -> Unit)
  fun discoverServices(address: String, callback: (Result<List<BmBluetoothService>>) -> Unit)
  fun readCharacteristic(address: String, characteristic: BmCharacteristicRef, callback: (Result<ByteArray>) -> Unit)
  fun writeCharacteristic(address: String, characteristic: BmCharacteristicRef, writeType: BmWriteType, allowLongWrite: Boolean, value: ByteArray, callback: (Result<Unit>) -> Unit)
  fun readDescriptor(address: String, descriptor: BmDescriptorRef, callback: (Result<ByteArray>) -> Unit)
  fun writeDescriptor(address: String, descriptor: BmDescriptorRef, value: ByteArray, callback: (Result<Unit>) -> Unit)
  /** Completes after the CCCD write confirms (or immediately if no CCCD). */
  fun setNotifyValue(address: String, characteristic: BmCharacteristicRef, forceIndications: Boolean, enable: Boolean, callback: (Result<Boolean>) -> Unit)
  fun requestMtu(address: String, mtu: Long, callback: (Result<Long>) -> Unit)
  fun readRssi(address: String, callback: (Result<Long>) -> Unit)
  fun requestConnectionPriority(address: String, connectionPriority: BmConnectionPriorityEnum)
  fun getPhySupport(): BmPhySupport
  fun setPreferredPhy(address: String, txPhy: Long, rxPhy: Long, phyOptions: Long, callback: (Result<Unit>) -> Unit)
  fun getBondState(address: String): BmBondStateEnum
  fun createBond(address: String, pin: ByteArray?, callback: (Result<Boolean>) -> Unit)
  fun removeBond(address: String, callback: (Result<Boolean>) -> Unit)
  fun clearGattCache(address: String, callback: (Result<Unit>) -> Unit)

  companion object {
    /** The codec used by BluebirdHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
    /** Sets up an instance of `BluebirdHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: BluebirdHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.bluebird.BluebirdHostApi.flutterRestart$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.flutterRestart())
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.bluebird.BluebirdHostApi.connectedCount$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.connectedCount())
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.bluebird.BluebirdHostApi.setLogLevel$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val levelArg = args[0] as LogLevel
            val wrapped: List<Any?> = try {
              api.setLogLevel(levelArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.bluebird.BluebirdHostApi.setOptions$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val showPowerAlertArg = args[0] as Boolean
            val restoreStateArg = args[1] as Boolean
            val wrapped: List<Any?> = try {
              api.setOptions(showPowerAlertArg, restoreStateArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.bluebird.BluebirdHostApi.isSupported$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.isSupported())
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.bluebird.BluebirdHostApi.getAdapterName$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.getAdapterName{ result: Result<String> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.bluebird.BluebirdHostApi.getAdapterState$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getAdapterState())
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.bluebird.BluebirdHostApi.turnOn$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.turnOn{ result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.bluebird.BluebirdHostApi.turnOff$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.turnOff{ result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.bluebird.BluebirdHostApi.startScan$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val settingsArg = args[0] as BmScanSettings
            api.startScan(settingsArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                reply.reply(MessagesPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.bluebird.BluebirdHostApi.stopScan$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.stopScan()
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.bluebird.BluebirdHostApi.getSystemDevices$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val withServicesArg = args[0] as List<String>
            api.getSystemDevices(withServicesArg) { result: Result<List<BmBluetoothDevice>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.bluebird.BluebirdHostApi.getBondedDevices$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.getBondedDevices{ result: Result<List<BmBluetoothDevice>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.bluebird.BluebirdHostApi.connect$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val addressArg = args[0] as String
            api.connect(addressArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                reply.reply(MessagesPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.bluebird.BluebirdHostApi.disconnect$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val addressArg = args[0] as String
            api.disconnect(addressArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                reply.reply(MessagesPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.bluebird.BluebirdHostApi.discoverServices$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val addressArg = args[0] as String
            api.discoverServices(addressArg) { result: Result<List<BmBluetoothService>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.bluebird.BluebirdHostApi.readCharacteristic$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val addressArg = args[0] as String
            val characteristicArg = args[1] as BmCharacteristicRef
            api.readCharacteristic(addressArg, characteristicArg) { result: Result<ByteArray> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.bluebird.BluebirdHostApi.writeCharacteristic$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val addressArg = args[0] as String
            val characteristicArg = args[1] as BmCharacteristicRef
            val writeTypeArg = args[2] as BmWriteType
            val allowLongWriteArg = args[3] as Boolean
            val valueArg = args[4] as ByteArray
            api.writeCharacteristic(addressArg, characteristicArg, writeTypeArg, allowLongWriteArg, valueArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                reply.reply(MessagesPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.bluebird.BluebirdHostApi.readDescriptor$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val addressArg = args[0] as String
            val descriptorArg = args[1] as BmDescriptorRef
            api.readDescriptor(addressArg, descriptorArg) { result: Result<ByteArray> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.bluebird.BluebirdHostApi.writeDescriptor$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val addressArg = args[0] as String
            val descriptorArg = args[1] as BmDescriptorRef
            val valueArg = args[2] as ByteArray
            api.writeDescriptor(addressArg, descriptorArg, valueArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                reply.reply(MessagesPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.bluebird.BluebirdHostApi.setNotifyValue$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val addressArg = args[0] as String
            val characteristicArg = args[1] as BmCharacteristicRef
            val forceIndicationsArg = args[2] as Boolean
            val enableArg = args[3] as Boolean
            api.setNotifyValue(addressArg, characteristicArg, forceIndicationsArg, enableArg) { result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.bluebird.BluebirdHostApi.requestMtu$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val addressArg = args[0] as String
            val mtuArg = args[1] as Long
            api.requestMtu(addressArg, mtuArg) { result: Result<Long> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.bluebird.BluebirdHostApi.readRssi$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val addressArg = args[0] as String
            api.readRssi(addressArg) { result: Result<Long> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.bluebird.BluebirdHostApi.requestConnectionPriority$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val addressArg = args[0] as String
            val connectionPriorityArg = args[1] as BmConnectionPriorityEnum
            val wrapped: List<Any?> = try {
              api.requestConnectionPriority(addressArg, connectionPriorityArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.bluebird.BluebirdHostApi.getPhySupport$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getPhySupport())
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.bluebird.BluebirdHostApi.setPreferredPhy$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val addressArg = args[0] as String
            val txPhyArg = args[1] as Long
            val rxPhyArg = args[2] as Long
            val phyOptionsArg = args[3] as Long
            api.setPreferredPhy(addressArg, txPhyArg, rxPhyArg, phyOptionsArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                reply.reply(MessagesPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.bluebird.BluebirdHostApi.getBondState$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val addressArg = args[0] as String
            val wrapped: List<Any?> = try {
              listOf(api.getBondState(addressArg))
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.bluebird.BluebirdHostApi.createBond$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val addressArg = args[0] as String
            val pinArg = args[1] as ByteArray?
            api.createBond(addressArg, pinArg) { result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.bluebird.BluebirdHostApi.removeBond$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val addressArg = args[0] as String
            api.removeBond(addressArg) { result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.bluebird.BluebirdHostApi.clearGattCache$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val addressArg = args[0] as String
            api.clearGattCache(addressArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                reply.reply(MessagesPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
