// GENERATED FILE — do not edit by hand.
// Regenerate with: dart run tool/gen_assigned_numbers.dart
//
// Bluetooth SIG 16-bit UUID registries: the assigned number → name tables
// behind `Uuid.assignedName` in `../assigned_numbers.dart`.
//
// Source: https://bitbucket.org/bluetooth-SIG/public (1415ddd9db5770dd21ecbe53173fbfc09e2943b6, 2026-08-13)
//         assigned_numbers/uuids/service_uuids.yaml
//         assigned_numbers/uuids/characteristic_uuids.yaml
//         assigned_numbers/uuids/descriptors.yaml
//         assigned_numbers/uuids/declarations.yaml
//         assigned_numbers/uuids/service_class.yaml
//         assigned_numbers/uuids/member_uuids.yaml
//         assigned_numbers/uuids/sdo_uuids.yaml

/// GATT service UUIDs (`0x18xx`).
const Map<int, String> serviceUuidNames = {
  0x1800: 'GAP',
  0x1801: 'GATT',
  0x1802: 'Immediate Alert',
  0x1803: 'Link Loss',
  0x1804: 'Tx Power',
  0x1805: 'Current Time',
  0x1806: 'Reference Time Update',
  0x1807: 'Next DST Change',
  0x1808: 'Glucose',
  0x1809: 'Health Thermometer',
  0x180A: 'Device Information',
  0x180D: 'Heart Rate',
  0x180E: 'Phone Alert Status',
  0x180F: 'Battery',
  0x1810: 'Blood Pressure',
  0x1811: 'Alert Notification',
  0x1812: 'Human Interface Device',
  0x1813: 'Scan Parameters',
  0x1814: 'Running Speed and Cadence',
  0x1815: 'Automation IO',
  0x1816: 'Cycling Speed and Cadence',
  0x1818: 'Cycling Power',
  0x1819: 'Location and Navigation',
  0x181A: 'Environmental Sensing',
  0x181B: 'Body Composition',
  0x181C: 'User Data',
  0x181D: 'Weight Scale',
  0x181E: 'Bond Management',
  0x181F: 'Continuous Glucose Monitoring',
  0x1820: 'Internet Protocol Support',
  0x1821: 'Indoor Positioning',
  0x1822: 'Pulse Oximeter',
  0x1823: 'HTTP Proxy',
  0x1824: 'Transport Discovery',
  0x1825: 'Object Transfer',
  0x1826: 'Fitness Machine',
  0x1827: 'Mesh Provisioning',
  0x1828: 'Mesh Proxy',
  0x1829: 'Reconnection Configuration',
  0x183A: 'Insulin Delivery',
  0x183B: 'Binary Sensor',
  0x183C: 'Emergency Configuration',
  0x183D: 'Authorization Control',
  0x183E: 'Physical Activity Monitor',
  0x183F: 'Elapsed Time',
  0x1840: 'Generic Health Sensor',
  0x1843: 'Audio Input Control',
  0x1844: 'Volume Control',
  0x1845: 'Volume Offset Control',
  0x1846: 'Coordinated Set Identification',
  0x1847: 'Device Time',
  0x1848: 'Media Control',
  0x1849: 'Generic Media Control',
  0x184A: 'Constant Tone Extension',
  0x184B: 'Telephone Bearer',
  0x184C: 'Generic Telephone Bearer',
  0x184D: 'Microphone Control',
  0x184E: 'Audio Stream Control',
  0x184F: 'Broadcast Audio Scan',
  0x1850: 'Published Audio Capabilities',
  0x1851: 'Basic Audio Announcement',
  0x1852: 'Broadcast Audio Announcement',
  0x1853: 'Common Audio',
  0x1854: 'Hearing Access',
  0x1855: 'Telephony and Media Audio',
  0x1856: 'Public Broadcast Announcement',
  0x1857: 'Electronic Shelf Label',
  0x1858: 'Gaming Audio',
  0x1859: 'Mesh Proxy Solicitation',
  0x185A: 'Industrial Measurement Device',
  0x185B: 'Ranging',
  0x185C: 'HID ISO',
  0x185D: 'Cookware',
  0x185E: 'Voice Assistant',
  0x185F: 'Generic Voice Assistant',
  0x1860: 'Tire Pressure Monitoring System',
};

/// GATT characteristic UUIDs (`0x2Axx`).
const Map<int, String> characteristicUuidNames = {
  0x2A00: 'Device Name',
  0x2A01: 'Appearance',
  0x2A02: 'Peripheral Privacy Flag',
  0x2A03: 'Reconnection Address',
  0x2A04: 'Peripheral Preferred Connection Parameters',
  0x2A05: 'Service Changed',
  0x2A06: 'Alert Level',
  0x2A07: 'Tx Power Level',
  0x2A08: 'Date Time',
  0x2A09: 'Day of Week',
  0x2A0A: 'Day Date Time',
  0x2A0C: 'Exact Time 256',
  0x2A0D: 'DST Offset',
  0x2A0E: 'Time Zone',
  0x2A0F: 'Local Time Information',
  0x2A11: 'Time with DST',
  0x2A12: 'Time Accuracy',
  0x2A13: 'Time Source',
  0x2A14: 'Reference Time Information',
  0x2A16: 'Time Update Control Point',
  0x2A17: 'Time Update State',
  0x2A18: 'Glucose Measurement',
  0x2A19: 'Battery Level',
  0x2A1C: 'Temperature Measurement',
  0x2A1D: 'Temperature Type',
  0x2A1E: 'Intermediate Temperature',
  0x2A21: 'Measurement Interval',
  0x2A22: 'Boot Keyboard Input Report',
  0x2A23: 'System ID',
  0x2A24: 'Model Number String',
  0x2A25: 'Serial Number String',
  0x2A26: 'Firmware Revision String',
  0x2A27: 'Hardware Revision String',
  0x2A28: 'Software Revision String',
  0x2A29: 'Manufacturer Name String',
  0x2A2A: 'IEEE 11073-20601 Regulatory Certification Data List',
  0x2A2B: 'Current Time',
  0x2A2C: 'Magnetic Declination',
  0x2A31: 'Scan Refresh',
  0x2A32: 'Boot Keyboard Output Report',
  0x2A33: 'Boot Mouse Input Report',
  0x2A34: 'Glucose Measurement Context',
  0x2A35: 'Blood Pressure Measurement',
  0x2A36: 'Intermediate Cuff Pressure',
  0x2A37: 'Heart Rate Measurement',
  0x2A38: 'Body Sensor Location',
  0x2A39: 'Heart Rate Control Point',
  0x2A3F: 'Alert Status',
  0x2A40: 'Ringer Control Point',
  0x2A41: 'Ringer Setting',
  0x2A42: 'Alert Category ID Bit Mask',
  0x2A43: 'Alert Category ID',
  0x2A44: 'Alert Notification Control Point',
  0x2A45: 'Unread Alert Status',
  0x2A46: 'New Alert',
  0x2A47: 'Supported New Alert Category',
  0x2A48: 'Supported Unread Alert Category',
  0x2A49: 'Blood Pressure Feature',
  0x2A4A: 'HID Information',
  0x2A4B: 'Report Map',
  0x2A4C: 'HID Control Point',
  0x2A4D: 'Report',
  0x2A4E: 'Protocol Mode',
  0x2A4F: 'Scan Interval Window',
  0x2A50: 'PnP ID',
  0x2A51: 'Glucose Feature',
  0x2A52: 'Record Access Control Point',
  0x2A53: 'RSC Measurement',
  0x2A54: 'RSC Feature',
  0x2A55: 'SC Control Point',
  0x2A5A: 'Aggregate',
  0x2A5B: 'CSC Measurement',
  0x2A5C: 'CSC Feature',
  0x2A5D: 'Sensor Location',
  0x2A5E: 'PLX Spot-Check Measurement',
  0x2A5F: 'PLX Continuous Measurement',
  0x2A60: 'PLX Features',
  0x2A63: 'Cycling Power Measurement',
  0x2A64: 'Cycling Power Vector',
  0x2A65: 'Cycling Power Feature',
  0x2A66: 'Cycling Power Control Point',
  0x2A67: 'Location and Speed',
  0x2A68: 'Navigation',
  0x2A69: 'Position Quality',
  0x2A6A: 'LN Feature',
  0x2A6B: 'LN Control Point',
  0x2A6C: 'Elevation',
  0x2A6D: 'Pressure',
  0x2A6E: 'Temperature',
  0x2A6F: 'Humidity',
  0x2A70: 'True Wind Speed',
  0x2A71: 'True Wind Direction',
  0x2A72: 'Apparent Wind Speed',
  0x2A73: 'Apparent Wind Direction',
  0x2A74: 'Gust Factor',
  0x2A75: 'Pollen Concentration',
  0x2A76: 'UV Index',
  0x2A77: 'Irradiance',
  0x2A78: 'Rainfall',
  0x2A79: 'Wind Chill',
  0x2A7A: 'Heat Index',
  0x2A7B: 'Dew Point',
  0x2A7D: 'Descriptor Value Changed',
  0x2A7E: 'Aerobic Heart Rate Lower Limit',
  0x2A7F: 'Aerobic Threshold',
  0x2A80: 'Age',
  0x2A81: 'Anaerobic Heart Rate Lower Limit',
  0x2A82: 'Anaerobic Heart Rate Upper Limit',
  0x2A83: 'Anaerobic Threshold',
  0x2A84: 'Aerobic Heart Rate Upper Limit',
  0x2A85: 'Date of Birth',
  0x2A86: 'Date of Threshold Assessment',
  0x2A87: 'Email Address',
  0x2A88: 'Fat Burn Heart Rate Lower Limit',
  0x2A89: 'Fat Burn Heart Rate Upper Limit',
  0x2A8A: 'First Name',
  0x2A8B: 'Five Zone Heart Rate Limits',
  0x2A8C: 'Gender',
  0x2A8D: 'Heart Rate Max',
  0x2A8E: 'Height',
  0x2A8F: 'Hip Circumference',
  0x2A90: 'Last Name',
  0x2A91: 'Maximum Recommended Heart Rate',
  0x2A92: 'Resting Heart Rate',
  0x2A93: 'Sport Type for Aerobic and Anaerobic Thresholds',
  0x2A94: 'Three Zone Heart Rate Limits',
  0x2A95: 'Two Zone Heart Rate Limits',
  0x2A96: 'VO2 Max',
  0x2A97: 'Waist Circumference',
  0x2A98: 'Weight',
  0x2A99: 'Database Change Increment',
  0x2A9A: 'User Index',
  0x2A9B: 'Body Composition Feature',
  0x2A9C: 'Body Composition Measurement',
  0x2A9D: 'Weight Measurement',
  0x2A9E: 'Weight Scale Feature',
  0x2A9F: 'User Control Point',
  0x2AA0: 'Magnetic Flux Density - 2D',
  0x2AA1: 'Magnetic Flux Density - 3D',
  0x2AA2: 'Language',
  0x2AA3: 'Barometric Pressure Trend',
  0x2AA4: 'Bond Management Control Point',
  0x2AA5: 'Bond Management Feature',
  0x2AA6: 'Central Address Resolution',
  0x2AA7: 'CGM Measurement',
  0x2AA8: 'CGM Feature',
  0x2AA9: 'CGM Status',
  0x2AAA: 'CGM Session Start Time',
  0x2AAB: 'CGM Session Run Time',
  0x2AAC: 'CGM Specific Ops Control Point',
  0x2AAD: 'Indoor Positioning Configuration',
  0x2AAE: 'Latitude',
  0x2AAF: 'Longitude',
  0x2AB0: 'Local North Coordinate',
  0x2AB1: 'Local East Coordinate',
  0x2AB2: 'Floor Number',
  0x2AB3: 'Altitude',
  0x2AB4: 'Uncertainty',
  0x2AB5: 'Location Name',
  0x2AB6: 'URI',
  0x2AB7: 'HTTP Headers',
  0x2AB8: 'HTTP Status Code',
  0x2AB9: 'HTTP Entity Body',
  0x2ABA: 'HTTP Control Point',
  0x2ABB: 'HTTPS Security',
  0x2ABC: 'TDS Control Point',
  0x2ABD: 'OTS Feature',
  0x2ABE: 'Object Name',
  0x2ABF: 'Object Type',
  0x2AC0: 'Object Size',
  0x2AC1: 'Object First-Created',
  0x2AC2: 'Object Last-Modified',
  0x2AC3: 'Object ID',
  0x2AC4: 'Object Properties',
  0x2AC5: 'Object Action Control Point',
  0x2AC6: 'Object List Control Point',
  0x2AC7: 'Object List Filter',
  0x2AC8: 'Object Changed',
  0x2AC9: 'Resolvable Private Address Only',
  0x2ACC: 'Fitness Machine Feature',
  0x2ACD: 'Treadmill Data',
  0x2ACE: 'Cross Trainer Data',
  0x2ACF: 'Step Climber Data',
  0x2AD0: 'Stair Climber Data',
  0x2AD1: 'Rower Data',
  0x2AD2: 'Indoor Bike Data',
  0x2AD3: 'Training Status',
  0x2AD4: 'Supported Speed Range',
  0x2AD5: 'Supported Inclination Range',
  0x2AD6: 'Supported Resistance Level Range',
  0x2AD7: 'Supported Heart Rate Range',
  0x2AD8: 'Supported Power Range',
  0x2AD9: 'Fitness Machine Control Point',
  0x2ADA: 'Fitness Machine Status',
  0x2ADB: 'Mesh Provisioning Data In',
  0x2ADC: 'Mesh Provisioning Data Out',
  0x2ADD: 'Mesh Proxy Data In',
  0x2ADE: 'Mesh Proxy Data Out',
  0x2AE0: 'Average Current',
  0x2AE1: 'Average Voltage',
  0x2AE2: 'Boolean',
  0x2AE3: 'Chromatic Distance from Planckian',
  0x2AE4: 'Chromaticity Coordinates',
  0x2AE5: 'Chromaticity in CCT and Duv Values',
  0x2AE6: 'Chromaticity Tolerance',
  0x2AE7: 'CIE 13.3-1995 Color Rendering Index',
  0x2AE8: 'Coefficient',
  0x2AE9: 'Correlated Color Temperature',
  0x2AEA: 'Count 16',
  0x2AEB: 'Count 24',
  0x2AEC: 'Country Code',
  0x2AED: 'Date UTC',
  0x2AEE: 'Electric Current',
  0x2AEF: 'Electric Current Range',
  0x2AF0: 'Electric Current Specification',
  0x2AF1: 'Electric Current Statistics',
  0x2AF2: 'Energy',
  0x2AF3: 'Energy in a Period of Day',
  0x2AF4: 'Event Statistics',
  0x2AF5: 'Fixed String 16',
  0x2AF6: 'Fixed String 24',
  0x2AF7: 'Fixed String 36',
  0x2AF8: 'Fixed String 8',
  0x2AF9: 'Generic Level',
  0x2AFA: 'Global Trade Item Number',
  0x2AFB: 'Illuminance',
  0x2AFC: 'Luminous Efficacy',
  0x2AFD: 'Luminous Energy',
  0x2AFE: 'Luminous Exposure',
  0x2AFF: 'Luminous Flux',
  0x2B00: 'Luminous Flux Range',
  0x2B01: 'Luminous Intensity',
  0x2B02: 'Mass Flow',
  0x2B03: 'Perceived Lightness',
  0x2B04: 'Percentage 8',
  0x2B05: 'Power',
  0x2B06: 'Power Specification',
  0x2B07: 'Relative Runtime in a Current Range',
  0x2B08: 'Relative Runtime in a Generic Level Range',
  0x2B09: 'Relative Value in a Voltage Range',
  0x2B0A: 'Relative Value in an Illuminance Range',
  0x2B0B: 'Relative Value in a Period of Day',
  0x2B0C: 'Relative Value in a Temperature Range',
  0x2B0D: 'Temperature 8',
  0x2B0E: 'Temperature 8 in a Period of Day',
  0x2B0F: 'Temperature 8 Statistics',
  0x2B10: 'Temperature Range',
  0x2B11: 'Temperature Statistics',
  0x2B12: 'Time Decihour 8',
  0x2B13: 'Time Exponential 8',
  0x2B14: 'Time Hour 24',
  0x2B15: 'Time Millisecond 24',
  0x2B16: 'Time Second 16',
  0x2B17: 'Time Second 8',
  0x2B18: 'Voltage',
  0x2B19: 'Voltage Specification',
  0x2B1A: 'Voltage Statistics',
  0x2B1B: 'Volume Flow',
  0x2B1C: 'Chromaticity Coordinate',
  0x2B1D: 'RC Feature',
  0x2B1E: 'RC Settings',
  0x2B1F: 'Reconnection Configuration Control Point',
  0x2B20: 'IDD Status Changed',
  0x2B21: 'IDD Status',
  0x2B22: 'IDD Annunciation Status',
  0x2B23: 'IDD Features',
  0x2B24: 'IDD Status Reader Control Point',
  0x2B25: 'IDD Command Control Point',
  0x2B26: 'IDD Command Data',
  0x2B27: 'IDD Record Access Control Point',
  0x2B28: 'IDD History Data',
  0x2B29: 'Client Supported Features',
  0x2B2A: 'Database Hash',
  0x2B2B: 'BSS Control Point',
  0x2B2C: 'BSS Response',
  0x2B2D: 'Emergency ID',
  0x2B2E: 'Emergency Text',
  0x2B2F: 'ACS Status',
  0x2B30: 'ACS Data In',
  0x2B31: 'ACS Data Out Notify',
  0x2B32: 'ACS Data Out Indicate',
  0x2B33: 'ACS Control Point',
  0x2B34: 'Enhanced Blood Pressure Measurement',
  0x2B35: 'Enhanced Intermediate Cuff Pressure',
  0x2B36: 'Blood Pressure Record',
  0x2B37: 'Registered User',
  0x2B38: 'BR-EDR Handover Data',
  0x2B39: 'Bluetooth SIG Data',
  0x2B3A: 'Server Supported Features',
  0x2B3B: 'Physical Activity Monitor Features',
  0x2B3C: 'General Activity Instantaneous Data',
  0x2B3D: 'General Activity Summary Data',
  0x2B3E: 'CardioRespiratory Activity Instantaneous Data',
  0x2B3F: 'CardioRespiratory Activity Summary Data',
  0x2B40: 'Step Counter Activity Summary Data',
  0x2B41: 'Sleep Activity Instantaneous Data',
  0x2B42: 'Sleep Activity Summary Data',
  0x2B43: 'Physical Activity Monitor Control Point',
  0x2B44: 'Physical Activity Current Session',
  0x2B45: 'Physical Activity Session Descriptor',
  0x2B46: 'Preferred Units',
  0x2B47: 'High Resolution Height',
  0x2B48: 'Middle Name',
  0x2B49: 'Stride Length',
  0x2B4A: 'Handedness',
  0x2B4B: 'Device Wearing Position',
  0x2B4C: 'Four Zone Heart Rate Limits',
  0x2B4D: 'High Intensity Exercise Threshold',
  0x2B4E: 'Activity Goal',
  0x2B4F: 'Sedentary Interval Notification',
  0x2B50: 'Caloric Intake',
  0x2B51: 'TMAP Role',
  0x2B77: 'Audio Input State',
  0x2B78: 'Gain Settings Attribute',
  0x2B79: 'Audio Input Type',
  0x2B7A: 'Audio Input Status',
  0x2B7B: 'Audio Input Control Point',
  0x2B7C: 'Audio Input Description',
  0x2B7D: 'Volume State',
  0x2B7E: 'Volume Control Point',
  0x2B7F: 'Volume Flags',
  0x2B80: 'Volume Offset State',
  0x2B81: 'Audio Location',
  0x2B82: 'Volume Offset Control Point',
  0x2B83: 'Audio Output Description',
  0x2B84: 'Set Identity Resolving Key',
  0x2B85: 'Coordinated Set Size',
  0x2B86: 'Set Member Lock',
  0x2B87: 'Set Member Rank',
  0x2B88: 'Encrypted Data Key Material',
  0x2B89: 'Apparent Energy 32',
  0x2B8A: 'Apparent Power',
  0x2B8B: 'Live Health Observations',
  0x2B8C: 'CO₂ Concentration',
  0x2B8D: 'Cosine of the Angle',
  0x2B8E: 'Device Time Feature',
  0x2B8F: 'Device Time Parameters',
  0x2B90: 'Device Time',
  0x2B91: 'Device Time Control Point',
  0x2B92: 'Time Change Log Data',
  0x2B93: 'Media Player Name',
  0x2B94: 'Media Player Icon Object ID',
  0x2B95: 'Media Player Icon URL',
  0x2B96: 'Track Changed',
  0x2B97: 'Track Title',
  0x2B98: 'Track Duration',
  0x2B99: 'Track Position',
  0x2B9A: 'Playback Speed',
  0x2B9B: 'Seeking Speed',
  0x2B9C: 'Current Track Segments Object ID',
  0x2B9D: 'Current Track Object ID',
  0x2B9E: 'Next Track Object ID',
  0x2B9F: 'Parent Group Object ID',
  0x2BA0: 'Current Group Object ID',
  0x2BA1: 'Playing Order',
  0x2BA2: 'Playing Orders Supported',
  0x2BA3: 'Media State',
  0x2BA4: 'Media Control Point',
  0x2BA5: 'Media Control Point Opcodes Supported',
  0x2BA6: 'Search Results Object ID',
  0x2BA7: 'Search Control Point',
  0x2BA8: 'Energy 32',
  0x2BAD: 'Constant Tone Extension Enable',
  0x2BAE: 'Advertising Constant Tone Extension Minimum Length',
  0x2BAF: 'Advertising Constant Tone Extension Minimum Transmit Count',
  0x2BB0: 'Advertising Constant Tone Extension Transmit Duration',
  0x2BB1: 'Advertising Constant Tone Extension Interval',
  0x2BB2: 'Advertising Constant Tone Extension PHY',
  0x2BB3: 'Bearer Provider Name',
  0x2BB4: 'Bearer UCI',
  0x2BB5: 'Bearer Technology',
  0x2BB6: 'Bearer URI Schemes Supported List',
  0x2BB7: 'Bearer Signal Strength',
  0x2BB8: 'Bearer Signal Strength Reporting Interval',
  0x2BB9: 'Bearer List Current Calls',
  0x2BBA: 'Content Control ID',
  0x2BBB: 'Status Flags',
  0x2BBC: 'Incoming Call Target Bearer URI',
  0x2BBD: 'Call State',
  0x2BBE: 'Call Control Point',
  0x2BBF: 'Call Control Point Optional Opcodes',
  0x2BC0: 'Termination Reason',
  0x2BC1: 'Incoming Call',
  0x2BC2: 'Call Friendly Name',
  0x2BC3: 'Mute',
  0x2BC4: 'Sink ASE',
  0x2BC5: 'Source ASE',
  0x2BC6: 'ASE Control Point',
  0x2BC7: 'Broadcast Audio Scan Control Point',
  0x2BC8: 'Broadcast Receive State',
  0x2BC9: 'Sink PAC',
  0x2BCA: 'Sink Audio Locations',
  0x2BCB: 'Source PAC',
  0x2BCC: 'Source Audio Locations',
  0x2BCD: 'Available Audio Contexts',
  0x2BCE: 'Supported Audio Contexts',
  0x2BCF: 'Ammonia Concentration',
  0x2BD0: 'Carbon Monoxide Concentration',
  0x2BD1: 'Methane Concentration',
  0x2BD2: 'Nitrogen Dioxide Concentration',
  0x2BD3: 'Non-Methane Volatile Organic Compounds Concentration',
  0x2BD4: 'Ozone Concentration',
  0x2BD5: 'Particulate Matter - PM1 Concentration',
  0x2BD6: 'Particulate Matter - PM2.5 Concentration',
  0x2BD7: 'Particulate Matter - PM10 Concentration',
  0x2BD8: 'Sulfur Dioxide Concentration',
  0x2BD9: 'Sulfur Hexafluoride Concentration',
  0x2BDA: 'Hearing Aid Features',
  0x2BDB: 'Hearing Aid Preset Control Point',
  0x2BDC: 'Active Preset Index',
  0x2BDD: 'Stored Health Observations',
  0x2BDE: 'Fixed String 64',
  0x2BDF: 'High Temperature',
  0x2BE0: 'High Voltage',
  0x2BE1: 'Light Distribution',
  0x2BE2: 'Light Output',
  0x2BE3: 'Light Source Type',
  0x2BE4: 'Noise',
  0x2BE5: 'Relative Runtime in a Correlated Color Temperature Range',
  0x2BE6: 'Time Second 32',
  0x2BE7: 'VOC Concentration',
  0x2BE8: 'Voltage Frequency',
  0x2BE9: 'Battery Critical Status',
  0x2BEA: 'Battery Health Status',
  0x2BEB: 'Battery Health Information',
  0x2BEC: 'Battery Information',
  0x2BED: 'Battery Level Status',
  0x2BEE: 'Battery Time Status',
  0x2BEF: 'Estimated Service Date',
  0x2BF0: 'Battery Energy Status',
  0x2BF1: 'Observation Schedule Changed',
  0x2BF2: 'Elapsed Time',
  0x2BF3: 'Health Sensor Features',
  0x2BF4: 'GHS Control Point',
  0x2BF5: 'LE GATT Security Levels',
  0x2BF6: 'ESL Address',
  0x2BF7: 'AP Sync Key Material',
  0x2BF8: 'ESL Response Key Material',
  0x2BF9: 'ESL Current Absolute Time',
  0x2BFA: 'ESL Display Information',
  0x2BFB: 'ESL Image Information',
  0x2BFC: 'ESL Sensor Information',
  0x2BFD: 'ESL LED Information',
  0x2BFE: 'ESL Control Point',
  0x2BFF: 'UDI for Medical Devices',
  0x2C00: 'GMAP Role',
  0x2C01: 'UGG Features',
  0x2C02: 'UGT Features',
  0x2C03: 'BGS Features',
  0x2C04: 'BGR Features',
  0x2C05: 'Percentage 8 Steps',
  0x2C06: 'Acceleration',
  0x2C07: 'Force',
  0x2C08: 'Linear Position',
  0x2C09: 'Rotational Speed',
  0x2C0A: 'Length',
  0x2C0B: 'Torque',
  0x2C0C: 'IMD Status',
  0x2C0D: 'IMDS Descriptor Value Changed',
  0x2C0E: 'First Use Date',
  0x2C0F: 'Life Cycle Data',
  0x2C10: 'Work Cycle Data',
  0x2C11: 'Service Cycle Data',
  0x2C12: 'IMD Control',
  0x2C13: 'IMD Historical Data',
  0x2C14: 'RAS Features',
  0x2C15: 'Real-time Ranging Data',
  0x2C16: 'On-demand Ranging Data',
  0x2C17: 'RAS Control Point',
  0x2C18: 'Ranging Data Ready',
  0x2C19: 'Ranging Data Overwritten',
  0x2C1A: 'Coordinated Set Name',
  0x2C1B: 'Humidity 8',
  0x2C1C: 'Illuminance 16',
  0x2C1D: 'Acceleration - 3D',
  0x2C1E: 'Precise Acceleration - 3D',
  0x2C1F: 'Acceleration Detection Status',
  0x2C20: 'Door/Window Status',
  0x2C21: 'Pushbutton Status 8',
  0x2C22: 'Contact Status 8',
  0x2C23: 'HID ISO Properties',
  0x2C24: 'LE HID Operation Mode',
  0x2C25: 'Cookware Description',
  0x2C26: 'Recipe Control',
  0x2C27: 'Recipe Parameters',
  0x2C28: 'Cooking Step Status',
  0x2C29: 'Cooking Zone Capabilities',
  0x2C2A: 'Cooking Zone Desired Cooking Conditions',
  0x2C2B: 'Cooking Zone Actual Cooking Conditions',
  0x2C2C: 'Cookware Sensor Data',
  0x2C2D: 'Cookware Sensor Aggregate',
  0x2C2E: 'Cooking Temperature',
  0x2C2F: 'Cooking Zone Perceived Power',
  0x2C30: 'Kitchen Appliance Airflow',
  0x2C31: 'Voice Assistant Name',
  0x2C32: 'Voice Assistant UUID',
  0x2C33: 'Voice Assistant Service Control Point',
  0x2C34: 'Installed Location',
  0x2C35: 'Voice Assistant Session State',
  0x2C36: 'Voice Assistant Session Flag',
  0x2C37: 'Voice Assistant Supported Languages',
  0x2C38: 'Voice Assistant Supported Features',
  0x2C39: 'HID SCI Mode',
  0x2C3A: 'HID SCI Information',
  0x2C3B: 'Tire Pressure',
  0x2C3C: 'Tire Temperature',
  0x2C3D: 'Tire Acceleration',
  0x2C3E: 'TPMS Properties',
  0x2C3F: 'TPMS Duty Cycle',
  0x2C40: 'TPMS Position',
  0x2C41: 'TPMS Signing Key',
};

/// GATT descriptor UUIDs (`0x29xx`).
const Map<int, String> descriptorUuidNames = {
  0x2900: 'Characteristic Extended Properties',
  0x2901: 'Characteristic User Description',
  0x2902: 'Client Characteristic Configuration',
  0x2903: 'Server Characteristic Configuration',
  0x2904: 'Characteristic Presentation Format',
  0x2905: 'Characteristic Aggregate Format',
  0x2906: 'Valid Range',
  0x2907: 'External Report Reference',
  0x2908: 'Report Reference',
  0x2909: 'Number of Digitals',
  0x290A: 'Value Trigger Setting',
  0x290B: 'Environmental Sensing Configuration',
  0x290C: 'Environmental Sensing Measurement',
  0x290D: 'Environmental Sensing Trigger Setting',
  0x290E: 'Time Trigger Setting',
  0x290F: 'Complete BR-EDR Transport Block Data',
  0x2910: 'Observation Schedule',
  0x2911: 'Valid Range and Accuracy',
  0x2912: 'Measurement Description',
  0x2913: 'Manufacturer Limits',
  0x2914: 'Process Tolerances',
  0x2915: 'IMD Trigger Setting',
  0x2916: 'Cooking Sensor Info',
  0x2917: 'Cooking Trigger Setting',
};

/// GATT attribute declaration UUIDs (`0x28xx`).
const Map<int, String> declarationUuidNames = {
  0x2800: 'Primary Service',
  0x2801: 'Secondary Service',
  0x2802: 'Include',
  0x2803: 'Characteristic',
};

/// Service class and profile identifiers (`0x1xxx`), used by classic Bluetooth service discovery.
const Map<int, String> serviceClassUuidNames = {
  0x1000: 'ServiceDiscoveryServerServiceClassID',
  0x1001: 'BrowseGroupDescriptorServiceClassID',
  0x1101: 'SerialPort',
  0x1102: 'LANAccessUsingPPP',
  0x1103: 'Dial-Up Networking',
  0x1104: 'IrMCSync',
  0x1105: 'OBEXObjectPush',
  0x1106: 'OBEX File Transfer',
  0x1107: 'IrMCSyncCommand',
  0x1108: 'Headset',
  0x1109: 'CordlessTelephony',
  0x110A: 'Audio Source',
  0x110B: 'Audio Sink',
  0x110C: 'A/V Remote Control Target',
  0x110D: 'Advanced Audio Distribution',
  0x110E: 'A/V Remote Control',
  0x110F: 'A/V Remote Control Controller',
  0x1110: 'Intercom',
  0x1111: 'Fax',
  0x1112: 'Headset Audio Gateway',
  0x1113: 'WAP',
  0x1114: 'WAP_CLIENT',
  0x1115: 'PANU',
  0x1116: 'NAP',
  0x1117: 'GN',
  0x1118: 'DirectPrinting',
  0x1119: 'ReferencePrinting',
  0x111A: 'Imaging',
  0x111B: 'Imaging Responder',
  0x111C: 'Imaging Automatic Archive',
  0x111D: 'Imaging Referenced Objects',
  0x111E: 'Hands-Free',
  0x111F: 'AG Hands-Free',
  0x1120: 'DirectPrintingReferencedObjectsService',
  0x1121: 'ReflectedUI',
  0x1122: 'BasicPrinting',
  0x1123: 'PrintingStatus',
  0x1124: 'HID',
  0x1125: 'HardcopyCableReplacement',
  0x1126: 'HCR_Print',
  0x1127: 'HCR_Scan',
  0x1128: 'Common_ISDN_Access',
  0x112D: 'SIM Access',
  0x112E: 'Phonebook Access Client',
  0x112F: 'Phonebook Access Server',
  0x1130: 'Phonebook Access Profile',
  0x1131: 'Headset - HS',
  0x1132: 'Message Access Server',
  0x1133: 'Message Notification Server',
  0x1134: 'Message Access Profile',
  0x1135: 'GNSS',
  0x1136: 'GNSS_Server',
  0x1137: '3D Display',
  0x1138: '3D Glasses',
  0x1139: '3D Synch Profile',
  0x113A: 'Multi Profile Specification',
  0x113B: 'MPS',
  0x113C: 'CTN Access Service',
  0x113D: 'CTN Notification Service',
  0x113E: 'Calendar Tasks and Notes Profile',
  0x1200: 'PnPInformation',
  0x1201: 'Generic Networking',
  0x1202: 'GenericFileTransfer',
  0x1203: 'Generic Audio',
  0x1204: 'GenericTelephony',
  0x1205: 'UPNP_Service',
  0x1206: 'UPNP_IP_Service',
  0x1300: 'ESDP_UPNP_IP_PAN',
  0x1301: 'ESDP_UPNP_IP_LAP',
  0x1302: 'ESDP_UPNP_L2CAP',
  0x1303: 'Video Source',
  0x1304: 'Video Sink',
  0x1305: 'Video Distribution',
  0x1400: 'HDP',
  0x1401: 'HDP Source',
  0x1402: 'HDP Sink',
};

/// Member UUIDs (`0xFCxx`–`0xFExx`) — allocated to a SIG member for their own
/// use, so the name is a company rather than a service.
const Map<int, String> memberUuidNames = {
  0xFC2A: 'Troo Corporation',
  0xFC2B: 'Elder Technologies, Inc',
  0xFC2C: 'Verkada Inc.',
  0xFC30: 'Arashi Vision Inc.',
  0xFC31: 'Ford Motor Company',
  0xFC32: 'InPlay, Inc.',
  0xFC34: 'Mitsubishi Electric Corporation',
  0xFC35: 'Metabowerke GmbH',
  0xFC36: 'PharmaSens AG',
  0xFC37: 'TANlock GmbH',
  0xFC38: 'SetPoint Medical',
  0xFC39: 'Harman International',
  0xFC3A: 'C.O.B.O. SpA',
  0xFC3B: 'BONX INC.',
  0xFC3C: 'Eforthink Technology Co., Ltd.',
  0xFC3D: 'Reelables, Inc.',
  0xFC3E: 'Google LLC',
  0xFC3F: 'Milwaukee Electric Tools',
  0xFC41: 'Yoto Limited',
  0xFC43: 'Atmosic Technologies, Inc.',
  0xFC44: 'Block, Inc.',
  0xFC45: 'Mitsubishi Electric Corporation',
  0xFC46: 'Xiaomi',
  0xFC47: 'Shanghai Ingeek Technology Co., Ltd.',
  0xFC48: 'Michelin',
  0xFC49: 'Golioth, Inc.',
  0xFC4A: 'Shenzhen Shokz Co.,Ltd.',
  0xFC4B: 'WinMagic Inc.',
  0xFC4C: 'HP Inc.',
  0xFC4D: 'Lodestar Technology Inc.',
  0xFC4E: 'Lodestar Technology Inc.',
  0xFC4F: 'WaveRF, Corp.',
  0xFC50: 'Ant Group Co., Ltd.',
  0xFC51: 'Ant Group Co., Ltd.',
  0xFC52: 'LG Electronics Inc.',
  0xFC53: 'LEGIC Identsystems AG',
  0xFC54: 'Shenzhen Yinwang Intelligent Technologies Co., Ltd.',
  0xFC55: 'BYD Company Limited',
  0xFC56: 'Google LLC',
  0xFC57: 'Ambient Life Inc.',
  0xFC58: 'Shenzhen Minew Technologies Co., Ltd.',
  0xFC59: 'Ant Group Co., Ltd.',
  0xFC5A: 'LAST LOCK INC.',
  0xFC5B: 'Time Location Systems AS',
  0xFC5C: 'PLASTIC RESEARCH AND DEVELOPMENT CORPORATION',
  0xFC5D: 'GP Acoustics International Limited',
  0xFC5E: 'KUBU SMART LIMITED',
  0xFC5F: 'PI-CRYSTAL INC.',
  0xFC60: 'Ohme Operations UK Limited',
  0xFC61: 'QIKCONNEX LLC',
  0xFC62: 'SPRiNTUS GmbH',
  0xFC63: 'Volvo Technology AB',
  0xFC64: 'Volvo Technology AB',
  0xFC65: 'Robor Electronics B.V.',
  0xFC66: 'Xiaomi Inc.',
  0xFC67: 'Guangdong Hengqin Xingtong Technology Co.,ltd.',
  0xFC68: 'RIGH, INC.',
  0xFC69: 'Harman International',
  0xFC6A: 'Sonos Inc',
  0xFC6B: 'Sonos Inc',
  0xFC6C: 'Powerstick.com',
  0xFC6D: 'MOTIVE TECHNOLOGIES, INC.',
  0xFC6E: 'stryker',
  0xFC6F: 'NextSense, Inc.',
  0xFC70: 'MOTIVE TECHNOLOGIES, INC.',
  0xFC71: 'Hive-Zox International SA',
  0xFC72: 'iodyne, LLC',
  0xFC73: 'Google LLC',
  0xFC74: 'EMBEINT INC',
  0xFC75: 'Xiaomi Inc.',
  0xFC76: 'Weber-Stephen Products LLC',
  0xFC77: 'SING SUN TECHNOLOGY (INTERNATIONAL) LIMITED',
  0xFC78: 'DHL',
  0xFC79: 'LG Electronics Inc.',
  0xFC7A: 'Outshiny India Private Limited',
  0xFC7B: 'Testo SE & Co. KGaA',
  0xFC7C: 'Motorola Mobility, LLC',
  0xFC7D: 'MML US, Inc',
  0xFC7E: 'Harman International',
  0xFC7F: 'Southco',
  0xFC80: 'TELE System Communications Pte. Ltd.',
  0xFC81: 'Axon Enterprise, Inc.',
  0xFC82: 'Zwift, Inc.',
  0xFC83: 'iHealth Labs, Inc.',
  0xFC84: 'NINGBO FOTILE KITCHENWARE CO., LTD.',
  0xFC85: 'Zhejiang Huanfu Technology Co., LTD',
  0xFC86: 'Samsara Networks, Inc',
  0xFC87: 'Samsara Networks, Inc',
  0xFC88: 'CCC del Uruguay',
  0xFC89: 'Intel Corporation',
  0xFC8A: 'Intel Corporation',
  0xFC8B: 'Kaspersky Lab Middle East FZ-LLC',
  0xFC8C: 'VusionGroup',
  0xFC8D: 'Caire Inc.',
  0xFC8E: 'Blue Iris Labs, Inc.',
  0xFC8F: 'Bose Corporation',
  0xFC90: 'Wiliot LTD.',
  0xFC91: 'Samsung Electronics Co., Ltd.',
  0xFC92: 'Furuno Electric Co., Ltd.',
  0xFC93: 'Komatsu Ltd.',
  0xFC94: 'Apple Inc.',
  0xFC95: 'Hippo Camp Software Ltd.',
  0xFC96: 'LEGO System A/S',
  0xFC97: 'Japan Display Inc.',
  0xFC98: 'Ruuvi Innovations Ltd.',
  0xFC99: 'Badger Meter',
  0xFC9A: 'Koppli AB',
  0xFC9B: 'Merry Electronics (S) Pte Ltd',
  0xFC9D: 'Lenovo (Singapore) Pte Ltd.',
  0xFC9E: 'Dell Computer Corporation',
  0xFC9F: 'Delta Development Team, Inc',
  0xFCA0: 'Apple Inc.',
  0xFCA1: 'PF SCHWEISSTECHNOLOGIE GMBH',
  0xFCA2: 'Meizu Technology Co., Ltd.',
  0xFCA3: 'Gunnebo Aktiebolag',
  0xFCA4: 'HP Inc.',
  0xFCA5: 'HAYWARD INDUSTRIES, INC.',
  0xFCA6: 'Hubble Network Inc.',
  0xFCA7: 'Hubble Network Inc.',
  0xFCA8: 'Medtronic Inc.',
  0xFCA9: 'Medtronic Inc.',
  0xFCAA: 'Spintly, Inc.',
  0xFCAB: 'IRISS INC.',
  0xFCAC: 'IRISS INC.',
  0xFCAD: 'Beijing 99help Safety Technology Co., Ltd',
  0xFCAE: 'Imagine Marketing Limited',
  0xFCAF: 'AltoBeam Inc.',
  0xFCB0: 'Ford Motor Company',
  0xFCB1: 'Google LLC',
  0xFCB2: 'Apple Inc.',
  0xFCB3: 'SWEEN',
  0xFCB4: 'OMRON HEALTHCARE Co., Ltd.',
  0xFCB5: 'OMRON HEALTHCARE Co., Ltd.',
  0xFCB6: 'OMRON HEALTHCARE Co., Ltd.',
  0xFCB7: 'T-Mobile USA',
  0xFCB8: 'Ribbiot, INC.',
  0xFCB9: 'Lumi United Technology Co., Ltd',
  0xFCBA: 'BlueID GmbH',
  0xFCBB: 'SharkNinja Operating LLC',
  0xFCBC: 'Drowsy Digital, Inc.',
  0xFCBD: 'Toshiba Corporation',
  0xFCBE: 'Musen Connect, Inc.',
  0xFCBF: 'ASSA ABLOY Opening Solutions Sweden AB',
  0xFCC0: 'Xiaomi Inc.',
  0xFCC1: 'TIMECODE SYSTEMS LIMITED',
  0xFCC2: 'Qualcomm Technologies, Inc.',
  0xFCC3: 'HP Inc.',
  0xFCC4: 'OMRON(DALIAN) CO,.LTD.',
  0xFCC5: 'OMRON(DALIAN) CO,.LTD.',
  0xFCC6: 'Wiliot LTD.',
  0xFCC7: 'PB INC.',
  0xFCC8: 'Allthenticate, Inc.',
  0xFCC9: 'SkyHawke Technologies',
  0xFCCA: 'Cosmed s.r.l.',
  0xFCCB: 'TOTO LTD.',
  0xFCCD: 'Marshall Group AB',
  0xFCCE: 'Luna Health, Inc.',
  0xFCCF: 'Google LLC',
  0xFCD0: 'Laerdal Medical AS',
  0xFCD1: 'Shenzhen Benwei Media Co.,Ltd.',
  0xFCD2: 'Allterco Robotics ltd',
  0xFCD3: 'Fisher & Paykel Healthcare',
  0xFCD4: 'OMRON HEALTHCARE',
  0xFCD5: 'Nortek Security & Control',
  0xFCD6: 'SWISSINNO SOLUTIONS AG',
  0xFCD7: 'PowerPal Pty Ltd',
  0xFCD8: 'Appex Factory S.L.',
  0xFCD9: 'Huso, INC',
  0xFCDA: 'Draeger',
  0xFCDB: 'aconno GmbH',
  0xFCDC: 'Amazon.com Services, LLC',
  0xFCDD: 'Mobilaris AB',
  0xFCDE: 'ARCTOP, INC.',
  0xFCDF: 'NIO USA, Inc.',
  0xFCE0: 'Akciju sabiedriba "SAF TEHNIKA"',
  0xFCE1: 'Sony Group Corporation',
  0xFCE2: 'Baracoda Daily Healthtech',
  0xFCE3: 'Smith & Nephew Medical Limited',
  0xFCE4: 'Samsara Networks, Inc',
  0xFCE5: 'Samsara Networks, Inc',
  0xFCE6: 'Guard RFID Solutions Inc.',
  0xFCE7: 'TKH Security B.V.',
  0xFCE8: 'ITT Industries',
  0xFCE9: 'MindRhythm, Inc.',
  0xFCEA: 'Chess Wise B.V.',
  0xFCEB: 'Avi-On',
  0xFCEC: 'Griffwerk GmbH',
  0xFCED: 'Workaround Gmbh',
  0xFCEE: 'Velentium, LLC',
  0xFCEF: 'Divesoft s.r.o.',
  0xFCF0: 'Security Enhancement Systems, LLC',
  0xFCF1: 'Google LLC',
  0xFCF2: 'Bitwards Oy',
  0xFCF3: 'Armatura LLC',
  0xFCF4: 'Allegion',
  0xFCF5: 'Trident Communication Technology, LLC',
  0xFCF6: 'The Linux Foundation',
  0xFCF7: 'Honor Device Co., Ltd.',
  0xFCF8: 'Honor Device Co., Ltd.',
  0xFCF9: 'Leupold & Stevens, Inc.',
  0xFCFA: 'Leupold & Stevens, Inc.',
  0xFCFB: 'Shenzhen Benwei Media Co., Ltd.',
  0xFCFC: 'Barrot Technology Co.,Ltd.',
  0xFCFD: 'Barrot Technology Co.,Ltd.',
  0xFCFE: 'Sonova Consumer Hearing GmbH',
  0xFCFF: '701x',
  0xFD00: 'FUTEK Advanced Sensor Technology, Inc.',
  0xFD01: 'Sanvita Medical Corporation',
  0xFD02: 'LEGO System A/S',
  0xFD03: 'Quuppa Oy',
  0xFD04: 'Shure Inc.',
  0xFD05: 'Qualcomm Technologies, Inc.',
  0xFD06: 'RACE-AI LLC',
  0xFD07: 'Swedlock AB',
  0xFD08: 'Bull Group Incorporated Company',
  0xFD09: 'Cousins and Sears LLC',
  0xFD0A: 'Luminostics, Inc.',
  0xFD0B: 'Luminostics, Inc.',
  0xFD0C: 'OSM HK Limited',
  0xFD0D: 'Blecon Ltd',
  0xFD0E: 'HerdDogg, Inc',
  0xFD0F: 'AEON MOTOR CO.,LTD.',
  0xFD10: 'AEON MOTOR CO.,LTD.',
  0xFD11: 'AEON MOTOR CO.,LTD.',
  0xFD12: 'AEON MOTOR CO.,LTD.',
  0xFD13: 'BRG Sports, Inc.',
  0xFD14: 'BRG Sports, Inc.',
  0xFD15: 'Panasonic Corporation',
  0xFD16: 'Sensitech, Inc.',
  0xFD17: 'LEGIC Identsystems AG',
  0xFD18: 'LEGIC Identsystems AG',
  0xFD19: 'Smith & Nephew Medical Limited',
  0xFD1A: 'CSIRO',
  0xFD1B: 'Helios Sports, Inc.',
  0xFD1C: 'Brady Worldwide Inc.',
  0xFD1D: 'Samsung Electronics Co., Ltd',
  0xFD1E: 'Plume Design Inc.',
  0xFD1F: '3M',
  0xFD20: 'GN Hearing A/S',
  0xFD21: 'Huawei Technologies Co., Ltd.',
  0xFD22: 'Huawei Technologies Co., Ltd.',
  0xFD23: 'DOM Sicherheitstechnik GmbH & Co. KG',
  0xFD24: 'GD Midea Air-Conditioning Equipment Co., Ltd.',
  0xFD25: 'GD Midea Air-Conditioning Equipment Co., Ltd.',
  0xFD26: 'Novo Nordisk A/S',
  0xFD27: 'Integrated Illumination Systems, Inc.',
  0xFD28: 'Julius Blum GmbH',
  0xFD29: 'Asahi Kasei Corporation',
  0xFD2A: 'Sony Corporation',
  0xFD2B: 'The Access Technologies',
  0xFD2C: 'The Access Technologies',
  0xFD2D: 'Xiaomi Inc.',
  0xFD2E: 'Bitstrata Systems Inc.',
  0xFD2F: 'Bitstrata Systems Inc.',
  0xFD30: 'Sesam Solutions BV',
  0xFD31: 'LG Electronics Inc.',
  0xFD32: 'Gemalto Holding BV',
  0xFD33: 'DashLogic, Inc.',
  0xFD34: 'Aerosens LLC.',
  0xFD35: 'Transsion Holdings Limited',
  0xFD36: 'Google LLC',
  0xFD37: 'TireCheck GmbH',
  0xFD38: 'Danfoss A/S',
  0xFD39: 'PREDIKTAS',
  0xFD3A: 'Verkada Inc.',
  0xFD3B: 'Verkada Inc.',
  0xFD3C: 'Redline Communications Inc.',
  0xFD3D: 'Woan Technology (Shenzhen) Co., Ltd.',
  0xFD3E: 'Pure Watercraft, inc.',
  0xFD3F: 'Cognosos, Inc',
  0xFD40: 'Beflex Inc.',
  0xFD41: 'Amazon Lab126',
  0xFD42: 'Globe (Jiangsu) Co.,Ltd',
  0xFD43: 'Apple Inc.',
  0xFD44: 'Apple Inc.',
  0xFD45: 'GB Solution co.,Ltd',
  0xFD46: 'Lemco IKE',
  0xFD47: 'Liberty Global Inc.',
  0xFD48: 'Geberit International AG',
  0xFD49: 'Panasonic Corporation',
  0xFD4A: 'Sigma Elektro GmbH',
  0xFD4B: 'Samsung Electronics Co., Ltd.',
  0xFD4C: 'Adolf Wuerth GmbH & Co KG',
  0xFD4D: '70mai Co.,Ltd.',
  0xFD4E: '70mai Co.,Ltd.',
  0xFD4F: 'SONITOR TECHNOLOGIES AS',
  0xFD50: 'Hangzhou Tuya Information Technology Co., Ltd',
  0xFD51: 'UTC Fire and Security',
  0xFD52: 'UTC Fire and Security',
  0xFD53: 'PCI Private Limited',
  0xFD54: 'Qingdao Haier Technology Co., Ltd.',
  0xFD55: 'Braveheart Wireless, Inc.',
  0xFD56: 'Resmed Ltd',
  0xFD57: 'Volvo Car Corporation',
  0xFD58: 'Volvo Car Corporation',
  0xFD59: 'Samsung Electronics Co., Ltd.',
  0xFD5A: 'Samsung Electronics Co., Ltd.',
  0xFD5B: 'V2SOFT INC.',
  0xFD5C: 'React Mobile',
  0xFD5D: 'maxon motor ltd.',
  0xFD5E: 'Tapkey GmbH',
  0xFD5F: 'Meta Platforms Technologies, LLC',
  0xFD60: 'Sercomm Corporation',
  0xFD61: 'Arendi AG',
  0xFD62: 'Google LLC',
  0xFD63: 'Google LLC',
  0xFD64: 'INRIA',
  0xFD65: 'Razer Inc.',
  0xFD66: 'Zebra Technologies Corporation',
  0xFD67: 'Montblanc Simplo GmbH',
  0xFD68: 'Ubique Innovation AG',
  0xFD69: 'Samsung Electronics Co., Ltd',
  0xFD6A: 'Emerson',
  0xFD6B: 'rapitag GmbH',
  0xFD6C: 'Samsung Electronics Co., Ltd.',
  0xFD6D: 'Sigma Elektro GmbH',
  0xFD6E: 'Polidea sp. z o.o.',
  0xFD6F: 'Apple, Inc.',
  0xFD70: 'GuangDong Oppo Mobile Telecommunications Corp., Ltd',
  0xFD71: 'GN Hearing A/S',
  0xFD72: 'Logitech International SA',
  0xFD73: 'BRControls Products BV',
  0xFD74: 'BRControls Products BV',
  0xFD75: 'Insulet Corporation',
  0xFD76: 'Insulet Corporation',
  0xFD77: 'Withings',
  0xFD78: 'Withings',
  0xFD79: 'Withings',
  0xFD7A: 'Withings',
  0xFD7B: 'WYZE LABS, INC.',
  0xFD7C: 'Toshiba Information Systems(Japan) Corporation',
  0xFD7D: 'Center for Advanced Research Wernher Von Braun',
  0xFD7E: 'Samsung Electronics Co., Ltd.',
  0xFD7F: 'Husqvarna AB',
  0xFD80: 'Phindex Technologies, Inc',
  0xFD81: 'CANDY HOUSE, Inc.',
  0xFD82: 'Sony Corporation',
  0xFD83: 'iNFORM Technology GmbH',
  0xFD84: 'Tile, Inc.',
  0xFD85: 'Husqvarna AB',
  0xFD86: 'Abbott',
  0xFD87: 'Google LLC',
  0xFD88: 'Urbanminded LTD',
  0xFD89: 'Urbanminded LTD',
  0xFD8A: 'Signify Netherlands B.V.',
  0xFD8B: 'Jigowatts Inc.',
  0xFD8C: 'Google LLC',
  0xFD8D: 'quip NYC Inc.',
  0xFD8E: 'Motorola Solutions',
  0xFD90: 'Guangzhou SuperSound Information Technology Co.,Ltd',
  0xFD91: 'Groove X, Inc.',
  0xFD92: 'Qualcomm Technologies International, Ltd. (QTIL)',
  0xFD93: 'Bayerische Motoren Werke AG',
  0xFD94: 'Hewlett Packard Enterprise',
  0xFD95: 'Rigado',
  0xFD96: 'Google LLC',
  0xFD97: 'June Life, Inc.',
  0xFD98: 'Disney Worldwide Services, Inc.',
  0xFD99: 'ABB Oy',
  0xFD9A: 'Huawei Technologies Co., Ltd.',
  0xFD9B: 'Huawei Technologies Co., Ltd.',
  0xFD9C: 'Huawei Technologies Co., Ltd.',
  0xFD9D: 'Gastec Corporation',
  0xFD9E: 'The Coca-Cola Company',
  0xFD9F: 'VitalTech Affiliates LLC',
  0xFDA0: 'Secugen Corporation',
  0xFDA1: 'Groove X, Inc',
  0xFDA2: 'Groove X, Inc',
  0xFDA3: 'Inseego Corp.',
  0xFDA4: 'Inseego Corp.',
  0xFDA5: 'Neurostim OAB, Inc.',
  0xFDA6: 'WWZN Information Technology Company Limited',
  0xFDA7: 'WWZN Information Technology Company Limited',
  0xFDA8: 'PSA Peugeot Citroën',
  0xFDA9: 'Rhombus Systems, Inc.',
  0xFDAA: 'Xiaomi Inc.',
  0xFDAB: 'Xiaomi Inc.',
  0xFDAC: 'Tentacle Sync GmbH',
  0xFDAD: 'Houwa System Design, k.k.',
  0xFDAE: 'Houwa System Design, k.k.',
  0xFDAF: 'Wiliot LTD',
  0xFDB0: 'Oura Health Ltd',
  0xFDB1: 'Oura Health Ltd',
  0xFDB2: 'Portable Multimedia Ltd',
  0xFDB3: 'Audiodo AB',
  0xFDB4: 'HP Inc',
  0xFDB5: 'ECSG',
  0xFDB6: 'GWA Hygiene GmbH',
  0xFDB7: 'LivaNova USA Inc.',
  0xFDB8: 'LivaNova USA Inc.',
  0xFDBB: 'Profoto',
  0xFDBC: 'Emerson',
  0xFDBD: 'Clover Network, Inc.',
  0xFDBE: 'California Things Inc.',
  0xFDBF: 'California Things Inc.',
  0xFDC0: 'Hunter Douglas',
  0xFDC1: 'Hunter Douglas',
  0xFDC2: 'Baidu Online Network Technology (Beijing) Co., Ltd',
  0xFDC3: 'Baidu Online Network Technology (Beijing) Co., Ltd',
  0xFDC4: 'Simavita (Aust) Pty Ltd',
  0xFDC5: 'Automatic Labs',
  0xFDC6: 'Eli Lilly and Company',
  0xFDC7: 'Eli Lilly and Company',
  0xFDC8: 'Hach – Danaher',
  0xFDC9: 'Busch-Jaeger Elektro GmbH',
  0xFDCA: 'Fortin Electronic Systems',
  0xFDCB: 'Meggitt SA',
  0xFDCC: 'Shoof Technologies',
  0xFDCD: 'Qingping Technology (Beijing) Co., Ltd.',
  0xFDCE: 'SENNHEISER electronic GmbH & Co. KG',
  0xFDCF: 'Nalu Medical, Inc',
  0xFDD0: 'Huawei Technologies Co., Ltd',
  0xFDD1: 'Huawei Technologies Co., Ltd',
  0xFDD2: 'Bose Corporation',
  0xFDD3: 'FUBA Automotive Electronics GmbH',
  0xFDD4: 'LX Solutions Pty Limited',
  0xFDD5: 'Brompton Bicycle Ltd',
  0xFDD6: 'Ministry of Supply',
  0xFDD7: 'Copeland Cold Chain LP',
  0xFDD8: 'Jiangsu Teranovo Tech Co., Ltd.',
  0xFDD9: 'Jiangsu Teranovo Tech Co., Ltd.',
  0xFDDA: 'MHCS',
  0xFDDB: 'Samsung Electronics Co., Ltd.',
  0xFDDC: '4iiii Innovations Inc.',
  0xFDDD: 'Arch Systems Inc',
  0xFDDE: 'Noodle Technology Inc.',
  0xFDDF: 'Harman International',
  0xFDE0: 'John Deere',
  0xFDE1: 'Fortin Electronic Systems',
  0xFDE2: 'Google LLC',
  0xFDE3: 'Abbott Diabetes Care',
  0xFDE4: 'JUUL Labs, Inc.',
  0xFDE5: 'SMK Corporation',
  0xFDE6: 'Intelletto Technologies Inc',
  0xFDE7: 'SECOM Co., LTD',
  0xFDE8: 'Robert Bosch GmbH',
  0xFDE9: 'Spacesaver Corporation',
  0xFDEA: 'SeeScan, Inc',
  0xFDEB: 'Syntronix Corporation',
  0xFDEC: 'Mannkind Corporation',
  0xFDED: 'Pole Star',
  0xFDEE: 'Huawei Technologies Co., Ltd.',
  0xFDEF: 'ART AND PROGRAM, INC.',
  0xFDF0: 'Google LLC',
  0xFDF1: 'LAMPLIGHT Co.,Ltd',
  0xFDF2: 'AMICCOM Electronics Corporation',
  0xFDF3: 'Amersports',
  0xFDF4: 'O. E. M. Controls, Inc.',
  0xFDF5: 'Milwaukee Electric Tools',
  0xFDF6: 'AIAIAI ApS',
  0xFDF7: 'HP Inc.',
  0xFDF8: 'Onvocal',
  0xFDF9: 'INIA',
  0xFDFA: 'Tandem Diabetes Care',
  0xFDFB: 'Tandem Diabetes Care',
  0xFDFC: 'Optrel AG',
  0xFDFD: 'RecursiveSoft Inc.',
  0xFDFE: 'ADHERIUM(NZ) LIMITED',
  0xFDFF: 'OSRAM GmbH',
  0xFE00: 'Amazon.com Services, Inc.',
  0xFE01: 'Duracell U.S. Operations Inc.',
  0xFE02: 'Robert Bosch GmbH',
  0xFE03: 'Amazon.com Services, Inc.',
  0xFE04: 'Motorola Solutions, Inc.',
  0xFE05: 'CORE Transport Technologies NZ Limited',
  0xFE06: 'Qualcomm Technologies, Inc.',
  0xFE07: 'Sonos, Inc.',
  0xFE08: 'Microsoft',
  0xFE09: 'Pillsy, Inc.',
  0xFE0A: 'ruwido austria gmbh',
  0xFE0B: 'ruwido austria gmbh',
  0xFE0C: 'Procter & Gamble',
  0xFE0D: 'Procter & Gamble',
  0xFE0E: 'Setec Pty Ltd',
  0xFE0F: 'Signify Netherlands B.V. (formerly Philips Lighting B.V.)',
  0xFE10: 'LAPIS Technology Co., Ltd.',
  0xFE11: 'GMC-I Messtechnik GmbH',
  0xFE12: 'M-Way Solutions GmbH',
  0xFE13: 'Apple Inc.',
  0xFE14: 'Flextronics International USA Inc.',
  0xFE15: 'Amazon.com Services, Inc..',
  0xFE16: 'Footmarks, Inc.',
  0xFE17: 'Telit Wireless Solutions GmbH',
  0xFE18: 'Runtime, Inc.',
  0xFE19: 'Google LLC',
  0xFE1A: 'Tyto Life LLC',
  0xFE1B: 'Tyto Life LLC',
  0xFE1C: 'NetMedia, Inc.',
  0xFE1D: 'Illuminati Instrument Corporation',
  0xFE1E: 'LAMPLIGHT Co., Ltd.',
  0xFE1F: 'Garmin International, Inc.',
  0xFE20: 'Emerson',
  0xFE21: 'Bose Corporation',
  0xFE22: 'Zoll Medical Corporation',
  0xFE23: 'Zoll Medical Corporation',
  0xFE24: 'August Home Inc',
  0xFE25: 'Apple, Inc.',
  0xFE26: 'Google LLC',
  0xFE27: 'Google LLC',
  0xFE28: 'Ayla Networks',
  0xFE29: 'Gibson Innovations',
  0xFE2A: 'DaisyWorks, Inc.',
  0xFE2B: 'ITT Industries',
  0xFE2C: 'Google LLC',
  0xFE2D: 'LAMPLIGHT Co., Ltd.',
  0xFE2E: 'ERi,Inc.',
  0xFE2F: 'CRESCO Wireless, Inc',
  0xFE30: 'Volkswagen AG',
  0xFE31: 'Volkswagen AG',
  0xFE32: 'Pro-Mark, Inc.',
  0xFE33: 'CHIPOLO d.o.o.',
  0xFE34: 'SmallLoop LLC',
  0xFE35: 'HUAWEI Technologies Co., Ltd',
  0xFE36: 'HUAWEI Technologies Co., Ltd',
  0xFE39: 'TTS Tooltechnic Systems AG & Co. KG',
  0xFE3A: 'TTS Tooltechnic Systems AG & Co. KG',
  0xFE3B: 'Dolby Laboratories',
  0xFE3C: 'alibaba',
  0xFE3D: 'BD Medical',
  0xFE3E: 'BD Medical',
  0xFE3F: 'Friday Labs Limited',
  0xFE40: 'Inugo Systems Limited',
  0xFE41: 'Inugo Systems Limited',
  0xFE42: 'Nets A/S',
  0xFE43: 'Andreas Stihl AG & Co. KG',
  0xFE44: 'SK Telecom',
  0xFE45: 'Snapchat Inc',
  0xFE46: 'B&O Play A/S',
  0xFE47: 'General Motors',
  0xFE48: 'General Motors',
  0xFE49: 'SenionLab AB',
  0xFE4A: 'OMRON HEALTHCARE Co., Ltd.',
  0xFE4B: 'Signify Netherlands B.V. (formerly Philips Lighting B.V.)',
  0xFE4C: 'Volkswagen AG',
  0xFE4D: 'Casambi Technologies Oy',
  0xFE4E: 'NTT docomo',
  0xFE4F: 'Molekule, Inc.',
  0xFE50: 'Google LLC',
  0xFE51: 'SRAM',
  0xFE52: 'SetPoint Medical',
  0xFE53: '3M',
  0xFE54: 'Motiv, Inc.',
  0xFE55: 'Google LLC',
  0xFE56: 'Google LLC',
  0xFE57: 'Dotted Labs',
  0xFE58: 'Nordic Semiconductor ASA',
  0xFE59: 'Nordic Semiconductor ASA',
  0xFE5A: 'Cronologics Corporation',
  0xFE5B: 'GT-tronics HK Ltd',
  0xFE5C: 'million hunters GmbH',
  0xFE5D: 'Grundfos A/S',
  0xFE5E: 'Plastc Corporation',
  0xFE5F: 'Eyefi, Inc.',
  0xFE60: 'Lierda Science & Technology Group Co., Ltd.',
  0xFE61: 'Logitech International SA',
  0xFE62: 'Indagem Tech LLC',
  0xFE63: 'Connected Yard, Inc.',
  0xFE64: 'Siemens AG',
  0xFE65: 'CHIPOLO d.o.o.',
  0xFE66: 'Intel Corporation',
  0xFE67: 'Lab Sensor Solutions',
  0xFE68: 'Capsle Technologies Inc.',
  0xFE69: 'Capsle Technologies Inc.',
  0xFE6A: 'Kontakt Micro-Location Sp. z o.o.',
  0xFE6B: 'TASER International, Inc.',
  0xFE6C: 'TASER International, Inc.',
  0xFE6D: 'The University of Tokyo',
  0xFE6E: 'The University of Tokyo',
  0xFE6F: 'LINE Corporation',
  0xFE70: 'Beijing Jingdong Century Trading Co., Ltd.',
  0xFE71: 'Plume Design Inc',
  0xFE72: 'Abbott (formerly St. Jude Medical, Inc.)',
  0xFE73: 'Abbott (formerly St. Jude Medical, Inc.)',
  0xFE74: 'unwire',
  0xFE75: 'TangoMe',
  0xFE76: 'TangoMe',
  0xFE77: 'Hewlett-Packard Company',
  0xFE78: 'Hewlett-Packard Company',
  0xFE79: 'Zebra Technologies',
  0xFE7A: 'Bragi GmbH',
  0xFE7B: 'Orion Labs, Inc.',
  0xFE7C: 'Telit Wireless Solutions (Formerly Stollmann E+V GmbH)',
  0xFE7D: 'Aterica Health Inc.',
  0xFE7E: 'Awear Solutions Ltd',
  0xFE7F: 'Doppler Lab',
  0xFE80: 'Doppler Lab',
  0xFE81: 'Medtronic Inc.',
  0xFE82: 'Medtronic Inc.',
  0xFE83: 'Blue Bite',
  0xFE84: 'RF Digital Corp',
  0xFE85: 'RF Digital Corp',
  0xFE86: 'HUAWEI Technologies Co., Ltd',
  0xFE87: 'Qingdao Yeelink Information Technology Co., Ltd. ( 青岛亿联客信息技术有限公司 )',
  0xFE88: 'SALTO SYSTEMS S.L.',
  0xFE89: 'B&O Play A/S',
  0xFE8A: 'Apple, Inc.',
  0xFE8B: 'Apple, Inc.',
  0xFE8C: 'TRON Forum',
  0xFE8D: 'Interaxon Inc.',
  0xFE8E: 'ARM Ltd',
  0xFE8F: 'CSR',
  0xFE90: 'JUMA',
  0xFE91: 'Shanghai Imilab Technology Co.,Ltd',
  0xFE92: 'Jarden Safety & Security',
  0xFE93: 'OttoQ In',
  0xFE94: 'OttoQ In',
  0xFE95: 'Xiaomi Inc.',
  0xFE96: 'Tesla Motors Inc.',
  0xFE97: 'Tesla Motors Inc.',
  0xFE98: 'Currant Inc',
  0xFE99: 'Currant Inc',
  0xFE9A: 'Estimote',
  0xFE9B: 'Samsara Networks, Inc',
  0xFE9C: 'GSI Laboratories, Inc.',
  0xFE9D: 'Mobiquity Networks Inc',
  0xFE9E: 'Renesas Design Netherlands B.V.',
  0xFE9F: 'Google LLC',
  0xFEA0: 'Google LLC',
  0xFEA3: 'ITT Industries',
  0xFEA4: 'Paxton Access Ltd',
  0xFEA5: 'GoPro, Inc.',
  0xFEA6: 'GoPro, Inc.',
  0xFEA7: 'UTC Fire and Security',
  0xFEA8: 'Savant Systems LLC',
  0xFEA9: 'Savant Systems LLC',
  0xFEAA: 'Google LLC',
  0xFEAB: 'Nokia',
  0xFEAC: 'Nokia',
  0xFEAD: 'Nokia',
  0xFEAE: 'Nokia',
  0xFEAF: 'Nest Labs Inc',
  0xFEB0: 'Nest Labs Inc',
  0xFEB1: 'Electronics Tomorrow Limited',
  0xFEB2: 'Microsoft Corporation',
  0xFEB3: 'Taobao',
  0xFEB4: 'WiSilica Inc.',
  0xFEB5: 'WiSilica Inc.',
  0xFEB6: 'Vencer Co., Ltd',
  0xFEB7: 'Meta Platforms, Inc.',
  0xFEB8: 'Meta Platforms, Inc.',
  0xFEB9: 'LG Electronics',
  0xFEBA: 'Tencent Holdings Limited',
  0xFEBB: 'adafruit industries',
  0xFEBC: 'Dexcom Inc',
  0xFEBD: 'Clover Network, Inc',
  0xFEBE: 'Bose Corporation',
  0xFEBF: 'Nod, Inc.',
  0xFEC0: 'KDDI Corporation',
  0xFEC1: 'KDDI Corporation',
  0xFEC2: 'Blue Spark Technologies, Inc.',
  0xFEC3: '360fly, Inc.',
  0xFEC4: 'PLUS Location Systems',
  0xFEC5: 'Realtek Semiconductor Corp.',
  0xFEC6: 'Kocomojo, LLC',
  0xFEC7: 'Apple, Inc.',
  0xFEC8: 'Apple, Inc.',
  0xFEC9: 'Apple, Inc.',
  0xFECA: 'Apple, Inc.',
  0xFECB: 'Apple, Inc.',
  0xFECC: 'Apple, Inc.',
  0xFECD: 'Apple, Inc.',
  0xFECE: 'Apple, Inc.',
  0xFECF: 'Apple, Inc.',
  0xFED0: 'Apple, Inc.',
  0xFED1: 'Apple, Inc.',
  0xFED2: 'Apple, Inc.',
  0xFED3: 'Apple, Inc.',
  0xFED4: 'Apple, Inc.',
  0xFED5: 'Plantronics Inc.',
  0xFED6: 'Broadcom',
  0xFED7: 'Broadcom',
  0xFED8: 'Google LLC',
  0xFED9: 'Pebble Technology Corporation',
  0xFEDA: 'ISSC Technologies Corp.',
  0xFEDB: 'Perka, Inc.',
  0xFEDC: 'Jawbone',
  0xFEDD: 'Jawbone',
  0xFEDE: 'Coin, Inc.',
  0xFEE0: 'Anhui Huami Information Technology Co., Ltd.',
  0xFEE1: 'Anhui Huami Information Technology Co., Ltd.',
  0xFEE2: 'Anki, Inc.',
  0xFEE3: 'Anki, Inc.',
  0xFEE4: 'Nordic Semiconductor ASA',
  0xFEE5: 'Nordic Semiconductor ASA',
  0xFEE6: 'Silvair, Inc.',
  0xFEE7: 'Tencent Holdings Limited.',
  0xFEE8: 'Quintic Corp.',
  0xFEE9: 'Quintic Corp.',
  0xFEEA: 'Swirl Networks, Inc.',
  0xFEEB: 'Swirl Networks, Inc.',
  0xFEEC: 'Tile, Inc.',
  0xFEED: 'Tile, Inc.',
  0xFEEE: 'Polar Electro Oy',
  0xFEEF: 'Polar Electro Oy',
  0xFEF0: 'Intel',
  0xFEF1: 'CSR',
  0xFEF2: 'CSR',
  0xFEF3: 'Google LLC',
  0xFEF4: 'Google LLC',
  0xFEF5: 'Dialog Semiconductor GmbH',
  0xFEF6: 'Wicentric, Inc.',
  0xFEF7: 'Aplix Corporation',
  0xFEF8: 'Aplix Corporation',
  0xFEF9: 'PayPal, Inc.',
  0xFEFA: 'PayPal, Inc.',
  0xFEFB: 'Telit Wireless Solutions (Formerly Stollmann E+V GmbH)',
  0xFEFC: 'Gimbal, Inc.',
  0xFEFD: 'Gimbal, Inc.',
  0xFEFE: 'GN Hearing A/S',
  0xFEFF: 'GN Netcom',
};

/// Standards Development Organization UUIDs (`0xFFxx`), allocated to another
/// standards body.
const Map<int, String> sdoUuidNames = {
  0xFCCC: 'Wi-Fi Easy Connect Specification',
  0xFFEF: 'Wi-Fi Direct Specification',
  0xFFF0: 'Public Key Open Credential (PKOC)',
  0xFFF1: 'ICCE Digital Key',
  0xFFF2: 'Aliro',
  0xFFF3: 'FiRa Consortium',
  0xFFF4: 'FiRa Consortium',
  0xFFF5: 'Car Connectivity Consortium, LLC',
  0xFFF6: 'Matter Profile ID',
  0xFFF7: 'Zigbee Direct',
  0xFFF8: 'Mopria Alliance BLE',
  0xFFF9: 'FIDO2 secure client-to-authenticator transport',
  0xFFFA: 'ASTM Remote ID',
  0xFFFB: 'Direct Thread Commissioning',
  0xFFFC: 'Wireless Power Transfer (WPT)',
  0xFFFD: 'Universal Second Factor Authenticator',
  0xFFFE: 'Wireless Power Transfer',
};
